### ISSUE TITLE
Can I have an expression to show function return value

### ISSUE THREAD

**Issue by amosbird** [cyrus-and/gdb-dashboard#103]
I'd like to make function return value be listed in the expression dashboard and persist until another function call returns.

**Comment by cyrus-and** [comment]
I'm not sure I'm fully understanding what you're asking here, a function call is an expression just like any other, so for example:

    dashboard expressions watch strerror(i)

will print the return value of `strerror` whatever is the value of `i` at the time of evaluation.

Does this answer your question?

**Comment by amosbird** [comment]
Nope. I meant to have something like this
```
dashboard expressions watch $ret
```
so that every function returning triggers an update of the $ret value.

**Comment by cyrus-and** [comment]
I don't think it's possible, and in case that would be the only the *last* return value as many function may potentially be called when the inferior continues.

In any case this would be something about GDB itself, you may want to try to ask it in their mailing list or IRC channel.
