### ISSUE TITLE
Move Locals for Current Stack into Separate Module

### ISSUE THREAD

**Issue by neerajbadlani** [cyrus-and/gdb-dashboard#107]
Functions with large number of locals clutter stack module .
Also , if a local object , can be expanded into subobjects ( like it happens in gdbgui)

THanks

**Comment by cyrus-and** [comment]
> Functions with large number of locals clutter stack module .

You know that you can disable arguments and locals via `dashboard stack -style ...`, right? Also, there is a compact mode.

> Also , if a local object , can be expanded into subobjects ( like it happens in gdbgui)

Please clarify.

**Comment by neerajbadlani** [comment]
Well , yeah , I can disable/condense , but what I was suggesting is that , if they had their own layout "window" , like source or stack , that will be better , I will be able to get more frames fit in stack tty, and i can keep eye on the locals and args on seperate tty. 
Attached the image ( also notice + signs under an object , which further expands )

Please let me know if something not clear.

![screen shot 2018-02-28 at 8 29 29 am](https://user-images.githubusercontent.com/3440085/36799308-b0e9ba3e-1c61-11e8-8809-010a7be767aa.jpeg)

**Comment by cyrus-and** [comment]
I could *replicate* the locals and arguments of the current frame in another module (say "Variables") I guess. But I don't see how can I implement the + sign since no user interaction is available here, only commands.

**Comment by noscript** [comment]
+1 I would want expandable local variables, something what `lldb` TUI mode can do.

Allowing user interactions would bring the dashboard to a whole new level. For one, it would also solve #131.

**Comment by cyrus-and** [comment]
@noscript

> Allowing user interactions would bring the dashboard to a whole new level. For one, it would also solve #131.

User interaction is something that's not possible, the dashboard never meant to be (and will never be) a GDB frontend.

> A solution using command could be to give a number to each line of the stack widget, so it would be possible to address variables by number and therefor be able expand them.

Yes, but that would be super awkward to use.

**Comment by noscript** [comment]
>Yes, but that would be super awkward to use.

Another idea is to have a cursor in stack widget that can move up and down (two commands), and a third command to toggle the expand.

**Comment by cyrus-and** [comment]
A new module (Variables) has been added and some defaults have been changed.

The "expand" part it's unlikely to happen, sorry.
