### ISSUE TITLE
How to manually enlarge size of some fields, such as assembly and source ? 

### ISSUE THREAD

**Issue by punkofnewsociety** [cyrus-and/gdb-dashboard#109]
How to manually enlarge size of some fields, such as assembly and source ? 
too little lines ( 5-6 in my case) i got empty space and not satisfied 
![ebota10](https://user-images.githubusercontent.com/6445282/37770678-418d6ff0-2de6-11e8-8bc3-3607de65516e.png)

**Comment by cyrus-and** [comment]
Using the `context` style, like:

```
dashboard assembly -style context 20
dashboard source -style context 20
```

**Comment by YayDebug** [comment]
Excuse me for commenting here, but how do you get the multiple colums for the different dashboard elements? I could not find anything....

**Comment by linxon** [comment]
@YayDebug https://gist.github.com/henrik/1967800

**Comment by YayDebug** [comment]
@linxon thank you!
