### ISSUE TITLE
style_low Text isn't shown properly on putty

### ISSUE THREAD

**Issue by sthuck** [cyrus-and/gdb-dashboard#11]
Not really an issue, but I'd recommend adding some FAQ section in readme to answer this. It drove me nuts and as putty is very popular I assume others are going to run into this issue. Putty shows bold grey text as black, which is the default background.

To fix:
either change the color:  dashboard -style style_low '36'   
Or change putty settings: window->Colours->'Indicate bolded text by changing by changing:'->The colour\Both

**Comment by cyrus-and** [comment]
Isn't this [already fixed](http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/bold-font-default.html) in the latest version of PuTTY?

**Comment by soerenb** [comment]
I have that problem (noticed it with 'prompt_not_running') running putty 0.65 (but colors in putty always seem a little off compared to a native terminal). Changing the dashboard style didn't help it, but I could fix it in putty adjusting the settings as @sthuck suggested. Thanks!

**Comment by cyrus-and** [comment]
I don't know... I tried and it seems working with version 0.65.
In any case it is almost surely a problem with PuTTY, so I'm closing this.

@soerenb The colors strongly depends on your terminal setting.

@sthuck Anyway thanks for this, now I know, just in case someone else should experience this.
