### ISSUE TITLE
AttributeError on sourcing gdbinit

### ISSUE THREAD

**Issue by hektzu** [cyrus-and/gdb-dashboard#111]
I get this error while loading the script.

```
Traceback (most recent call last):
 File "<string>", line 417, in custom_prompt
 AttributeError: type object 'R' has no attribute 'prompt_not_running'
```

It seems that object R has its attributes unset in context of method `custom_prompt()` even though printing `R.__dict__` gives all the correct attributes called from `set_custom_prompt()`.

I _solved_ this by appending 

```py
for name, attribute in R.attributes().items():
    attr_name = attribute.get('name', name)
    attr_type = attribute.get('type', str)
    attr_check = attribute.get('check', lambda _: True)
    attr_default = attribute['default']
    value = attr_type(attr_default)
    setattr(R, attr_name, value) 
```
at the start of `custom_prompt()`. So currently I have working setup but it would be nice to find the fix for the root cause in case someone else has the same problem.

```
python --version
Python 3.6.4
```
```
gdb --version
GNU gdb (GDB) 8.1
```

**Comment by cyrus-and** [comment]
> python --version
> Python 3.6.4

That's the system version of Python, to see the one with which GDB had been compiled run from GDB itself:

    python import sys; print(sys.version)

**Comment by hektzu** [comment]
```
python import sys; print(sys.version)
3.6.4 (default, Jan  5 2018, 02:35:40)
[GCC 7.2.1 20171224]
```
It is compiled with the correct python version and even if wasn't that wouldn't explain the error, would it?

**Comment by cyrus-and** [comment]
Probably not, just wanted to rule out extremely old versions of Python.

**Comment by cyrus-and** [comment]
I can only reproduce a similar behavior if I comment [this][1] line. How do you exactly load the script? Show me all the steps even if they're obvious and if you use `source /path/to/dashboard` try starting GDB with `-nx`.

[1]: https://github.com/cyrus-and/gdb-dashboard/blob/ae7cbaeaa07ca3739914cfec7774c3baea2e89b1/.gdbinit#L245

**Comment by hektzu** [comment]
I have the script in ~/.gdbinit.d/init and I load it with `source ~/.gdbinit/init`.

After debuggin bit more I noticed that just by sourcing the script gdb goes unresponsive for few moments and floods terminal with
```
Error while executing Python code.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 392, in start
  File "<string>", line 438, in parse_inits
gdb.error: /home/heka/.gdbinit.d/init:1542: Error in sourced command file:
```
There are over 1000 lines of this.

The line in question is `python Dashboard.start()`.
And the weird thing is that if I comment that line and start the dashboard manually it works.

The other thing I noticed is that placing `print(id(R))` in `Dashboard.start()`, `Dashboard.set_custom_prompt()` and `custom_prompt()` methods I get the same id with the first and the second print but the third is different.

Example output:
```python
94072694464952  #start()
94072694464952  #set_custom_prompt()
94072695251720  #custom_prompt()
```

`id()` method in python returns id of an object and that id should be unique during its lifetime.
So `R` in `custom_prompt` is different from what it was in other functions and its attributes are unset.
Clearly something is happening with the custom prompt function closure.

**Comment by cyrus-and** [comment]
> One thing I noticed is that placing print(id(R)) in Dashboard.start(), Dashboard.set_custom_prompt() and custom_prompt() methods I get the same id with the first and the second print but the third is different.

I did the same and I obtain the same id in all the cases.

**Comment by hektzu** [comment]
What gdb version are you using? And what about python? I tested printing the ids with gdb 7.12.1 and still got different ids.

I wouldn't go earlier than 7.12 with the gdb as I need the Rust support introduced in that release.

I wonder if this have something to do with the python API as it seems that almost all release has changes to python API or atleast _enhancements_.

And do you know what would be the easiest way to test with different python versions without downgrading as I would like to keep most current python as my system wide release?

**Comment by cyrus-and** [comment]
> What gdb version are you using? And what about python?

I tried with both:
- GDB 8.0 / Python 3.5.3
- GDB Debian 7.12-6 / Python 3.5.3

> And do you know what would be the easiest way to test with different python versions without downgrading as I would like to keep most current python as my system wide release?

I managed to do that by installing everything in `/opt/` and compiling GDB with `./configure --with-python=/opt/python-xxx/bin/python-xxx`. But I face some issues now, GDB is actually compiled with Python but the `gdb` object is not present.

**Comment by hektzu** [comment]
Did you install GDB to your systems directory or did you just run it where it was built?
I did need to specify `--data-directory` when running GDB from build directory.
So after building I ran ` ./gdb --data-directory=data-directory/` in /path/to/gdb-7.12.1/gdb.

**Comment by cyrus-and** [comment]
> Did you install GDB to your systems directory or did you just run it where it was built?

I tried both, same outcome.

In any case I'm having hard time reproducing your issue.

**Comment by hektzu** [comment]
That gives perfectly correct output:
``` 
94621531081160
94621531081160
```
Tried with GDB 8.1 and 7.12.1 and Python 3.6.5.

**Comment by hektzu** [comment]
I did some further investigation by cutting and pasting only the essential pieces (for initial prompt).
The code I used is found [here](https://gist.github.com/hektzu/5d87773626964202828b2be7ea84ad67)
This also gives correct output 
```
93940185499592
93940185499592
93940185499592
```
so point of _failure_ might not be here.

Just wondering if there's any chance to attach debugger to the python module. (debuggerception :grin: )
Maybe with [pdb](https://docs.python.org/3.6/library/pdb.html).

**Comment by cyrus-and** [comment]
> Just wondering if there's any chance to attach debugger to the python module.

You surely can do that, place the following line where you want to break:

```py
import pdb; pdb.set_trace()
```

**Comment by cyrus-and** [comment]
Did you get any further with this?

**Comment by hackingwu** [comment]
PyImport_Import() fail:

ImportError: xxxx undefined symbol: PyExc_ValueError


If when you didn't `./configure --enable-shared`, there is only libpython*a under /usr/local/lib, But GDB need libpython*so.

Resolution is：
So, Two resolution. 
1. rebuild python with enable-shared configuration and rebuild gdb again
2. just rebuild gdb, add 'export-dynamic' to C_FLAGS in GDB makefile

**Comment by cyrus-and** [comment]
@hackingwu if I compile Python with the `--enable-shared` option then the binary comes with some misconfigured library path and dies with:

```console
$ /opt/python-3.6.5/bin/python3                                        
/opt/python-3.6.5/bin/python3: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

The library exists but Python is unable to find it unless I explicitly set the `LD_LIBRARY_PATH` environment variable.

Anyway GDB refuses to compile with these settings.

**Comment by hackingwu** [comment]
yes, so I add python conf to /etc/ld.so.conf.d
Anyway, This issue can resolved by this method. I'm using a very old system Redhat 5.3, So I upgrade pythone by building it. Maybe this issue is because the python isn't builtin.
