### ISSUE TITLE
How to change the order of different modules?

### ISSUE THREAD

**Issue by wind2412** [cyrus-and/gdb-dashboard#112]
For example, I want to switch the position of `Threads` to the top of `Assembly`, because maybe the program has too many threads at one time... but I didn't find the code of the output order because I'm not good at python, TIA.

**Comment by cyrus-and** [comment]
You can just use the [`-layout`][1] command, the order in which you specify the modules is the one in which they are displayed. Say you want source, threads and assembly (in this order):

    dashboard -layout source threads assembly

[1]: https://github.com/cyrus-and/gdb-dashboard#dashboard--layout-directive
