### ISSUE TITLE
gdb startup failure

### ISSUE THREAD

**Issue by zhangyafeikimi** [cyrus-and/gdb-dashboard#113]
the message containing gdb version is like:

GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 403, in start
  File "<string>", line 306, in load_modules
  File "<string>", line 509, in __init__
  File "<string>", line 539, in add_subcommands
  File "<string>", line 1517, in commands
AttributeError: 'module' object has no attribute 'COMPLETE_EXPRESSION'
/home/kimi/.gdbinit:1546: Error in sourced command file:
Error while executing Python code.
Reading symbols from /home/kimi/ycm/a.out...done.

**Comment by zhangyafeikimi** [comment]
What is the minimal supported gdb version?

And would you like to port gdb-dashboard to old gdb?

**Comment by cyrus-and** [comment]
See #115.
