### ISSUE TITLE
Is there a method to highlight source's current line?

### ISSUE THREAD

**Issue by iswade** [cyrus-and/gdb-dashboard#116]

**Comment by cyrus-and** [comment]
Nope, the current line is marked either using a `>` (if ANSI is off) or marking the line number with the user-provided ANSI style.

**Comment by cyrus-and** [comment]
OK, I just added the `highlight-line` option to Source and Assembly modules, if you set that to `True` then the corresponding style will be applied to the whole line. Please note that in order to override the Pygments style you need to specify the background, for example, red:

    dashboard -style style_selected_1 41

Or reverse video:

    dashboard -style style_selected_1 7

**Comment by iswade** [comment]
👍

**Comment by iswade** [comment]
Test it, but cannot override the Pygments color.

**Comment by cyrus-and** [comment]
Show me what you tried.

**Comment by cyrus-and** [comment]
In any case there are Pygments styles that resets the style after certain keywords (i.e., with `\x1b[0m`), this causes truncated selected lines like the following:

![scrot](https://user-images.githubusercontent.com/1660263/39621912-b44a37fa-4f90-11e8-9cc5-19f3394af9fb.png)

I was hoping that wasn't never the case... Unfortunately there's no way to *nest* ANSI styles AFAIK, I think I'm going to revert the change.

I don't know if it's possible to write a custom Pygments formatter that overrides the background color of each chunk.

---

Remember that if the syntax highlighting is disabled the whole line is styled anyway, even before 4328974b86f10ef4a7e828d647cd04d5c3a2f33e.

**Comment by muhmud** [comment]
It might be useful to have a separate style for the highlight line.

I found changing style 1 it interferes with breakpoints and threads.

**Comment by Lucifer-02** [comment]
![image](https://user-images.githubusercontent.com/84069686/233968108-941cc5c2-f1cc-4f7f-b0d6-4d02e5279c5b.png)
Do you mean like this?

**Comment by muhmud** [comment]
Actually, I mean if I use a multiple terminal configuration, as per the [wiki](https://github.com/cyrus-and/gdb-dashboard/wiki/Use-multiple-terminals), the highlight applies to parts of the breakpoints and threads output as well, which I would prefer were styled as before.

**Comment by cyrus-and** [comment]
> Actually, I mean if I use a multiple terminal configuration, as per the [wiki](https://github.com/cyrus-and/gdb-dashboard/wiki/Use-multiple-terminals), the highlight applies to parts of the breakpoints and threads output as well, which I would prefer were styled as before.

@muhmud What do you mean? Can you attach a screenshot and the configuration used to reproduce that?

**Comment by muhmud** [comment]
It was only a few code changes to implement my own `style_selected_3`

**Comment by czak** [comment]
This worked for me:

```diff
175a176,178
>             'style_selected_3': {
>                 'default': '40'
>             },
1255c1258
<                         line_format = '{}' + ansi(number_format, R.style_selected_1) + '  {}'
---
>                         line_format = '{}' + ansi(number_format, R.style_selected_3) + '  {}'
1257c1260
<                         line_format = '{}' + ansi(number_format + '  {}', R.style_selected_1)
---
>                         line_format = '{}' + ansi(number_format + '  {}', R.style_selected_3)
```

I'm having good results with color `40` (white background) and the `'arduino'` pygments theme on a light terminal:

![image](https://github.com/cyrus-and/gdb-dashboard/assets/14021/d56f0aca-a35f-411b-8041-f7af3476c5ae)
