### ISSUE TITLE
Cannot set breakpoints on future library loads when using gdb-dashboard

### ISSUE THREAD

**Issue by bluehood** [cyrus-and/gdb-dashboard#117]
Hi, 
for some reason without this `.gdbinit` I can do this:
```
gdb -nh foo.x
(gdb) break Obj::function
Function "Obj::function" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (CPyCppyy::tpp_call) pending.
```

With this `.gdbinit` present I only get:
```
gdb foo.x
>>> break CPyCppyy::tpp_call
Function "CPyCppyy::tpp_call" not defined.
>>> 
```

Is there any way to get the feature back?

**Comment by bluehood** [comment]
Yes, it's a surprising default because it silently hides a feature :)

I'll put `set confirm on` in my custom configuration for now -- I didn't know that option

**Comment by cyrus-and** [comment]
> I'll put set confirm on in my custom configuration for now -- I didn't know that option

Well there's no need anymore, since 61ba469788f51e1ba749e480c5d92b8f1fb2ff46 the dashboard uses the GDB default (which should be `on`).
