### ISSUE TITLE
Display message when module in separate terminal was disabled

### ISSUE THREAD

**Issue by DanielChabrowski** [cyrus-and/gdb-dashboard#118]
Hello, I discovered this project a few days ago and it's awesome.

When we disable the module in the dashboard output terminal, it gets updated and disabled modules disappear but it seems that when a module's output is going to a separate terminal there is no information that the module was disabled. I sat for like 5 minutes thinking why my Source module wasn't changing even though I moved to the other breakpoints and it turns out I changed the layout without adding it.

When gdb exits we get "--- EXITED ---" message in other terminals so maybe a "--- MODULE DISABLED ---" or something could be helpful ?

**Comment by cyrus-and** [comment]
Hey thanks! :)

And thanks for bringing up this issue. Now a `--- NO MODULE TO DISPLAY ---` message is displayed in separate terminals that have no enabled module.

Moreover a `--- RELEASED ---` message is displayed when a terminal is released.
