### ISSUE TITLE
Show filename in sources module

### ISSUE THREAD

**Issue by DenValk** [cyrus-and/gdb-dashboard#119]
It would be easier to loop up additional code around the displayed block using another editor if the sources module could display the name of the file containing the displayed code.

**Comment by cyrus-and** [comment]
You can use the `edit` GDB command for that, it opens the current source file using the program specified by the `EDITOR` environment variable. See `help edit` for more info.

**Comment by DenValk** [comment]
Sorry for wasting your time. This fits my use case perfectly. I leave less ignorant than I came.

**Comment by cyrus-and** [comment]
Hey, no time is wasted helping each others. :)
