### ISSUE TITLE
Use Intel flavor

### ISSUE THREAD

**Issue by canel-rom1** [cyrus-and/gdb-dashboard#121]
Hello,

It's possible to use Intel flavor? I looked but I'can't find an option.

Thank you
Best regards

**Comment by cyrus-and** [comment]
Sure, just do as you normally would in GDB alone:

    set disassembly-flavor intel

**Comment by maugier** [comment]
Perhaps the problem was that when you `set disassembly-flavor intel`, the dashboard view doesn't seem to update (either by calling `dashboard`, or turning off assembly view off and on again), but it does update correctly after a single `stepi` command.
