### ISSUE TITLE
Output is messed when opening the source panel (Ctrl-X a)

### ISSUE THREAD

**Issue by romgrk** [cyrus-and/gdb-dashboard#122]
![screenshot from 2018-06-28 12-45-22](https://user-images.githubusercontent.com/1423607/42048447-50e92650-7ad1-11e8-9490-5485971a293a.png)

**Comment by cyrus-and** [comment]
It looks like you're trying to use the dashboard with another frontend (GDB TUI?), it just doesn't work, it's an either-or situation.

**Comment by romgrk** [comment]
Is there a way to disable it when opening the GDB TUI? The GDB TUI is more useful for navigating assembly (allows to go up and down, not just see the IP & context)

**Comment by cyrus-and** [comment]
You can use `dashboard -enabled off`, but the prompt will be messed anyway.

Alternatively you can define custom commands like these:

```
define tui-on
dashboard -enabled off
dashboard -style prompt '(gdb)'
tui enable
end

define tui-off
tui disable
dashboard -style prompt '{status}'
dashboard -enabled on
end
```

**Comment by romgrk** [comment]
Good enough, thanks!

**Comment by cyrus-and** [comment]
Moreover, with a bit  of readline-fu you can bind them to a proper keybinding. For example add the following to your `~/.inputrc` to use `Alt-g` to toggle TUI mode.

```
$if Gdb
"\eg": "toggle-tui\n"
$endif
```

Also define:

```
set $tui = 0
define toggle-tui
  if $tui == 1
    tui disable
    dashboard -style prompt '{status}'
    dashboard -enabled on
    set $tui = 0
  else
    dashboard -enabled off
    dashboard -style prompt '(gdb)'
    tui enable
    set $tui = 1
  end
end
```
