### ISSUE TITLE
Install via wget -P

### ISSUE THREAD

**Issue by hansgans** [cyrus-and/gdb-dashboard#124]
I  had some custom stuff in my .gdbinit and the command:
```wget -P ~ git.io/.gdbinit```
gives a file which misses the `python` command on the beginning. I don't understand why this is the case but probably you should change in install section.

**Comment by cyrus-and** [comment]
If an existing `.gdbinit` is found in your home then wget don't overwrite it, rather it creates a copy, e.g., `.gdbinit.1` and place the download there. So at the end you end up with your old `.gdbinit` file, unchanged.

**Comment by hansgans** [comment]
I had a strange alias on `wget`.
