### ISSUE TITLE
Make dashboard refresh more eagerly

### ISSUE THREAD

**Issue by amosbird** [cyrus-and/gdb-dashboard#129]
When doing thread switching, dashboard doesn't refresh itself of the current thread info (expressions, stack, registers). This also happens when threads get interruptted. I have to issue a `next` command to get the up-to-date dashboard view. Can we at least have a dashboard refresh command? thanks!

**Comment by cyrus-and** [comment]
I'll look into it, simply redisplaying the dashboard (with `dashboard` or an abbreviation) will work too?

**Comment by amosbird** [comment]
ah, `dashboard` works.

**Comment by amosbird** [comment]
```

define hookpost-up
  dashboard
end

define hookpost-down
  dashboard
end

define hookpost-frame
  dashboard
end

define hook-stop
  dashboard
end

define hook-thread
  dashboard
end
```
