### ISSUE TITLE
Exception in Assembly Module

### ISSUE THREAD

**Issue by jez** [cyrus-and/gdb-dashboard#13]
When debugging a C++ program in gdb, I get this error as soon as I hit a breakpoint:

```
Traceback (most recent call last):
  File "<string>", line 184, in <lambda>
  File "<string>", line 203, in on_stop
  File "<string>", line 240, in build
  File "<string>", line 683, in lines
ValueError: invalid literal for int() with base 16: '0x000000010002e710:\tpush'
```

It looks like there's some issue with parsing some gdb output in the assembly module, because disabling it with

```
dashboard assembly
```

removes the error upon hitting a breakpoint.

**Comment by cyrus-and** [comment]
Thanks, I will look into this. In the meanwhile it would be great if you could send me a minimal program to reproduce it, or alternatively the output of the `disassemble` GDB command once you hit that breakpoint.

**Comment by jez** [comment]
I haven't been able to reproduce it with a smaller program, and I unfortunately the program it fails on is my homework, so I can't distribute it.

I'm pretty sure the error is due to a space vs. tab issue. I've made a patch (#14) that addresses it.

**Comment by cyrus-and** [comment]
> so I can't distribute it.

OK, I understand, I was asking because, for the moment being, I'am forced to parse the output of `disassemble` which is quite unreliable so I was interested in all the corner cases.

That patch does not properly parse all the relevant cases, see further comments on #14.
