### ISSUE TITLE
Add support of source code scroll

### ISSUE THREAD

**Issue by uboats** [cyrus-and/gdb-dashboard#131]
recently started to use gdb and found this awesome tool
however, i have to switch between this and tui when need to read code around

so i tried to add this feature myself, and finally made it (although just a walkaround solution)
problem of my try is that it requires more config in .inputrc and .gdbinit.d/init
can anyone help me improve it and make config as less as possible?

below is my changes:
**.gdbinit**

246a247
>         Dashboard.SrcScrollCommand(self)
510a512,532
>     @staticmethod
>     def source_scroll_up(dashboard):
>         for module in dashboard.modules:
>             if module.name == 'source':
>                 module.instance.scrl_up()
>         dashboard.redisplay()
> 
>     @staticmethod
>     def source_scroll_down(dashboard):
>         for module in dashboard.modules:
>             if module.name == 'source':
>                 module.instance.scrl_down()
>         dashboard.redisplay()
> 
>     @staticmethod
>     def source_scroll_reset(dashboard):
>         for module in dashboard.modules:
>             if module.name == 'source':
>                 module.instance.scrl_rst()
>         dashboard.redisplay()
> 
684a707,730
>     class SrcScrollCommand(gdb.Command):
> 
>         def __init__(self, dashboard):
>             gdb.Command.__init__(self, 'dashboard -srcscroll', gdb.COMMAND_USER)
>             self.dashboard = dashboard
> 
>         def invoke(self, arg, from_tty):
>             arg = Dashboard.parse_arg(arg)
>             if arg == 'rst':
>                 self.dashboard.source_scroll_reset(self.dashboard)
>             elif arg == 'up':
>                 self.dashboard.source_scroll_up(self.dashboard)
>                 #self.dashboard.redisplay()
>             elif arg == 'down':
>                 self.dashboard.source_scroll_down(self.dashboard)
>             else:
>                 msg = 'Wrong argument "{}"; expecting "up" or "down"'
>                 Dashboard.err(msg.format(arg))
> 
>         def complete(self, text, word):
>             return Dashboard.complete(word, ['up', 'down'])
> 
869a916
>         self.src_offset = 0
894a942
>             self.src_offset = 0
905,906c953,954
>         start = max(current_line - 1 - self.context + self.src_offset, 0)
>         end = min(current_line - 1 + self.context + 1 + self.src_offset, len(self.source_lines))
928a977,985
>     
>     def scrl_up(self):
>         self.src_offset = self.src_offset - 1
> 
>     def scrl_down(self):
>         self.src_offset = self.src_offset + 1
> 
>     def scrl_rst(self):
>         self.src_offset = 0

===========================
**.gdbinit.d/init**

`define scrollup`
`dashboard -srcscroll up`
`end`

`define scrolldown`
`dashboard -srcscroll down`
`end`

`define scrollreset`
`dashboard -srcscroll rst`
`end`

`define hookpost-next`
`scrollreset`
`end`

==================
**.inputrc**
`
$if gdb
    "\C-p": "scrollup\n"
    "\C-n": "scrolldown\n"
$endif
`

**Comment by cyrus-and** [comment]
Hey thanks! See #106 for a discussion about this feature.

Basically, the Source module (as well as the Assembly module) is there just to provide context, and implement scrolling in a REPL environment would be pretty cumbersome unless, as you suggest, `.inputrc` is used. Also, the problem of when and how resetting the offset...

I guess that you could just use `l` and `l -` instead of going back to TUI.

**Comment by uboats** [comment]
Thanks for tips
'l' and 'l -' will not have colored code and also move the dashboard out of view

regarding when and how to reset the offset
1. when 'next', 'up', 'down', 'frame', reset the offset
2. i think use define-hook to call reset function or capture those command in the run() func

at lease my current walkaround fix works, but i do want to see a more reliable/smart implementation officially ;)

**Comment by WorldSEnder** [comment]
A bit more intricate `.inputrc`:

```
$if gdb
    "\C-p": '\C-userver scrollup\015\C-y'
    "\C-n": '\C-userver scrolldown\015\C-y'
$endif
```
This
- issues commands with [`server`](https://sourceware.org/gdb/onlinedocs/gdb/Server-Prefix.html#Server-Prefix) so that they are not recorded in the history
- preserves the current line for the user

**Comment by uboats** [comment]
> A bit more intricate `.inputrc`:
> 
> ```
> $if gdb
>     "\C-p": '\C-userver scrollup\015\C-y'
>     "\C-n": '\C-userver scrolldown\015\C-y'
> $endif
> ```
> This
> 
> * issues commands with [`server`](https://sourceware.org/gdb/onlinedocs/gdb/Server-Prefix.html#Server-Prefix) so that they are not recorded in the history
> * preserves the current line for the user

Thanks so much!!!!

**Comment by phcerdan** [comment]
This is a great feature, any chance on allowing this `tui`-like navigation? Even if the user still needs to modify inputrc...

**Comment by cyrus-and** [comment]
Implemented in c671fddb455d85f23631742159084aae2bed991d. Use the `readline` *trick* like this:

```
$if gdb
    "\C-p": "\C-a\C-kserver dashboard source scroll 1\n\C-y"
    "\C-n": "\C-a\C-kserver dashboard source scroll -1\n\C-y"
    "\C-\M-p": "\C-a\C-kserver dashboard assembly scroll 1\n\C-y"
    "\C-\M-n": "\C-a\C-kserver dashboard assembly scroll -1\n\C-y"
$endif
```

**Comment by yankee14** [comment]
Hi! It is not clear to me from reading this thread; is it possible to scroll in the dashboard source window?

**Comment by cyrus-and** [comment]
@yankee14 yes, see `help dashboard source scroll`.
