### ISSUE TITLE
cuda-gdb support

### ISSUE THREAD

**Issue by isaacleeai** [cyrus-and/gdb-dashboard#132]
Hi,

I tried using this in cuda-gdb by renaming .gdbinit file to .cuda-gdbinit. 
The error is 
`Cannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 386, in render
  File "<string>", line 1492, in lines
error: Frame is invalid.`

is there a way to make this compatible with cuda-gdb as well?

**Comment by cyrus-and** [comment]
This is hard to impossible for me to work on this so I'm going to close it. If anyone is willing to help feel free to chime in.
