### ISSUE TITLE
Reverse order of frames, newest last to avoid scrolling.

### ISSUE THREAD

**Issue by phcerdan** [cyrus-and/gdb-dashboard#134]
In module Stack. Show first the oldest frames, and last the newest (that usually is the most relevant).

With frames with no much data, it doesn't matter, but when showing local content on frames, or the frames are big, force the user to scroll. So, instead of:
```
[0]: ...
[1]: ...
[2]: ...
```

Go for oldest first, so the user wouldn't need to scroll back for the usually more interesting frame (the newest).
```
[2]: ...
[1]: ...
[0]: ...
```

Gdb provides `gdb.newest_frame()`, but it doesn't seem to provide the symmetric `gdb.oldest_frame()`

Or maybe what I suggest is to print the selected_frame at the end, instead of at the start.

**Comment by cyrus-and** [comment]
I don't get it, why keeping track of the oldest (least relevant) while stepping?

If you need to peek at the oldest frame you can select it with `frame N` (use `info stack` to obtain `N`) and redisplay the dashboard. Any stepping from here will select the newest frame again.

**Comment by phcerdan** [comment]
I do have a custom function to show the local variables in the stack, and it is showing them for all the frames. So, my suggestion here was to show the most relevant (the newest) in the end, so I don't have to scroll up.

But if I understand you correctly, the current behavior of the module is to only show the current (newest) frame. So this doesn't apply. Thanks.
