### ISSUE TITLE
Neat lines not displayed properly

### ISSUE THREAD

**Issue by xrr** [cyrus-and/gdb-dashboard#139]
Instead of neat lines to delimit sections, my terminal shows the following:

> âââ Threads âââââââââââââââââââââââ

**Comment by cyrus-and** [comment]
Likely your terminal doesn't support UTF-8, you can either fix that or use ASCII dividers (see [this][1] comment of #138).

[1]: https://github.com/cyrus-and/gdb-dashboard/pull/138#issuecomment-462816304
