### ISSUE TITLE
dashbord command not found in ubuntu 16.04

### ISSUE THREAD

**Issue by sureshs2k12** [cyrus-and/gdb-dashboard#140]
Hello all,

           i have done following this $ wget -P ~ git.io/.gdbinit, after this i have open the new terminal & type the $ tty command then gave this command "dashboard -output /dev/ttys001" in terminal but i am getting error 

csk@CSK-Ubuntu:~$ dashboard -output /dev/ttys001
dashboard: command not found
csk@CSK-Ubuntu:~$ 

please help me for further move

**Comment by cyrus-and** [comment]
Hi, `dashboard` is not a system command, it's a GDB command, meaning that you have to run it inside a GDB session, what you want is:

1. in terminal A run the `tty` command and note the path, say `/dev/ttys001`;
2. in terminal B run:

        $ gdb /some/executable
        >>> dashboard -output /dev/ttys001
        >>> start

3. now the dashboard will be displayed in terminal A and the prompt will be in terminal B.

Good luck!

**Comment by sureshs2k12** [comment]
![screenshot from 2019-03-05 16-50-27](https://user-images.githubusercontent.com/31896055/53802117-fd46cb00-3f66-11e9-9801-327d2ec03629.png)
 Thanks for support ....

Please review above screen shot of my PC, which i got after following your flow

Thanks  in advance...

**Comment by cyrus-and** [comment]
Is the `.gdbinit` file in your home folder?

**Comment by sureshs2k12** [comment]
yes, now i can open dashboard(before **.gdbinit** file not in home folder, now its in home folder), but how can i visible all register view & expressions in terminal and have any change to look the live status of variable?

check below screenshot,which i try to display the register,threads,expressions... etc

![screenshot from 2019-03-08 15-29-59](https://user-images.githubusercontent.com/31896055/54022341-49d51500-41b8-11e9-9f07-ddcf134c0adf.png)


kindly request you to help me
thanks in advance

**Comment by sureshs2k12** [comment]
![screenshot from 2019-03-08 16-11-40](https://user-images.githubusercontent.com/31896055/54024161-f0231980-41bc-11e9-8601-2bffcd08d9a5.png)

help me to use the **expressions** and live watch of variable

**Comment by cyrus-and** [comment]
You can use the `help` command for about everything, in this case:

    help dashboard expressions

So for example:

    dashboard expressions watch foo()+5

**Comment by sureshs2k12** [comment]
Thanks lot for your response....

its working fine...

i need your help on below questions  
    * need to watch the Rx_buffer (local variable buffer) continuously without stop the debugging & without apply any break point (live watch of Rx_buffer)

please help me for it

**Comment by cyrus-and** [comment]
I'm sorry, that's simply not possible with GDB (and any other debugger AFAIK).

**Comment by sureshs2k12** [comment]
it's ok.... and thanks 

how can i use non-stop mode?
what is command to use non-stop mode?

**Comment by cyrus-and** [comment]
This has nothing to do with the dashboard, please refer to the GDB manual.
