### ISSUE TITLE
Source window does not update when moving up and down frames.

### ISSUE THREAD

**Issue by syamajala** [cyrus-and/gdb-dashboard#141]
Sometimes the Source window does not update when I move up and down frames. The only way to get it to show the source for the current frame is to clear the window with Ctrl+L and then redisplay the dashboard.

**Comment by cyrus-and** [comment]
Are you using hooks as described [here][1]?

Can you provide a step-by-step way to reproduce this? I mean sample program and all...

[1]: https://github.com/cyrus-and/gdb-dashboard#dashboard--enabled-onoff

**Comment by syamajala** [comment]
I was not using the hooks. Adding those seems to work. Thanks!
