### ISSUE TITLE
What exactly are the usage instructions?

### ISSUE THREAD

**Issue by mvrozanti** [cyrus-and/gdb-dashboard#144]
Every combination of the set of possible sequences of actions that fit the (very) ambiguous instructions leads to, at most, a single line displaying `--- RELEASED ---` inside (a second) `gdb` opened without a file argument.

May I ask, how do I use this tool?

**Comment by mvrozanti** [comment]
Ok, managed to get it running with the following steps:

- `gdb filename`
- execute run
- execute dashboard
- debug as usual

**Comment by cyrus-and** [comment]
> The GDB documentation is available at `help dashboard`.

Provided that you know how to use GDB, `help dashboard -output` should give you enough information about using a second terminal... but according to your [comment][1] I doubt that's what you want to achieve.

[1]: https://github.com/cyrus-and/gdb-dashboard/issues/144#issuecomment-490702399

**Comment by mvrozanti** [comment]
may I ask, why use a second terminal anyway? one for input and the other for output?

**Comment by cyrus-and** [comment]
Yes, you can have the prompt and program output to one and the dashboard in another:

    dashboard -output /dev/pts/2

Or have just some modules to a second or third (or more) terminal:

    dashboard source -output /dev/pts/2
    dashboard assembly -output /dev/pts/2
    dashboard stack -output /dev/pts/3
    dashboard memory -output /dev/pts/3

In any case this is optional and of course not the default so I'm puzzled about how you ended up with that `--- RELEASED ---` line.
