### ISSUE TITLE
.gdbinit:1653: Error in sourced command file:

### ISSUE THREAD

**Issue by jiachi27** [cyrus-and/gdb-dashboard#147]
My python and gdb version are listed below.
Python 2.7.5
GNU gdb (GDB) 8.0.1
When I launch GDB I got below errors.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 442, in start
  File "<string>", line 326, in load_modules
  File "<string>", line 555, in __init__
ValueError: zero length field name in format
.gdbinit:1653: Error in sourced command file:
Error while executing Python code.

How do I overcome this?

**Comment by cyrus-and** [comment]
Chances are that the version of Python compiled with your GDB is 2.6, you can check that with:

```console
$ gdb -ex 'python import sys; print(sys.version)' -ex quit
3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516]
```

As you can see it's different from the *system-wide* Python:

```console
$ python -c 'import sys; print(sys.version)'
2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516]
```

And the dashboard [requires][1] at least Python version 2.7; upgrade/compile your GDB.

[1]: https://github.com/cyrus-and/gdb-dashboard#requirements

**Comment by cire831** [comment]
looks like a Python3 vs Python2 issue.

I see Python 3.5 in the top line and Python 2.7 in the bottom.

**Comment by cyrus-and** [comment]
@cire831 Well, no... it's perfectly fine to have different Python versions in GDB and system.

**Comment by cire831** [comment]
k.  I think I misunderstood your previous point.   I see what you are showiing.  sorry about the noise.

**Comment by jiachi27** [comment]
Let me try recompiling gdb.

**Comment by jiachi27** [comment]
Issue has gone after moving to correct gdb
