### ISSUE TITLE
gdb-dashboard on WSL

### ISSUE THREAD

**Issue by evertvr** [cyrus-and/gdb-dashboard#148]
I've tried to run gdb-dashboard with gdb on WSL/windows 10 but it's telling me:

>>> dash
Is the target program running?

GDB version: GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git

gdb --tui gives me some kind of interface (but the text seems to be screwed up).

Anyone had any luck with running it on windows 10 with WSL?

**Comment by cyrus-and** [comment]
I'm not a Windows user but I tried in your specific conditions and it works as expected. For example:

```console
$ gdb /bin/ls -ex 'break __libc_start_main' -ex run
```

> Is the target program running?

Well does it?

**Comment by evertvr** [comment]
ok, so I would have thought to already get a dashboard without running the app at all. Should not have ignored the "is the target program running"

When I run it, it indeed displays the dashboard correctly.
