### ISSUE TITLE
Fragments in function names highlighted as registers

### ISSUE THREAD

**Issue by oblitum** [cyrus-and/gdb-dashboard#149]
Example where part of `sprintf` is highlighted for the `sp` register:

![screenshot](https://user-images.githubusercontent.com/1269815/59969007-34db8200-951a-11e9-9d7b-0a4136efdb6b.png)

**Comment by cyrus-and** [comment]
I guess Pygments is really the culprit this time. This snippet

```python
import pygments
import pygments.formatters
import pygments.lexers

lexer = pygments.lexers.NasmLexer()
formatter = pygments.formatters.TestcaseFormatter()
source = 'callq  0x5555555545f0 <sprintf@plt>'

print(pygments.highlight(source, lexer, formatter))
```

produces:

```
Token.Name.Function     u'callq'
Token.Text      u'  '
Token.Literal.Number.Hex        u'0x5555555545f0'
Token.Text      u' '
Token.Operator  u'<'
Token.Name.Builtin      u'sp'
Token.Name.Variable     u'rintf@plt'
Token.Operator  u'>'
Token.Text      u'\n'
```

I'll file an issue. Yet I'm not sure if the `<...>` format is valid Nasm syntax, more likely it's just a convention used by disassemblers that should be interpreted as comment IMHO.

FWIW the `GasLexer` parse the above correctly, at least without the `sp` thing.

What do you think?

**Comment by cyrus-and** [comment]
See [this Pygments issue][1].

[1]: https://bitbucket.org/birkenfeld/pygments-main/issues/1527/fix-nasmlexer-to-support-syntax-like

**Comment by oblitum** [comment]
OK, thanks for looking into it.

**Comment by oblitum** [comment]
> What do you think?

Yeah I think it's Pygments issue.
