### ISSUE TITLE
Memory  doesn't show.

### ISSUE THREAD

**Issue by Plasticoo** [cyrus-and/gdb-dashboard#15]
For some reason, Memory tab is a simple line with nothing in it. Any way to solve this problem?

I got latest .gdbinit from this repo, i got GDB version 7.10.

**Comment by cyrus-and** [comment]
It's not a problem. The `Memory` module allows to inspect the memory at user-provided addresses, that is, you have to specify the memory regions to be watched, like:

    dashboard memory watch 0x00400551 42

The above inspects `42` bytes starting from `0x00400551`.

See `help dashboard memory`.
