### ISSUE TITLE
curses error on msys2

### ISSUE THREAD

**Issue by jonsykkel** [cyrus-and/gdb-dashboard#151]
hello, nyce skrypt
im getting error when i try debug:

```
│Cannot write the dashboard
│Traceback (most recent call last):
│  File "<string>", line 401, in render
│  File "<string>", line 471, in get_term_width
│  File "C:/msys64/mingw64/lib/python3.7\curses\__init__.py", line 30, in initscr
│    fd=_sys.__stdout__.fileno())
│_curses.error: setupterm: could not find terminfo database
│
│During handling of the above exception, another exception occurred:
│
│Traceback (most recent call last):
│  File "<string>", line 403, in render
│  File "<string>", line 471, in get_term_width
│  File "C:/msys64/mingw64/lib/python3.7\curses\__init__.py", line 30, in initscr
│    fd=_sys.__stdout__.fileno())
│_curses.error: setupterm: could not find terminfo database
```

things:
msys2 mintty terminal
GNU gdb (GDB) 8.3
Python 3.7.3

any ideas?

**Comment by cyrus-and** [comment]
Hmm, show me the output of the `env` command. What if you try another terminal? I'm not familiar with your environment

**Comment by cyrus-and** [comment]
Alright, it's something about the `TERM` environment variable, either it is wrong or your system is not configured properly:

```console
$ TERM=wrong-value python -c 'import curses; curses.initscr().getmaxyx(); curses.endwin()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/curses/__init__.py", line 33, in initscr
    fd=_sys.__stdout__.fileno())
_curses.error: setupterm: could not find terminal
```

**Comment by jonsykkel** [comment]
i dont know if i can even use another terminal with this msys thing, i think only mintty available

if i run just this without setting the TERM variable i get no output or error: python -c 'import curses; curses.initscr().getmaxyx(); curses.endwin()'

here is the env output:

jon@jonpc:~$ env
USERDOMAIN=JONPC
OS=Windows_NT
LS_COLORS=no=00:fi=00:di=33:ow=00:ln=04:ex=00:st=00:tw=00:ow=00:pi=30;44:so=35;44:do=35;44:bd=33;44:cd=37;44:or=05;37;41:mi=05;37;41:
COMMONPROGRAMFILES=C:\Program Files\Common Files
PROCESSOR_LEVEL=6
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
CommonProgramW6432=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
MSYSCON=mintty.exe
FP_NO_HOST_CHECK=NO
LANG=C.UTF-8
TZ=Europe/Oslo
MSYSTEM_CARCH=x86_64
HOSTNAME=jonpc
PUBLIC=C:\Users\Public
OLDPWD=/home/jon/code/okelib2
CONFIG_SITE=/mingw64/etc/config.site
WD=C:\msys64\usr\bin\
CONTITLE=MinGW x64
MSYSTEM_CHOST=x86_64-w64-mingw32
LOGINSHELL=bash
USERNAME=jon
LOGONSERVER=\\JONPC
PROCESSOR_ARCHITECTURE=AMD64
tmp=C:\Users\jon\AppData\Local\Temp
LOCALAPPDATA=C:\Users\jon\AppData\Local
PREFIX=/mingw64
CC=cc
COMPUTERNAME=JONPC
USER=jon
!::=::\
SYSTEMDRIVE=C:
USERPROFILE=C:\Users\jon
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SYSTEMROOT=C:\Windows
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
MINGW_PACKAGE_PREFIX=mingw-w64-x86_64
PWD=/home/jon
HOME=/home/jon
TMP=/tmp
MSYSTEM_PREFIX=/mingw64
!C:=C:\msys64\usr\bin
PROCESSOR_REVISION=3c03
PROMPT=$P$G
NUMBER_OF_PROCESSORS=8
ProgramW6432=C:\Program Files
COMSPEC=C:\Windows\system32\cmd.exe
APPDATA=C:\Users\jon\AppData\Roaming
SHELL=/usr/bin/bash
TERM=xterm-256color
WINDIR=C:\Windows
MINGW_CHOST=x86_64-w64-mingw32
ProgramData=C:\ProgramData
SHLVL=1
PRINTER=Microsoft XPS Document Writer
ACLOCAL_PATH=/mingw64/share/aclocal:/usr/share/aclocal
PROGRAMFILES=C:\Program Files
MANPATH=/mingw64/local/man:/mingw64/share/man:/usr/local/man:/usr/share/man:/usr/man:/share/man
ORIGINAL_TEMP=/c/Users/jon/AppData/Local/Temp
ORIGINAL_TMP=/c/Users/jon/AppData/Local/Temp
ALLUSERSPROFILE=C:\ProgramData
TEMP=/tmp
temp=C:\Users\jon\AppData\Local\Temp
MSYSTEM=MINGW64
MINGW_PREFIX=/mingw64
SESSIONNAME=Console
ProgramFiles(x86)=C:\Program Files (x86)
PATH=/home/jon/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
PS1=\u@\h:\w\[\e[33m\]`parse_git_branch`$\[\e[m\]
HOMEDRIVE=C:
PKG_CONFIG_PATH=/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig
INFOPATH=/usr/local/info:/usr/share/info:/usr/info:/share/info
HOMEPATH=\Users\jon
ORIGINAL_PATH=/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/
_=/usr/bin/env

**Comment by cyrus-and** [comment]
Then try running the dashboard without setting the `TERM` variable.

**Comment by jonsykkel** [comment]
when i run the dashboard without setting the TERM i get the error.
its not exactly the same error as you got when you set TERM=wrong-value
"could not find terminfo database" vs "could not find terminal"

**Comment by cyrus-and** [comment]
> "could not find terminfo database" vs "could not find terminal"

Oh, right, I thought it was the same... I'm going to try this on Windows as soon as I can.

**Comment by jonsykkel** [comment]
i tested it now on my other computer with the same type of environment and it works there, so i guess there is something wrong with my system. thanks for the quick responses though

**Comment by cyrus-and** [comment]
Oh, good! You're welcome.

**Comment by jonsykkel** [comment]
in case someone ever has the same problem: it seems to work with the msys2 gdb build but not with mingw64 gdb build. ("gdb" vs "mingw-w64-x86_64-gdb" packages)
