### ISSUE TITLE
Adding a breakpoints list and backtrace list

### ISSUE THREAD

**Issue by gavinhoward** [cyrus-and/gdb-dashboard#152]
I have implemented two modules for `dashboard`:

1. Breakpoints, which is just a list of breakpoints and watchpoints (not a marker in source), along with marking which ones are enabled/disabled, temporary, and their locations.
2. Backtrace, which is a full backtrace (for the current thread) that labels the currently selected frame.

Would there be interest in having me clean them up and submit them for possible merge?

**Comment by cyrus-and** [comment]
> * Breakpoints, which is just a list of breakpoints and watchpoints (not a marker in source), along with marking which ones are enabled/disabled, temporary, and their locations.

Are you using the GDB Python API to obtain that list or are you parsing the output of `info breakpoints` or similar?

> * Backtrace, which is a full backtrace (for the current thread) that labels the currently selected frame.

Can you please highlight the differences with the builtin Stack module?

**Comment by gavinhoward** [comment]
> Are you using the GDB Python API to obtain that list or are you parsing the output of `info breakpoints` or similar?

I am using the Python API to obtain the list. However, dealing with breakpoints, especially watchpoints, is still awkward with the Python API, even though I do not try to label the line in source. (I use `dashboard` with the `termdebug` plugin of `vim`/`neovim`, which shows me the source and a marker for the breakpoint.) Thus, the code is still...a bit ugly.
 
> Can you please highlight the differences with the builtin Stack module?

1. It doesn't show arguments or locals.
2. It shows the entire stack frame, no matter what frame is selected. (Stack currently only shows the current frame, along with older frames if `limit` is set high enough.)
3. It highlights the currently selected frame.

Backtrace was useful to me because I set `dashboard stack -style limit 1` to only show arguments and locals for the current frame. Backtrace allows me to see which stack frame I have selected.

**Comment by cyrus-and** [comment]
I would hold back the *new* Stack module as I think that those are minor changes with respect to the one built-in, moreover there's some overlapping with #107 that I still need to address.

The breakpoint module could be interesting, would it be possible for you to push it somewhere before (even if still ugly :) like a Gist or a repo on your own before making the PR so I can give it a quick try?

Thanks!

**Comment by gavinhoward** [comment]
Breakpoints gist: https://gist.github.com/gavinhoward/31a220a3e7731c3518136955ac6e8b0d

For the Stack module, I would be happy if Variables became their own module (as you suggested in #107) and have Stack extended to be able to

1. Have the full backtrace no matter what frame is selected, and
2. Highlight the current frame.

I like being able to see, at a glance, which frame I have selected without trying to see past locals and arguments.

However, I will be happy no matter how you do it because I have already made this module for myself; thanks for making `dashboard` extensible!

**Comment by cyrus-and** [comment]
> Breakpoints gist

Thanks, I'm a bit busy right now but I'll give it a look in the near future hopefully.

> thanks for making dashboard extensible!

That was one of my primal goals. :) And actually, I've been thinking to keep a list of user-contributed modules somewhere, like in the wiki, but there wouldn't be a lot of entries I'm afraid.

**Comment by cyrus-and** [comment]
I ended up implementing the breakpoint module from scratch so I could reuse the `fetch_breakpoints` function already used to display the breakpoints in the source and assembly modules. I also changed several other things to match the style of the dashboard.

Thanks for motivating me!

**Comment by gavinhoward** [comment]
You are welcome!

I will be sending a PR soon with a few changes to `fetch_breakpoints()` and the breakpoints module. They are ideas to make them more general (and to help me implement something I would like :P).
