### ISSUE TITLE
Display threads of all inferiors in the dashboard

### ISSUE THREAD

**Issue by lbmeng** [cyrus-and/gdb-dashboard#155]
Currently only threads of the current active inferior are displayed in the dashboard.

Is it possible to display all threads of all inferiors in the dashboard?

Currently I have to manually type "info threads" in the gdb command line to get all threads displayed.

**Comment by cyrus-and** [comment]
Now it is:

    dashboard threads -style all-inferiors True

Thanks for the suggestion.

**Comment by lbmeng** [comment]
Great, thanks for your quick response!
