### ISSUE TITLE
GDB TUI interface is not supported

### ISSUE THREAD

**Issue by ismailhkose** [cyrus-and/gdb-dashboard#157]
I tried gdb-dashboard in Ubuntu 18.04 and having the following issues.

1- It cant find dashboard command, and there is no explanation how it is installed in README.md.

> dashboard: command not found 

2 - After downloading .gdbinit and installed Pygments, gdb -tui view becomes as follows.

> GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git                                      
> Copyright (C) 2018 Free Software Foundation, Inc.                                     
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>         
> This is free software: you are free to change and redistribute it.                    
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"            
> and "show warranty" for details.                                                      
> This GDB was configured as "x86_64-linux-gnu".                                        
> Type "show configuration" for configuration details.                                  
> For bug reporting instructions, please see:                                           
> <http://www.gnu.org/software/gdb/bugs/>.                                              
> Find the GDB manual and other documentation resources online at:                      
> <http://www.gnu.org/software/gdb/documentation/>.                                     
> For help, type "help".                                                                
> Type "apropos word" to search for commands related to "word".                         
> ^A^[[1;30m^B>>>^A^[[0m^B                                                              

How can I resolve these errors? Could you provide more straightforward setup instructions?
 
Thanks in advance

**Comment by cyrus-and** [comment]
You don't need `-tui`.

**Comment by cyrus-and** [comment]
For example:

    dashboard source -style height 20

Please use the GDB `help` command to see what are the available commands and configurations:

    help dashboard
    help dashboard source
    help dashboard source -style

**Comment by cyrus-and** [comment]
BTW I don't know why you assumed that you needed to use TUI, in fact it is [explicitly][1] stated that TUI is not supported.

[1]: https://github.com/cyrus-and/gdb-dashboard#additional-gdb-front-ends
