### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by DeadlyHollows** [cyrus-and/gdb-dashboard#159]
Hi,
    Really great work guys! I really appreciate the project and the efforts you guys have put into it. We would like to use the project for a commercial training online/classroom. So, I just wanted to clarify, if we acknowledge the source, would that be sufficient and covered under the terms of use?

**Comment by cyrus-and** [comment]
Hey, thanks, I'm so glad to hear that!

Sure, the MIT license I'm using [basically][1] says you can do whatever you want as long as you retain the copyright notice. Now I don't know if you plan to modify it or just use it in your course, in any case retaining the copyright notice is the only mandatory point, while acknowledging the source and linking back to this repo would be a nice addition. :)

Good luck!

[1]: https://tldrlegal.com/license/mit-license

**Comment by DeadlyHollows** [comment]
Thanks for a quick reply. Really appreciate that. Yes, we would be acknowledging the source and providing the link as well. Great work guys!

Thanks.
