### ISSUE TITLE
'gdb.Breakpoint' object has no attribute 'pending'

### ISSUE THREAD

**Issue by limslarmo** [cyrus-and/gdb-dashboard#161]
Just tried to use gdb dashboard but got the following error under Expression panel. 

─── Expressions ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "<string>", line 475, in render
  File "<string>", line 1832, in lines
RuntimeError: Programmer error: unhandled type.

My system is ubuntu 18.04, gdb version = 8.1.0, 
gdb is compiled with python 3.6

Any troubleshooting guidance will be appreciated!

**Comment by cyrus-and** [comment]
OK I can reproduce this, but where does `'gdb.Breakpoint' object has no attribute 'pending'` come from?

**Comment by cyrus-and** [comment]
Sadly, this looks like a GDB bug:

```console
$ gdb --version
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
$ gdb -q --batch -nh -ex 'python gdb.parameter("output-radix")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: Programmer error: unhandled type.
Error while executing Python code.
```

**Comment by cyrus-and** [comment]
I'll look into this and provide a fix, in the meantime you can just replace this line:

https://github.com/cyrus-and/gdb-dashboard/blob/d9c7584f204bbb47a4999b5799ed63523d3ab385/.gdbinit#L1833

with:

```python
default_radix = 10
```

**Comment by limslarmo** [comment]
Appreciate it. Thanks!!!
