### ISSUE TITLE
hello, i want to splice to import messages like stack, source, Variables into different windows, like beatiful ide debug. Is there some ways to do that? please help

### ISSUE THREAD

**Issue by chenqs1992** [cyrus-and/gdb-dashboard#162]
once i debug mongo with dash, mongo db have many threads, my window is not big for to show some import messages for me, i can't see source and virables, please help me show some way to use dashboard more effectively. thanks

**Comment by cyrus-and** [comment]
Does [this wiki entry][1] help?

[1]: https://github.com/cyrus-and/gdb-dashboard/wiki/Use-multiple-terminals
