### ISSUE TITLE
What is the project's License?

### ISSUE THREAD

**Issue by kammce** [cyrus-and/gdb-dashboard#164]
I would like to include this file as apart of my project when users startup gdb as a part of my build system. I have seen other projects take your work and include it in their projects. But before doing this I would like to ask for your permission or request that you add a license so that this question is no longer necessary.

I would be happy to mention you in my project's README section.

**Comment by cyrus-and** [comment]
Hi, I'm glad to hear that, and thank you for taking the time to ask!

The license is MIT and it's [included][1] in the source file. I didn't place the canonical `LICENSE` file in the repo to avoid duplication, sorry for the confusion, maybe I should add it back there...

[1]: https://github.com/cyrus-and/gdb-dashboard/blob/462b7d658db08655bc8e80a5b6435e4a93554a51/.gdbinit#L2112-L2130

**Comment by kammce** [comment]
Thanks for the super fast reply. Great! I make a mention and add that in to my project. 

Also, fantastic work on this project. I have been recommending this to everyone at my company and to all of my students. I CANNOT stand using plain-ol' GDB on the command line. But with your tool, I prefer it to using an IDE's integrated debugger.

Cheers!

**Comment by kammce** [comment]
Oh and the project I am using this for is this if you were curious:

https://github.com/kammce/SJSU-Dev2/

**Comment by cyrus-and** [comment]
Great!

> Oh and the project I am using this for is this if you were curious:

Thanks, yes I was about to ask. :)
