### ISSUE TITLE
Last command in GDB no longer functions after installing dashboard

### ISSUE THREAD

**Issue by Hnefi** [cyrus-and/gdb-dashboard#165]
After installing the dashboard, GDB no longer caches/repeats the last command when pressing Return with a blank line. This makes repeated stepping quite annoying - could this potentially be added as a feature?

**Comment by cyrus-and** [comment]
It's likely a duplicate of #128: a GDB bug in version 8.2 and fixed in 8.2.1, can you relate?

**Comment by Hnefi** [comment]
@cyrus-and Just tested with gdb 8.3 compiled from source on Ubuntu 18.10, and this works fine. Closing the issue, thank you so much for the pointer.
