### ISSUE TITLE
Minor: exclamation mark for breakpoint

### ISSUE THREAD

**Issue by milanl81** [cyrus-and/gdb-dashboard#171]
I have two files with the same filename, in different folders (the last 4 directory names also the same). I put a breakpoint in one of them. In the other file i can see in the "Source" section the red exclamation mark at the specified line (for the other file though). I only had 1 breakpoint.
So it is very minor.. just posting this to uncover possible more serious issues.

**Comment by cyrus-and** [comment]
It should work now, please give it a try. Thanks for reporting!

**Comment by milanl81** [comment]
Works fine! Thanks
