### ISSUE TITLE
Problem with the Source module

### ISSUE THREAD

**Issue by vlorcy** [cyrus-and/gdb-dashboard#173]
During a debugging session, the following error was reported by the Source module:
```python
Traceback (most recent call last):
  File "<string>", line 486, in render
  File "<string>", line 1138, in lines
  File "<string>", line 300, in fetch_breakpoints
ValueError: invalid literal for int() with base 10: '1.1'
```
I had ran a command to set a breakpoint on a line in a templated function, which resulted in 2 breakpoints being created, numbered 1.1 and 1.2. I guess the breakpoint number shall be casted to `float` instead of `int`.

**Comment by cyrus-and** [comment]
This should already be fixed. Are you sure you're using the latest version?

**Comment by vlorcy** [comment]
Well, no I wasn't, it works perfectly fine with the latest version. Sorry about that !

**Comment by cyrus-and** [comment]
No worries, enjoy! :)
