### ISSUE TITLE
Error when using watchpoints

### ISSUE THREAD

**Issue by arakis** [cyrus-and/gdb-dashboard#175]
When using watchpoints, the dashboard shows errors. After deleting them, it works again.
Used version: 11.2. System: Debian 10 WSL (Windows Subsystem for Linux). When not using watchpoints, all works fine.

I checked all previous version: This issue was first seen in v11.1 ("Add support for breakpoints with multiple locations"). But i depend on version v11.2, because a bug with absolute file paths/symbolic links was solved. ("Improve the source files lookup", 1387711)

This issue exists in master ( 776180b ), too.

Before watchpoint:

![image](https://user-images.githubusercontent.com/1831942/69493350-2bca5480-0eae-11ea-80de-25ad30f2fd7e.png)

After adding watchpoint:
![image](https://user-images.githubusercontent.com/1831942/69493356-43094200-0eae-11ea-9e59-ba5567216720.png)

**Comment by cyrus-and** [comment]
Thanks for reporting, it should work now.

**Comment by arakis** [comment]
I can confirm that the issue is gone now. Thx for fixing!
