### ISSUE TITLE
Customize Dashboard persistently 

### ISSUE THREAD

**Issue by FabianSchuetze** [cyrus-and/gdb-dashboard#179]
Thank you for writing such a wonderful program, Andrea. 

I would like to customize the dashboard layout persistently. For example, suppose I want to have the following layout upon startup

``dashboard -layout assembly expressions registers !source``

Which config file would I have to edit and how would I specify this design? (I could not find such guidelines in the FAQ, I might have missed them though.)

**Comment by cyrus-and** [comment]
Thanks Fabian!

It's written in these pages: [1][1] and [2][2]. Basically any file in `~/.gdbinit.d/` will do, I use `init` as convention. Hope it helps.

[1]: https://github.com/cyrus-and/gdb-dashboard/wiki/Customize-the-dashboard
[2]: https://github.com/cyrus-and/gdb-dashboard/wiki/Use-personal-configuration-files

**Comment by FabianSchuetze** [comment]
Great - many thanks!

**Comment by cyrus-and** [comment]
FYI the wiki now has a proper sidebar, admittedly it *was* confusing. Thanks for the inspiration. :)

**Comment by FabianSchuetze** [comment]
The FAQ indeed looks much more organized now, thanks!
