### ISSUE TITLE
Stack module does not show function info that bt shows

### ISSUE THREAD

**Issue by mkurdej** [cyrus-and/gdb-dashboard#182]
As shown on the screenshot:
![image](https://user-images.githubusercontent.com/1609564/72885891-1ab08f00-3d09-11ea-977a-0eb79dde7267.png)

**Comment by cyrus-and** [comment]
Are you able to provide a minimum example so I can try to reproduce this?

**Comment by mkurdej** [comment]
I'll try to, but it occurred with a pretty big application, so it can take some time.

**Comment by cyrus-and** [comment]
I understand, thank you. Unfortunately it's near to impossible for me to dig into that without more information.

**Comment by Rubonnek** [comment]
Just found this myself -- this can easily be replicated by using the [Godot Game Engine](https://godotengine.org/download/linux).

@cyrus-and here are the steps using the stable 3.2 release:
```shell
git clone https://github.com/godotengine/godot-demo-projects
cd godot-demo-projects/2d/platformer
godot -e # let the engine reimport the assets then close the engine
gdb godot # then just run the engine
```
I find that tihis issue can be reproduced easily by just randomly stopping the engine by pressing Ctrl-C in the `gdb` terminal and looking at the backtrace and comparing it with the stack frames found on the dashboard

**Comment by cyrus-and** [comment]
@Rubonnek alright I got it, thanks! This is the never ending story, I wish the GDB Python API were more reliable or better documented... it should be fixed now, please give it a go.

**Comment by Rubonnek** [comment]
@cyrus-and works great! Thanks!
