### ISSUE TITLE
output messed up

### ISSUE THREAD

**Issue by nonpolarity** [cyrus-and/gdb-dashboard#183]
(gdb) source ~/.gdb-dashboard
^A^[[1;30m^B>>>^A^[[0m^B b main
Breakpoint 1 at 0x4087cf: file /home/alvin/openenclave/tests/syscall/fs/host/host.c, line 19.
^A^[[1;30m^B>>>^A^[[0m^B run
Starting program: /home/alvin/openenclave/build/tests/syscall/fs/host/fs_host /home/alvin/openenclave/build/tests/syscall/fs/enc/fs_enc /ho
me/alvin/openenclave /home/alvin/openenclave/build/tests/syscall/fs/tmp
^[[H^[[J^[[3J^[[36m───^[[0m ^[[1;33mOutput/messages^[[0m ^[[36m────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────^[[0m
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
^[[36m───^[[0m ^[[1;33mAssembly^[[0m ^[[36m────────────────────────────────────────────────────────────────────────────────────────────────
──────────────────────────────^[[0m
 ^[[1;30m0x00000000004087b4^[[0m  ^[[1;30mmain+20^[[0m mov    %edi,%ebp
 ^[[1;30m0x00000000004087b6^[[0m  ^[[1;30mmain+22^[[0m mov    $0xffffffffffffffff,%r14
 ^[[1;30m0x00000000004087bd^[[0m  ^[[1;30mmain+29^[[0m sar    $0x3f,%rax
 ^[[1;30m0x00000000004087c1^[[0m  ^[[1;30mmain+33^[[0m mov    %fs:0x28,%rcx
 ^[[1;30m0x00000000004087ca^[[0m  ^[[1;30mmain+42^[[0m mov    %rcx,0x10(%rsp)
^[[0;41m!^[[0m^[[1;32m0x00000000004087cf^[[0m^[[1;32m  ^[[0m^[[1;32m^[[0m^[[1;32mmain+47^[[0m^[[1;32m movq   $0x0,0x8(%rsp)^[[0m
 ^[[1;30m0x00000000004087d8^[[0m  ^[[1;30mmain+56^[[0m shl    $0x2f,%rax
 ^[[1;30m0x00000000004087dc^[[0m  ^[[1;30mmain+60^[[0m or     %rax,%rsp
 ^[[1;30m0x00000000004087df^[[0m  ^[[1;30mmain+63^[[0m callq  0x408e20 <oe_get_create_flags>
 ^[[1;30m0x00000000004087e4^[[0m  ^[[1;30mmain+68^[[0m mov    %rsp,%rbx
^[[36m───^[[0m ^[[1;33mBreakpoints^[[0m ^[[36m─────────────────────────────────────────────────────────────────────────────────────────────
──────────────────────────────^[[0m
[^[[1;32m1^[[0m] ^[[1;32mbreak^[[0m at ^[[1;32m0x00000000004087cf^[[0m in ^[[1;32m/home/alvin/openenclave/tests/syscall/fs/host/host.c^[[0m
:^[[1;32m19^[[0m for ^[[1;32mmain^[[0m hit ^[[1;32m1^[[0m time
^[[36m───^[[0m ^[[33mExpressions^[[0m ^[[36m───────────────────────────────────────────────────────────────────────────────────────────────
────────────────────────────^[[0m
^[[36m───^[[0m ^[[33mHistory^[[0m ^[[36m───────────────────────────────────────────────────────────────────────────────────────────────────
────────────────────────────^[[0m
^[[36m───^[[0m ^[[33mMemory^[[0m ^[[36m────────────────────────────────────────────────────────────────────────────────────────────────────
────────────────────────────^[[0m
^[[36m───^[[0m ^[[1;33mRegisters^[[0m ^[[36m───────────────────────────────────────────────────────────────────────────────────────────────
──────────────────────────────^[[0m
    ^[[1;30mrax^[[0m ^[[1;32m0x0000000000000000^[[0m     ^[[1;30mrbx^[[0m ^[[1;32m0x0000000000000000^[[0m        ^[[1;30mrcx^[[0m ^[[1;32m0
xbb3d0d9875cc4300^[[0m    ^[[1;30mrdx^[[0m ^[[1;32m0x00007fffffffe3d0^[[0m    ^[[1;30mrsi^[[0m ^[[1;32m0x00007fffffffe3a8^[[0m
    ^[[1;30mrdi^[[0m ^[[1;32m0x0000000000000004^[[0m     ^[[1;30mrbp^[[0m ^[[1;32m0x0000000000000004^[[0m        ^[[1;30mrsp^[[0m ^[[1;32m0
x00007fffffffe280^[[0m     ^[[1;30mr8^[[0m ^[[1;32m0x00007ffff7158d80^[[0m     ^[[1;30mr9^[[0m ^[[1;32m0x0000000000000000^[[0m
    ^[[1;30mr10^[[0m ^[[1;32m0x000000004f8bfbff^[[0m     ^[[1;30mr11^[[0m ^[[1;32m0x0000000000000015^[[0m        ^[[1;30mr12^[[0m ^[[1;32m0
x00000000004086b0^[[0m    ^[[1;30mr13^[[0m ^[[1;32m0x00007fffffffe3a8^[[0m    ^[[1;30mr14^[[0m ^[[1;32m0xffffffffffffffff^[[0m
    ^[[1;30mr15^[[0m ^[[1;32m0x0000000000000000^[[0m     ^[[1;30mrip^[[0m ^[[1;32m0x00000000004087cf^[[0m     ^[[1;30meflags^[[0m ^[[1;32m[
 PF ZF IF ]^[[0m           ^[[1;30mcs^[[0m ^[[1;32m0x00000033^[[0m             ^[[1;30mss^[[0m ^[[1;32m0x0000002b^[[0m
     ^[[1;30mds^[[0m ^[[1;32m0x00000000^[[0m              ^[[1;30mes^[[0m ^[[1;32m0x00000000^[[0m                 ^[[1;30mfs^[[0m ^[[1;32m0
x00000000^[[0m             ^[[1;30mgs^[[0m ^[[1;32m0x00000000^[[0m
^[[36m───^[[0m ^[[1;33mSource^[[0m ^[[36m──────────────────────────────────────────────────────────────────────────────────────────────────
──────────────────────────────^[[0m
 ^[[1;30m14^[[0m  int rmdir(const char* path);
 ^[[1;30m15^[[0m
 ^[[1;30m16^[[0m  int main(int argc, const char* argv[])
 ^[[1;30m17^[[0m  {
 ^[[1;30m18^[[0m      oe_result_t r;
^[[0;41m!^[[0m^[[1;32m19      oe_enclave_t* enclave = NULL;^[[0m
 ^[[1;30m20^[[0m      const uint32_t flags = oe_get_create_flags();
 ^[[1;30m21^[[0m      const oe_enclave_type_t type = OE_ENCLAVE_TYPE_SGX;
 ^[[1;30m22^[[0m
 ^[[1;30m23^[[0m      if (argc != 4)
^[[36m───^[[0m ^[[1;33mStack^[[0m ^[[36m───────────────────────────────────────────────────────────────────────────────────────────────────
──────────────────────────────^[[0m
[^[[1;32m0^[[0m] from ^[[1;32m0x00000000004087cf^[[0m in ^[[1;32mmain^[[0m+^[[1;32m47^[[0m at ^[[1;32m/home/alvin/openenclave/tests/syscall
/fs/host/host.c^[[0m:^[[1;32m19^[[0m
^[[36m───^[[0m ^[[1;33mThreads^[[0m ^[[36m─────────────────────────────────────────────────────────────────────────────────────────────────
──────────────────────────────^[[0m
[^[[1;32m1^[[0m] id ^[[1;32m18752^[[0m name ^[[1;32mfs_host^[[0m from ^[[1;32m0x00000000004087cf^[[0m in ^[[1;32mmain^[[0m+^[[1;32m47^[[0m
at ^[[1;32m/home/alvin/openenclave/tests/syscall/fs/host/host.c^[[0m:^[[1;32m19^[[0m
^[[36m───^[[0m ^[[1;33mVariables^[[0m ^[[36m───────────────────────────────────────────────────────────────────────────────────────────────
──────────────────────────────^[[0m
^[[1;30marg^[[0m ^[[1;37margc^[[0m ^[[1;30m=^[[0m 0x4^[[1;30m, ^[[0m^[[1;37margv^[[0m ^[[1;30m=^[[0m 0x7fffffffe3a8^[[1;30m:^[[0m 0x2f
^[[1;30mloc^[[0m ^[[1;37mtype^[[0m ^[[1;30m=^[[0m <optimized out>^[[1;30m, ^[[0m^[[1;37mflags^[[0m ^[[1;30m=^[[0m <optimized out>^[[1;30m,
^[[0m^[[1;37menclave_path^[[0m ^[[1;30m=^[[0m <optimized out>^[[1;30m, ^[[0m^[[1;37msrc_dir^[[0m ^[[1;30m=^[[0m <optimized out>^[[1;30m, ^[
[0m^[[1;37mtmp_dir^[[0m ^[[1;30m=^[[0m <optimized out>^[[1;30m, ^[[0m^[[1;37menclave^[[0m ^[[1;30m=^[[0m <optimized out>^[[1;30m, ^[[0m^[[1
;37mr^[[0m ^[[1;30m=^[[0m <optimized out>
^[[36m─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
──────^[[0m

Breakpoint 1, main (argc=0x4, argv=0x7fffffffe3a8) at /home/alvin/openenclave/tests/syscall/fs/host/host.c:19
^A^[[1;35m^B>>>^A^[[0m^B

Thanks!

**Comment by cyrus-and** [comment]
I need some context here, OS, terminal, etc. It looks like your terminal does not support ANSI codes, in that case:

    dashboard -style ansi False

And you might also want to change the prompt.

**Comment by nonpolarity** [comment]
Thanks for your instant response, yes after dashboard -style ansi False now the ascii out is OK.

Your project is the biggest improvement since tui support for gdb, thanks again!

**Comment by cyrus-and** [comment]
I'm so glad to hear that, thank you! :)

But it's quite unusual that you're running a terminal nowadays that's not able to display ASCII, chances are that there's a misconfiguration somewhere, feel free to post here details about your environment.

**Comment by nonpolarity** [comment]
@cyrus-and Now I know this problem results from the gdb tui mode. It seems no way to support ansiconsole and tui mode at the same. Anyway I record it here as a reference.
