### ISSUE TITLE
Cannot scroll assembly outside of recognized functions

### ISSUE THREAD

**Issue by MrMino** [cyrus-and/gdb-dashboard#188]
Scrolling seems to not work when there is no source code available.

Repro steps:

0. Have dashboard in ~/.gdbinit
1. Download Binary Bomb challange executable from [“Lab Assignments” page of Bryant and O’Hallaron’s website](https://csapp.cs.cmu.edu/public/labs.html) ("Self-study Handout" link). Unpack the archive.
2. `gdb bomb`
3. `b main`
4. `run`
5. `si` 7 times (until the `callq` to `initialize_bomb()`)
6. `dashboard assembly scroll +1` doesn't seem to do anything.

**Comment by cyrus-and** [comment]
Yes that happens when the bounds of the current function are not available. In that case I simply take *height* instructions from the PC. Since it's impossible to figure out the prior instruction I simply (and silently) disabled the scrolling.

**Comment by cyrus-and** [comment]
OK, now you can at least scroll down, thanks for reporting.

**Comment by MrMino** [comment]
That was fast :). Thanks! Great project BTW, this is brilliant.
