### ISSUE TITLE
gdb catch throw causes segmentation fault

### ISSUE THREAD

**Issue by jambuu** [cyrus-and/gdb-dashboard#189]
Hi,

When using `dashboard` with `catch throw`, `gdb` crashes with segmentation fault.

# How to reproduce

1. Example code:

  ```cpp
  #include <stdexcept>

  int main() { throw std::runtime_error("error"); }
  ```
2. compiling with debug symbols:

    `g++ -g test.cpp -o test`

3. enabling catch throw in gdb
  ```
Reading symbols from test...done.
>>> catch throw
Catchpoint 1 (throw)
>>> r
  ```
4. error
```
─── Output/messages ──────────────────────────────────────────────────────────────
Segmentation fault (core dumped)
```
If we disable dashboard, everything works fine.

**Comment by cyrus-and** [comment]
Thanks for reporting, even though it does not happen without the dashboard it shouldn't be possible to crash GDB from its Python API IMHO, so this is probably a GDB bug. I'll dig into it...

**Comment by cyrus-and** [comment]
Alright this is has nothing to do with the dashboard, GDB crashes in the above scenario when the `thatBreakpoint.location` attribute is fetched. Reproduce with:

```console
$ gdb test -nx -ex 'catch throw' -ex 'python gdb.breakpoints()[0].location'
Reading symbols from test...done.
Catchpoint 1 (throw)
Segmentation fault
```

You should file an issue to the GDB bug tracker.

**Comment by cyrus-and** [comment]
Closing as this does not concern the dashboard.

Feel free to use this discussion to report an upstream issue (and possibly post here the link).
