### ISSUE TITLE
Dashboard crashes external debuggers

### ISSUE THREAD

**Issue by procedural** [cyrus-and/gdb-dashboard#19]
Tested on Ubuntu Mint 14.04.

With `.gdbinit` copied to home directory, dashboard works as it should from terminal windows, but it breaks external GDB frontends like Nemiver or Qt Creator, they pop-up an unexpected crash error window without any helpful debug info.

If `.gdbinit` is removed from home directory, they work fine again.

**Comment by cyrus-and** [comment]
This `.gdbinit` is not meant to work with external frontends (and looks like it's not easy to make everybody happy). You can try to manually source this `.gdbinit` in the meanwhile.

Something like:

    mv .gdbinit .gdb-dashboard

Then from vanilla GDB:

    source ~/.gdb-dashboard

I'll try to find a better solution...

**Comment by procedural** [comment]
@cyrus-and thanks! I think adding this info to readme.md will be enough to close this issue so other people could be aware of this issue. Yeah, I don't think it'll be possible to fix this for external frontends, too...

**Comment by cyrus-and** [comment]
If only there was a way to know the currently used [interpreter](https://sourceware.org/gdb/onlinedocs/gdb/Interpreters.html) from within GDB, I could skip all the initialization if the interpreter is not `console`. But I can't find anything related...

Even a way to get the arguments passed to GDB would help. E.g., Nemiver execute the debugger with `--interpreter=mi2`.

**Comment by cyrus-and** [comment]
I even tried to ping the devs on #gdb, no luck... Added a [section in the README](/cyrus-and/gdb-dashboard#additional-gdb-front-ends).
Thanks!

**Comment by procedural** [comment]
@cyrus-and perfect, thank you!
