### ISSUE TITLE
Limit Stack display to a number of lines

### ISSUE THREAD

**Issue by rcaputo** [cyrus-and/gdb-dashboard#197]
A way to end the Stack display before frame 0 scrolls off would be very useful.  Frame 0 is the most important information in the Stack display, and it's the first to go when scrolling begins.

I tried using `frames.reverse()` but it's a hack.  Arguments and variables display backwards and above the frame's address.

It was suggested to use `style -limit N` to reduce the number of stack frames, but even a small number of frames can overflow a terminal when `arguments` or `locals` is enabled.  Trivially so if `compact` is disabled.

I believe something like this would also be an acceptable resolution to issue #134

**Comment by cyrus-and** [comment]
Why not just hide arguments and locals in the stack module (default) and use the Variable module instead to display that information (default)?

**Comment by rcaputo** [comment]
I don't usually view locals on the stack, but arguments have been useful for mentally walking the stack back to a function that originated a bad value.

I'll try using Variables to view them, and `up` and `dash` to manually walk the stack and view one frame's arguments at a time, out of context, but I expect this experience to be worse.

**Comment by cyrus-and** [comment]
There's not a real solution to this and it seems that in your use cases there's barely the space for frame 0.

If you really need to have a detailed representation of multiple frames of the stack (with arguments/locals) your best bet is to dedicate a separate full-height terminal tmux/pane to that.

**Comment by rcaputo** [comment]
I see. Very well.
