### ISSUE TITLE
'gdb.Breakpoint' object has no attribute 'temporary'

### ISSUE THREAD

**Issue by ckouder** [cyrus-and/gdb-dashboard#198]
```bash
Traceback (most recent call last):
  File "<string>", line 532, in render
  File "<string>", line 2170, in lines
  File "<string>", line 367, in fetch_breakpoints
AttributeError: 'gdb.Breakpoint' object has no attribute 'temporary'
```

I ran gdb and this message occurs. Any help?

**Comment by cyrus-and** [comment]
What version of GDB are you using?

**Comment by ckouder** [comment]
GDB 7.3.1. I solved the problem by updating it to 9.1. Thank you.

**Comment by ItsAMeMarcel** [comment]
Is there a workaround for older versions? I have the same issue with gdb version 7.6.1.  Sadly there is no easy way for me to update gdb on a newer version.

**Comment by cyrus-and** [comment]
@ItsAMeMarcel does [this](https://github.com/cyrus-and/gdb-dashboard/wiki/Support-older-GDB-versions) help?

**Comment by ItsAMeMarcel** [comment]
Thank you for the quick answer. I had already implemented this workaround but it didn't fix the problem.

**Comment by cyrus-and** [comment]
@ItsAMeMarcel FYI you don't need to be root to compile your own latest/more recent version of GDB, I can assist you with that if you need.

**Comment by ItsAMeMarcel** [comment]
You mean a local installation like you get if you use --prefix=$HOME/gdb when running ./configure? Yes maybe this is the easiest way to get this done. I'm only afraid that this fail because of the dependencies.

**Comment by cyrus-and** [comment]
@ItsAMeMarcel Yeah plus some option about Python. You can always use a slight newer version just to hit the minimum requirements and reduce the chance of unsatisfiable dependencies:

> GDB dashboard requires at least GDB 7.7 compiled with Python 2.7 in order to work properly.
