### ISSUE TITLE
"Is the target program running" error

### ISSUE THREAD

**Issue by vtronko** [cyrus-and/gdb-dashboard#199]
Installed as per README via simple wget to .gdbinit.

`Is the target program running?` message appears when I try to run gdb, either on itself or attached — doesn't matter. It prints that message and gdb quits right after that.

Any hints?

**Comment by cyrus-and** [comment]
Well I need more information... Show me *exactly* the commands that you run and the versions of GDB, Python (inside GDB), OS, etc.

**Comment by vtronko** [comment]
Linux 5.6.2-arch1-2 x86_64 GNU/Linux
NVIM v0.4.3
GNU gdb (GDB) 9.1

It worked on other device though.

>Show me exactly the commands that you run and the versions of GDB, Python (inside GDB), OS, etc.

Do you need to know how I launch gdb? `gdb`. Closing this for now.

**Comment by cyrus-and** [comment]
> Do you need to know how I launch gdb? `gdb`. Closing this for now.

There's no point in being sarcastic especially when you're asking for unpaid support... Running `gdb` itself is not enough, you need to pass an executable or attach to a process as you well know, a dump of the terminal would've been enough.

**Comment by vtronko** [comment]
1. Works well on other distro
2. Since when can't I start `gdb` on itself without passing an executable? It's an optional parameter. I can always decide what to debug or attach *after* I start gdb. Also, as I said in OP, I tried both ways, so it doesn't really affect the behavior.

This looks like a deeper issue, I will address this later with strace and see what happens underneath, will report my findings if any.

**Comment by cyrus-and** [comment]
> 2\. Since when can't I start `gdb` on itself without passing an executable?

Since when starting `gdb` on itself and not issuing any additional commands invokes the dashboard?

**Comment by vtronko** [comment]
@cyrus-and it makes the gdb quit before I can issue any commands at all.
