### ISSUE TITLE
Simple editor integrations (tips and tricks)

### ISSUE THREAD

**Issue by AndrewJDR** [cyrus-and/gdb-dashboard#20]
This is not so much a feature request or bug report about gdb-dashboard, but more like a tip/trick that might spark some discussion. I think this sort of thing falls outside the scope of gdb-dashboard but it might be interesting to hear how other developers deal with this --

Often I'm in gdb-dashboard on a breakpoint, and maybe I've moved up the callstack a few times and I realize I'd like to have a better look at the current frame's source/line within a text editor (can navigate around the file more easily, search for things, make modifications, etc). To quickly accomplish this, I use something like this in my .gdbinit:

```
define vo
python
import os
sal = gdb.selected_frame().find_sal()
current_line = sal.line
if current_line != 0:
    theCmd = "e " + sal.symtab.fullname() + " | +call cursor(" + str(current_line) + ", 0)"
    #theCmd = "vim --remote-silent +\"" + str(current_line) + "G|\" \"" + sal.symtab.fullname() + "\""
    os.system("tmux set-buffer \"" + theCmd + "\"")
    print(theCmd)
end
end
```

With this script I can type "vo" in gdb and it will put the appropriate vim/ex command onto my tmux buffer so i can paste that into my current vim pane and go right to the location I was just dealing with in gdb. If preferred, you could also run vim --remote-silent with a command and have "vo" immediately open it in your current vim session. I presume emacs and other editors have similar functionality, so you can adapt it to your needs.

Does anyone else use something like this? Any other tips and tricks others are using to integrate gdb with tmux/vim/emacs/etc?

**Comment by cyrus-and** [comment]
Thanks @ajohnson23, this is a good trick!

I don't use similar scripts, at least not worth of sharing, but I'll be happy to keep this issue for these kind of automation techniques, also because GDB dashboard introduces the [`.gdbinit.d` directory](/cyrus-and/gdb-dashboard#configuration) which allows to customize GDB in a modular way.

As you said, this is outside of the goal of GDB dashboard; since the beginning I enforced the idea of not introducing shortcuts nor forcing people to use some particular convention for what concern the workflow.

Nevertheless, this could be a good starting point for sharing user-defined snippets, a kind of *snippet repository*. :)

For example, assuming a vanilla GDB dashboard installation one could place your snippet in `~/.gdbinit.d/vo`.

**Comment by cyrus-and** [comment]
@ajohnson23 I just found a native way to do that: the GDB [`edit` command](https://sourceware.org/gdb/onlinedocs/gdb/Edit.html).

The `EDITOR` environment variable must be set, for example:

    export EDITOR=/usr/bin/vi

Then `edit` from GDB will automatically open the editor of choice at the current program position. This even work after switching frame. The editor is opened within GDB itself.

**Comment by ajohnson23** [comment]
Thanks, good to know there's a stock way of doing that! While personally I don't like a new vim getting opened within gdb, some may find that preferable. And in any case it's useful in a pinch if I'm on a machine where things aren't set up in the style I've grown accustomed to :)

**Comment by ajohnson23** [comment]
I also use https://github.com/vim-scripts/minimal_gdb.git which is a lightweight vim plugin to set breakpoints that are then reflected in gdb. Very lightweight and straightforward.

**Comment by elKokito** [comment]
if this is the right place to ask, is there a way to output each layout in a different terminal? I saw that you can redirect all the output to another terminal, but is there more control about that? Ideally each layout would have is own terminal for output...

**Comment by cyrus-and** [comment]
@elKokito Unfortunately that's not possible at the moment. It's a planned feature though...

**Comment by cyrus-and** [comment]
@elKokito FYI that feature has been [now][1] implemented!

[1]: https://github.com/cyrus-and/gdb-dashboard#display-each-module-in-a-separate-terminal

**Comment by phcerdan** [comment]
@AndrewJDR Thanks for pointing to [minimal_gdb](https://github.com/vim-scripts/minimal_gdb.git). I like the approach of just creating breaks in vim. I have forked it (and created a PR) for making it compatible with python3 as well. https://github.com/phcerdan/minimal_gdb
