### ISSUE TITLE
How to hide the title/divider

### ISSUE THREAD

**Issue by leslielg** [cyrus-and/gdb-dashboard#200]
I'm using dashboard + tmux as my gdb frontend, please see below screenshot, they look perfect for my usage. My question is there any way to hide the dashboard title (Source, Registers...)? So it can fit in tmux more pretty.

**Comment by cyrus-and** [comment]
> My question is there any way to hide the dashboard title (Source, Registers...)?

Not yet, but I think I can implement it. Thanks for the suggestion.

**Comment by cyrus-and** [comment]
Alright this should do, use:

```
dashboard -style omit_divider True
```

PS sorry for the long delay, busy times...

**Comment by leslielg** [comment]
Thanks, just tried and very good now. except "Threads" and "output/messages" still showing...
![image](https://user-images.githubusercontent.com/5469646/81477278-80d60900-9249-11ea-9db4-3b71991981d8.png)

**Comment by cyrus-and** [comment]
"Threads" is shown because there is at least another module on that TTY (even if disabled), you can check with `dashboard -layout`. Let me take care of the rest...

**Comment by cyrus-and** [comment]
OK, it should work as expected now, please give it a try.

**Comment by leslielg** [comment]
Works well now:
![image](https://user-images.githubusercontent.com/5469646/81490144-0ccf4b80-92b1-11ea-8129-86f18b75c26c.png)
