### ISSUE TITLE
Couldn't find ~/.gdbinit.d/ folder . How do I update the default configuration of dashboard?

### ISSUE THREAD

**Issue by rishi1906** [cyrus-and/gdb-dashboard#201]
I want to make the following changes to be made everytime I run the dashboard as part of an bash script.

dashboard source -style height 0
dashboard variables -style sort True
dashboard variables -style compact False
dashboard source -output /dev/pts/19
dashboard variables -output /dev/pts/20

I couldn't find a way to save these changes to the mentioned ~/.gdbinit.d/ directory?

**Comment by cyrus-and** [comment]
Just put those lines in a file inside that directory, create it if it doesn't exist.

**Comment by cyrus-and** [comment]
For reference, this [wiki](https://github.com/cyrus-and/gdb-dashboard/wiki/Use-personal-configuration-files) page.
