### ISSUE TITLE
Registers section messed up

### ISSUE THREAD

**Issue by fazibear** [cyrus-and/gdb-dashboard#204]
Tried iTerm2 and Allacrity.

![Screen Shot 2020-06-16 at 12 55 37](https://user-images.githubusercontent.com/687/84766239-bef4e400-afd0-11ea-80c4-bd47f0cf0022.png)

**Comment by cyrus-and** [comment]
Well since this isn't obviously the intended behaviour you should add a more details about how you achieved that, a bigger screenshot, etc.

**Comment by fazibear** [comment]
THe problem is with `xmm` registers. They displaying as
```
     xmm0 {
  v4_float = {[0] = 0, [1] = 0, [2] = 0, [3] = 0},
  v2_double = {[0] = 0, [1] = 0},
  v16_int8 = {[0] = 0 <repeats 16 times>},
  v8_int16 = {[0] = 0, [1] = 0, [2] = 0, [3] = 0, [4] = 0, [5] = 0, [6] = 0, [7] = 0},
  v4_int32 = {[0] = 0, [1] = 0, [2] = 0, [3] = 0},
  v2_int64 = {[0] = 0, [1] = 0},
  uint128 = 0
}
```
And the layout is totally messed up.

**Comment by cyrus-and** [comment]
It's not an easy task, what you can do is watch expressions only for those extended registers that you need.

**Comment by fazibear** [comment]
The easiest way is to display only 128bit value.
