### ISSUE TITLE
Error 'utf-8' codec can't decode byte 0x96 in position 32435: invalid start byte

### ISSUE THREAD

**Issue by paulorb** [cyrus-and/gdb-dashboard#205]
I am trying to use gdb dashboard, I am getting this error when breaking at a specific breakpoint

Traceback (most recent call last):
  File "<string>", line 542, in render
  File "<string>", line 1182, in lines
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 32435: invalid start byte

Thanks
Paulo

**Comment by paulorb** [comment]
I tried your suggestion, from the Wiki but is still not working

export LC_CTYPE=C.UTF-8

**Comment by paulorb** [comment]
By  running the command
python -c "import sys; print(sys.stdout.encoding)"

It gives me:
UTF-8

echo $LANG gives me:
en_US.UTF-8

gdb -nx -ex 'python with open("/dev/null") as f: print(f.encoding)' -ex quit  gives me:
UTF-8

**Comment by cyrus-and** [comment]
Version of GDB and Python (as per [this][1])?

Can you reproduce it with any source program? If not would it be possible that you provide a minimal C/C++ program that I can compile and try here?

[1]: https://github.com/cyrus-and/gdb-dashboard/wiki/Obtain-the-Python-version-used-by-GDB
