### ISSUE TITLE
1 step in debugging is so slow

### ISSUE THREAD

**Issue by andrea2312** [cyrus-and/gdb-dashboard#208]
On large C++ projects, 1 step over simple code line in debugging, took about 8 seconds.

**Comment by cyrus-and** [comment]
Try to toggle `Source` and `Assembly` to see which one is the culprit.

I'm kind of aware of this (I suspect the culprit is `Assembly`) but I'm still looking for a way to reliably reproduce this. If you could help me reproduce this it would be great. :)
