### ISSUE TITLE
can't see source

### ISSUE THREAD

**Issue by roboticsai** [cyrus-and/gdb-dashboard#209]
Source is showing at top as a result i'm not able to view the execution. threads, variabvls and stacks are comming above the command line in gdb. also how to increase the hight of source.

**Comment by cyrus-and** [comment]
To select which modules to display in which order see this [wiki entry](https://github.com/cyrus-and/gdb-dashboard/wiki/Select-which-modules-to-display).

To set the height of the source module use: `dashboard source -style height 20`.

Each module has its own attributes, e.g., for the source: `help dashboard source -style`.
