### ISSUE TITLE
Displaying multi-byte values in the Memory view

### ISSUE THREAD

**Issue by gshrikant** [cyrus-and/gdb-dashboard#21]
It would be useful to add support to display memory words (16/32/64 bits) in the Memory view akin to the gdb `x` command. The gdb `x` command is often used with more than 1 byte arguments and similar functionality would be nice to have in the dashboard.

I'm already working on this but I wanted to document this feature request if someone else has this on mind too. In either case, I'll try to send a pull request soon. :-)

**Comment by cyrus-and** [comment]
Premise: the Memory module is not a replacement for the GDB `x` command. Even if it would be somewhat nice to have all the expressive power of such command I don't feel like to re-implement all the format configurations nor to use the output of `x` itself. Moreover, even focusing on the *size* only, we have to consider that the `x` command takes into account endianness in printing multi-byte values.

For the above reasons I decided to make the Memory module as simple as possible, it's easy to start improving its format and ending up with an huge unmaintainable module.

A similar issue concerns the Expressions module as it might involve formatting options too.

Actually, I have no great solution for this... The idea is to use the Memory module to obtain a raw memory dump given an address, while the Expression module, using casts, to have a bit more control on the interpretation. For example, to simulate `x/10xh data` one could use:

    dashboard expressions watch ((short*)data)[0]@10

Remember that the values printed by the Expression and History modules are subject to the GDB input/output preferences (I should probably mention this in the doc...). So to display hexadecimal values one could issue:

    set radix 16

I'm aware that this is not as versatile as the native GDB formatting mechanism, but I think it can be a fair trade off, also considering that GDB dashboard is not a proper front end, rather, a visualization aid.

**Comment by GulinSS** [comment]
> `set radix 16`

Or try `set output-radix 16`. Worked for me as well.

Hi from 2025! Still impressive module! Thanks much!
