### ISSUE TITLE
Garbled text on Windows terminal?

### ISSUE THREAD

**Issue by rflmota** [cyrus-and/gdb-dashboard#212]
Hello,

I'm trying to use GDB dashboard on Windows 10 (previous success using it on Mac OS terminal), but getting a strange output with garbled text which I can't understand why (already tried with ConEmu but got the same result). Can someone help me debug by GDB dashboard installation? Ty

![2020-07-29 15_21_38-Window](https://user-images.githubusercontent.com/5682257/88812290-758edb80-d1af-11ea-895f-95477cd33039.png)

**Comment by cyrus-and** [comment]
Your terminal apparently does not support UTF-8. Show me the output of the following:

```console
$ python3 -c 'print("\u00a7")'
§
```

If you cannot fix that, you can always use ASCII characters for the dashboard elements, for example:

```
dashboard -style divider_fill_char_primary '-'
dashboard -style divider_fill_char_secondary '-'
dashboard -style value_truncation_string '...'
```

**Comment by rflmota** [comment]
Hi @cyrus-and , thank you for your feedback! I've tried setting up Windows CMD for UTF-8 support with `chcp 65001` but without success. But I've now tried with ConEmu terminal emulator and it's able to render the UTF-8 characters properly. Thank you for your tip ;)

**Comment by jgroman** [comment]
@rflmota Found this solution how to enable full Python UTF-8 output in Windows Terminal: https://stackoverflow.com/questions/60262015/encoding-problem-atom-cant-print-utf-8-%C3%A4-%C3%B6-%C3%BC
