### ISSUE TITLE
Bug: Source code does not show when breakpoints are set within a template

### ISSUE THREAD

**Issue by kammce** [cyrus-and/gdb-dashboard#215]
```
Traceback (most recent call last):
  File "<string>", line 486, in render
  File "<string>", line 1138, in lines
  File "<string>", line 300, in fetch_breakpoints
ValueError: invalid literal for int() with base 16: '9.1'
```

When creating a breakpoint in template functions, the breakpoint number sometimes becomes a decimal number, which tends to break gdb dashboard as the number is not a whole number.

**Comment by cyrus-and** [comment]
This should be already addressed, possibly a regression... Can you provide some minimal source code?

**Comment by kammce** [comment]
Sorry this was my mistake. I had multiple .gdbinit(s) on my system and an older one was getting in the way. Sorry for the confusion. Closing this bug.

**Comment by cyrus-and** [comment]
No worries! Cheers.
