### ISSUE TITLE
Tab completion occasionnally breaks

### ISSUE THREAD

**Issue by Arpafaucon** [cyrus-and/gdb-dashboard#217]
Hello, and thanks for this great front-end ! I litterally cannot live without it, you're the best :)

I noticed that, sometimes, the <TAB> autocompletion stops working in the middle of a debugging session. Typing `u<TAB>` will not show command completions, but will insert an actual TAB instead.

I haven't found a simple list of steps to reproduce the problem. If someone else does, feel free to post it here! @cyrus-and, if you have some pointers of what could be the problem, that might help me find a way to reproduce it reliably?

I'll work a lot with GDB in the following days, I hope to find something more tangible to work on. If I don't, I'll let you know so you can close this issue.

**Comment by cyrus-and** [comment]
You're too kind! :)

Hmm, that never happened to me and I cannot think of anything right now, but maybe a screenshot can help.

**Comment by Arpafaucon** [comment]
I still observed the problem, without getting any more useful infos.  You do well to close that then :)

For the record, here are some version infos:
- ubuntu 18.04 container, on a ubuntu 20.04 host
- `GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git`
- latest released dash.

**Comment by cyrus-and** [comment]
Thanks for the details, feel free to comment if you come up with something new.
