### ISSUE TITLE
Changing syntax_highlighting value has no effect

### ISSUE THREAD

**Issue by IdanBanani** [cyrus-and/gdb-dashboard#219]
seems like even when manually trying to change it's value, it takes no effect (colors looks like Monkai- which has bad colors selection for registers names)
How can I know if it's a problem with my .gdbinit configuration (conflicts) or a bug in gdb-dashboard?

**Comment by cyrus-and** [comment]
Did you just post the **whole** content of `.gdbinit` in a issue?

**Comment by cyrus-and** [comment]
> How can I know if it's a problem with my .gdbinit configuration (conflicts) or a bug in gdb-dashboard?

Try with a fresh vanilla installation and try to change the syntax highlighting stile from a live session, see if works in that way, and show me what you've tried.

This just works here, for example:

```
dashboard -style syntax_highlighting 'default'
```
