### ISSUE TITLE
Potential for handling STDIN

### ISSUE THREAD

**Issue by kammce** [cyrus-and/gdb-dashboard#220]
As far as I know, GDB has no clean way to accept STDIN from keyboard input. But maybe with the help of gdb-dashboard this is possible. Feel free to close this if the idea is not feasible.

**Comment by cyrus-and** [comment]
Please elaborate, I don't think I'm getting your idea.

**Comment by kammce** [comment]
Sorry for the delay. So the idea here is to support something like this:

```C++
#include <iostream>

int main()
{
  int x;
  std::cout << "Type number: " << std::endl;
  std::cin >> x;
  std::cout << "Number = " << x << std::endl;
  return 0;
}
```

Now currently in gdb you have to do io redirects like so, which can only be done at the start of the program. 

```
(gdb) run < input.in
```

The user doesn't have the option to type in the input themselves. This becomes more complicated if there are a bunch of input fields to type in. 

Are you getting what I mean now?

**Comment by cyrus-and** [comment]
OK, thanks for the explanation. But even in vanilla GDB when the program reads from stdin the user is able to type interactively:

```console
user@playground:~$ gdb ./a.out
(gdb) run
Starting program: /home/user/a.out
Type number:
123
Number = 123
[Inferior 1 (process 481) exited normally]
```

Am I missing something?

**Comment by kammce** [comment]
Ah, I think I'm mistaken then. My use case is for embedded and now I think that my issue is with my semihost implementation and not GDB itself. Thanks for the patience here.

**Comment by cyrus-and** [comment]
No worries, good luck!
