### ISSUE TITLE
Exception in the `Register` window

### ISSUE THREAD

**Issue by lbmeng** [cyrus-and/gdb-dashboard#222]
When remote debugging a QEMU ARM target, after `target remote :1234`, there is an exception in the `Register` window:

QEMU: v5.2.0
GDB: v10.1 configured with `--with-python=/usr/bin/python3`

```
─── Registers  ─────────────────────────────────
Traceback (most recent call last):
  File "<string>", line 538, in render
  File "<string>", line 1940, in lines
ValueError: max() arg is an empty sequence
─── Source ─────────────────────────────────
```

**Comment by cyrus-and** [comment]
See #190.

**Comment by lbmeng** [comment]
> dashboard registers -style list 'r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 r12 sp lr pc cpsr'

Works for me. Thanks!
