### ISSUE TITLE
gdb.error: There is no member named keys

### ISSUE THREAD

**Issue by lbmeng** [cyrus-and/gdb-dashboard#223]
When debugging, I see:

```
─── Output/messages ────────────────────────────
121         QTAILQ_FOREACH(kid, &b->children, sibling) {
Traceback (most recent call last):
  File "/usr/share/glib-2.0/gdb/glib_gdb.py", line 158, in children
    return self._iterator(self.val, self.keys_are_strings)
  File "/usr/share/glib-2.0/gdb/glib_gdb.py", line 108, in __init__
    self.keys = self._pointer_array(ht["keys"], ht["have_big_keys"])
gdb.error: There is no member named keys.
```

The reproduce steps are complicated as I am using QEMU remote gdb debugging and I believe this error might be related to the program I am debugging. Let me know if I need to provide some additional information.

**Comment by cyrus-and** [comment]
Hmm, I don't see the dashboard in the stack trace, it could be unrelated. Does the dashboard gets printed after? Does this happen if you disable the dashboard (`dashboard -enabled off`)?

**Comment by lbmeng** [comment]
Sorry, somehow I could not reproduce this issue any more :(

> Does the dashboard gets printed after?
Yes

> Does this happen if you disable the dashboard (dashboard -enabled off)?
I will try to disable the dashboard next time I see this.

**Comment by lbmeng** [comment]
Today I encountered this issue again.

> Does this happen if you disable the dashboard (dashboard -enabled off)?

The issue can still happen if I disabled the dashboard. The gdb erros happens when I "p/x <some_variable>"

```
>>> p/x *s
...
      parent_obj = {
        class = 0x555556436260,
        free = 0x7ffff7be7db0,
        properties = 0x5555568de460Traceback (most recent call last):
  File "/usr/share/glib-2.0/gdb/glib_gdb.py", line 158, in children
    return self._iterator(self.val, self.keys_are_strings)
  File "/usr/share/glib-2.0/gdb/glib_gdb.py", line 108, in __init__
    self.keys = self._pointer_array(ht["keys"], ht["have_big_keys"])
gdb.error: There is no member named keys.
,
        ref = 0x2,
        parent = 0x55555658dba0
      },
...
```

**Comment by cyrus-and** [comment]
If `p/x *s` alone is enough to trigger it then it's not a dashboard issue, this is some bug in the GDB helper for GLib. You should probably file an issue there, or maybe this is a [duplicate][1] which is now fixed.

[1]: https://gitlab.gnome.org/GNOME/glib/-/issues/863

**Comment by cyrus-and** [comment]
In the meanwhile, I suggest to patch that file locally.

**Comment by lbmeng** [comment]
> 
> 
> If `p/x *s` alone is enough to trigger it then it's not a dashboard issue, this is some bug in the GDB helper for GLib. You should probably file an issue there, or maybe this is a [duplicate](https://gitlab.gnome.org/GNOME/glib/-/issues/863) which is now fixed.

Thanks. This issue seems to be a duplicate of the one you mentioned.

**Comment by lbmeng** [comment]
> In the meanwhile, I suggest to patch that file locally.

I am not sure which file to patch. The GNOME issue link does not say much. I am using GDB 10.1 so this issue is still not fixed in the upstream (?)

**Comment by cyrus-and** [comment]
> I am not sure which file to patch.

The file `/usr/share/glib-2.0/gdb/glib_gdb.py` at line 108.

> I am using GDB 10.1 so this issue is still not fixed in the upstream (?)

This file is not part of GDB, it comes with GLib, for example [`libglib2.0-dev`](https://packages.debian.org/buster/amd64/libglib2.0-dev/filelist) in Debian.

Also I suspect you're using an old version of GLib? I don't find correspondence with the stack trace in the stable version.

**Comment by lbmeng** [comment]
> 
> 
> > I am not sure which file to patch.
> 
> The file `/usr/share/glib-2.0/gdb/glib_gdb.py` at line 108.
> 
> > I am using GDB 10.1 so this issue is still not fixed in the upstream (?)
> 
> This file is not part of GDB, it comes with GLib, for example [`libglib2.0-dev`](https://packages.debian.org/buster/amd64/libglib2.0-dev/filelist) in Debian.
> 
> Also I suspect you're using an old version of GLib? I don't find correspondence with the stack trace in the stable version.

I am using Ubuntu 20.04. glib must have been installed as part of some other packages due to dependencies.

**Comment by cyrus-and** [comment]
> glib must have been installed as part of some other packages due to dependencies.

But still you're debugging GLib executables, if you don't care about the GLib pretty printer I guess you can always disable it.

**Comment by lbmeng** [comment]
> > glib must have been installed as part of some other packages due to dependencies.
> 
> But still you're debugging GLib executables, if you don't care about the GLib pretty printer I guess you can always disable it.

Do you know how to disable that? Thanks!

**Comment by cyrus-and** [comment]
Maybe [this][1] can help, otherwise I don't know, just remove/rename those `.py` files.

[1]: https://sourceware.org/gdb/current/onlinedocs/gdb/Pretty_002dPrinter-Commands.html

**Comment by lbmeng** [comment]
> Maybe [this](https://sourceware.org/gdb/current/onlinedocs/gdb/Pretty_002dPrinter-Commands.html) can help, otherwise I don't know, just remove/rename those `.py` files.

Thanks! The following command can disable the glib-2.0 pretty-printer.

> disable pretty-printer /lib/x86_64-linux-gnu/libglib-2.0.so.0
