### ISSUE TITLE
Splitting the screen horizontally

### ISSUE THREAD

**Issue by charliegreen** [cyrus-and/gdb-dashboard#226]
Is it possible to have a layout that splits the screen horizontally (ie, having two modules displayed side by side, rather than on top of each other)?

On my terminal (which happens to be 173 x 44 characters when full-screened) there's a lot of blank space to the right of the useful information, and I think it would be really useful and convenient to trade this for more vertical real-estate for individual modules (especially the source code, assembly, and memory modules).

I looked through the source and this didn't seem to be implemented, so I think this is more of a feature request, but if I'm wrong and there's a way to do this then I'd love to hear it. Thanks!

**Comment by cyrus-and** [comment]
You can achieve that by using [multiple terminals](https://github.com/cyrus-and/gdb-dashboard/wiki/Use-multiple-terminals).
