### ISSUE TITLE
source'ing before the program is running give no gdb prompt

### ISSUE THREAD

**Issue by bgirard** [cyrus-and/gdb-dashboard#23]
Reproduction:
mozilla@mozgfx-rr-orange-hunter-1:~/scratch/gdb-dashboard$ gdb sleep
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
<...>
(gdb) source /home/mozilla/scratch/gdb-dashboard/.gdbinit

This gives no prompt on my Mac and Linux box.

**Comment by cyrus-and** [comment]
It seems that I cannot reproduce this. Starting `gdb` without any `.gdbinit` file and then sourcing GDB dashboard before starting the program produces:

```
$ gdb sleep
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from sleep...(no debugging symbols found)...done.
(gdb) source /home/cyrus/dev/gdb-dashboard/.gdbinit 
>>> 
```

**Comment by bgirard** [comment]
Ahh, I had another look. Turns out the prompt is black on my black background and thus invisible. It gave the impression that is was hanging while starting up. When the program is running it's a purple prompt and it's clearly visible. 

Sorry this is very silly =\. Might be handy to not have a black prompt since black console are common but feel free to close if you want.

**Comment by cyrus-and** [comment]
Well, it should not be black, it should be [gray][1]! :) More precisely [bright black][2].
I think there's a problem with your terminal, here's the expected result:

![2016-01-16-015240_131x69_scrot](https://cloud.githubusercontent.com/assets/1660263/12369193/e0aa9958-bbf3-11e5-9c13-6e6aeaad17ef.png)

[1]: https://github.com/cyrus-and/gdb-dashboard/blob/52e145d05e1f49eb2639ce3ff78b74f835847964/.gdbinit#L42
[2]: https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

**Comment by patrickdepinguin** [comment]
The display of these ANSI colors is dependent on the color scheme of the terminal. With some settings, the dashboard is effectively unreadable.
For example, with the 'Solarized (light)' preset present in most gnome-like terminals, the prompt and the register names are indeed not visible. Changing the color palette a bit fixes that.
It would be nice though if gdb-dashboard would not require changes to such preset palettes.

**Comment by cyrus-and** [comment]
@patrickdepinguin IMHO a terminal scheme should be able to correctly display at least the most common [ANSI styles][1], i.e.:

```bash
for b in {0..1}; do
    for c in {30..37}; do
        code="$b;$c"
        printf "\x1b[${code}m${code}\x1b[0m\n"
    done
done
```

Anyway, GDB dashboard does not require any changes in the terminal scheme, pretty much everything can be [configured][2], so for example to change the prompt color and all the other *greyish* text, one could put the following lines in any file within `~/.gdbinit.d/`:

```
dashboard -style prompt_not_running '\[\e[1;31m\]>>>\[\e[0m\]'
dashboard -style style_low '1;31'
```

Now all the previously *greyish* text will be displayed as red.

Users are encouraged to tune the default color scheme, it's almost impossible to provide a (nice) default which works well with all the possible terminal configurations.

[1]: https://en.wikipedia.org/wiki/ANSI_escape_code#Colors
[2]: https://github.com/cyrus-and/gdb-dashboard#stylable-attributes
