### ISSUE TITLE
Can't use dashboard with source

### ISSUE THREAD

**Issue by assafmendelson** [cyrus-and/gdb-dashboard#230]
Hi,
I have my own .gdbinit and I was prefering not to replace it with gdb-dashboard but instead to use it.
So I tried to source gdb-dashboard's gdbinit file.
This failed with various errors (e.g. encoding error etc.)
I was wondering if there is a way to use gdbinit externally.
What I tried (and failed):
source gdb-dashboard_file

gdb -x gdb-dashboard_file

I know I can move my private configuration to ~/.gdbinit-d/, however, for integration with other tools, this can be a little cumbersome

**Comment by cyrus-and** [comment]
> I know I can move my private configuration to ~/.gdbinit-d/, however, for integration with other tools, this can be a little cumbersome

This is the recommended way. And BTW you can use that setup but keep the dashboard off with `dashboard -enabled off`.

Sourcing the dashboard with `source` should work in principle. I can try to help if you provide more info about your own `.gdbinit` and the errors that you encounter.

**Comment by SirEnder125** [comment]
How can I use this?

**Comment by cyrus-and** [comment]
> How can I use this?

@SirEnder125 this what?

**Comment by SirEnder125** [comment]
gdb dashboard
where is the install instructions

**Comment by cyrus-and** [comment]
@SirEnder125 the README...? Also, how is it relevant to this issue?
