### ISSUE TITLE
Feature request: indicate how conditional instruction will evaluate

### ISSUE THREAD

**Issue by Kibouo** [cyrus-and/gdb-dashboard#231]
Having to look up eflag requirements isn't productive. A small indicator, next to the current line of assembly, which shows how the current conditional instruction will evaluate would ease reasoning about the instruction flow.

An example of the interface: the icons `+` and `-` could be used and placed in the very first column (same column as the `!`). It would overwrite the `!` if needed. E.g. if we will jump here: 
```
─── Assembly ────────────────────────────────────────────────────────────────────────────────────────
+0xf7fcce88  74 71                 ? je     0xf7fccefb <_dl_start+187>
 0xf7fcce8a  89 75 d4              ? mov    DWORD PTR [ebp-0x2c],esi
!0xf7fcce8d  bb ff ff ff 6f        ? mov    ebx,0x6fffffff
 0xf7fcce92  eb 1e                 ? jmp    0xf7fcceb2 <_dl_start+114>
 0xf7fcce94  8d 74 26 00           ? lea    esi,[esi+eiz*1+0x0]
```

I could have a look at this myself if interested. Having a list of all conditional instructions would be the biggest task.

**Comment by cyrus-and** [comment]
I'm interested in adding this feat only if GDB provides a native and architecture-independent way to do that. I certainly don't want to maintain a table (for each architecture) where each jump instruction is mapped to the `eflags` configuration that makes it jump.

**Comment by Kibouo** [comment]
As I understand, while the conditionals per architecture are clearly defined, different architectures have different lists?

**Comment by cyrus-and** [comment]
Yes, I mean different architectures have different instruction sets with their own semantics, and different registers. Now for the latter point, GDB abstracts the processor status registers, so that `$ps` always refers to the correct one (e.g., `$ps` is EFLAGS in x86), but this alone is not enough...

> I've not seen any feature for this in gdb yet.

Yep, until then, I close this issue. Feel free to comment if you come up with something.
