### ISSUE TITLE
setupterm: could not find terminfo database

### ISSUE THREAD

**Issue by maich** [cyrus-and/gdb-dashboard#232]
Hi, 
I saw that this issue was opened and closed and the solution was to run a different gdb ie. mingw64 gdb vs msys2 gdb. 
From my testing, both show similar errors.
Here is a snippet from your recommendation:

```
> env | grep TERM
TERM_PROGRAM_VERSION=3.4.5
TERM=xterm
TERM_PROGRAM=mintty

> python -c 'import curses; curses.initscr().getmaxyx(); curses.endwin()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.8/curses/__init__.py", line 29, in initscr
    setupterm(term=_os.environ.get("TERM", "unknown"),
_curses.error: setupterm: could not find terminfo database
```

Finally when running the dashboard, I get the following similar error:

```
Type "apropos word" to search for commands related to "word"...
Reading symbols from xvstr...
>>> b 8
Breakpoint 1 at 0x1400015ac: file xvstring.c, line 8.
>>> run
Starting program: C:\msys64\home\nmkiguta\src\c\string\xvstr.exe
[New Thread 7888.0x66e0]
Traceback (most recent call last):
  File "<string>", line 417, in on_continue
  File "<string>", line 594, in get_term_size
  File "C:/msys64/mingw64/lib/python3.8/curses/__init__.py", line 29, in initscr
    setupterm(term=_os.environ.get("TERM", "unknown"),
_curses.error: setupterm: could not find terminfo database

Thread 1 hit Breakpoint 1, main (argc=1, argv=0x1908a7f3c80, envp=0x1908a7f2600) at xvstring.c:8
8               int index = 0;
Cannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 509, in render
  File "<string>", line 594, in get_term_size
  File "C:/msys64/mingw64/lib/python3.8/curses/__init__.py", line 29, in initscr
    setupterm(term=_os.environ.get("TERM", "unknown"),
_curses.error: setupterm: could not find terminfo database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 511, in render
  File "<string>", line 594, in get_term_size
  File "C:/msys64/mingw64/lib/python3.8/curses/__init__.py", line 29, in initscr
    setupterm(term=_os.environ.get("TERM", "unknown"),
_curses.error: setupterm: could not find terminfo database
```

I am using Msys64 and just downloaded the latest (~24hrs) dashboard and running into this issue. Any help is greatly appreciated - I like the layout from dashboard and would like to use it.

Thanks!

**Comment by cyrus-and** [comment]
OK I managed to spin a Windows VM where I installed MSYS2:

``` console
$ env | grep TERM
TERM_PROGRAM_VERSION=3.4.5
TERM=xterm
TERM_PROGRAM=mintty
```

Then `pacman -S python` and then the following command completes succesfully:

```console
$ python -c 'import curses; curses.initscr().getmaxyx(); curses.endwin()'
```

The `terminfo` root directory is in `/usr/share/terminfo/` and `xterm` is supported.

---

The only difference I see is that, according to your stack trace, paths start with `C:\` while I'm in the MSYS2 terminal where paths start Unix-style with `/`.

**Comment by maich** [comment]
Thanks so much for the quick response!

I can run the quick test using the non-mingw python successfully. However, dashboard still doesn't work. When I launch it, I get a different error and dashboard abruptly clears the screen and errors out with 'Cannot access memory at address 0xxxxx'.

**Comment by cyrus-and** [comment]
> I get a different error

Which one? If you cannot read because of the screen refresh use:

    dashboard -style discard_scrollback False

> errors out with 'Cannot access memory at address 0xxxxx'

This could be another unrelated problem, please tell me exactly what you're trying to debug, how do you start GDB, and what commands you issue.

**Comment by maich** [comment]
$ /usr/bin/gdb
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-msys".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "<string>", line 4, in <module>
_ModuleNotFoundError: No module named 'libstdcxx'_
/etc/gdbinit:7: Error in sourced command file:
Error while executing Python code.

So I don't get too far with that. With the mingw gdb and python instead, I get:

 gdb poly
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from poly...
>>> dashboard -style discard_scrollback False
>>> b 8
Breakpoint 1 at 0x1400015a8: file polymer_puzzle.c, line 17.
>>> run
Starting program: C:\msys64\home\nmkiguta\src\c\poly.exe
[New Thread 3712.0x4ab4]
Traceback (most recent call last):
  File "<string>", line 417, in on_continue
  File "<string>", line 595, in get_term_size
_curses.error: endwin() returned ERR

Thread 1 hit Breakpoint 1, main (argc=1, argv=0x21fae2d3cb0) at polymer_puzzle.c:17
Cannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 509, in render
  File "<string>", line 595, in get_term_size
_curses.error: endwin() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 511, in render
  File "<string>", line 595, in get_term_size
_curses.error: endwin() returned ERR

So I get further with dashboard with the mingw gdb but, run into a python curses error.

Here are the term settings:

$ env | grep TERM
TERM_PROGRAM_VERSION=3.4.5
TERMINFO=/usr/share/terminfo
TERM=xterm
TERM_PROGRAM=mintty

The mingw python error's out the same way when I run the curses test program:

$ which python
/mingw64/bin/python

$ python -c 'import curses; curses.initscr().getmaxyx(); curses.endwin()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
_curses.error: endwin() returned ERR


From this, it looks like the winning combination would be /usr/bin/python with the /mingw64/bin/gdb, though sadly the mingw gdb is compiled with a different python. 

That's the problem I am having and frankly it looks like it has nothing to do with dashboard per se.

**Comment by cyrus-and** [comment]
The first error (non-mingw gdb) is clearly something unrelated, you can either try to fix that or disable/debug other init files (`/etc/gdbinit`).

About the second error, it's weird that this time the exception is different from the initial one...

**Comment by cyrus-and** [comment]
Closing for now, feel free to ask if you come up with something new.

**Comment by Transformation742** [comment]
https://stackdev.space/questions/is-there-a-way-to-incorporate-color-into-a-particular-string-using-python-curses-library Check out this finding
