### ISSUE TITLE
no releases provided anymore?

### ISSUE THREAD

**Issue by anthraxx** [cyrus-and/gdb-dashboard#234]
Hi,

We are packaging gdb-dashboard as a distro package but it seems that releases have been removed and no new releases are issued. We currently are therefor stuck with gdb-dashboard 0.11.4.
Would it be possible to bring back semi frequent release tags?

cheers

**Comment by cyrus-and** [comment]
Hi, sure, just pushed [v0.12.0](https://github.com/cyrus-and/gdb-dashboard/releases/tag/v0.12.0). Sorry but I always end up forgetting this. Thanks for the heads up!

(If it happen again in the future feel free to ping me, here, email, whatever...)

**Comment by anthraxx** [comment]
thank you!
