### ISSUE TITLE
[Question] Display layout in a vertical split.

### ISSUE THREAD

**Issue by surmish** [cyrus-and/gdb-dashboard#239]
I'm using just the output and the source sections, is there a way I can view them in a  veritical split window? (same terminal)

**Comment by c02y** [comment]
Are you using tmux? If you do, I got a simple solution.

**Comment by cyrus-and** [comment]
@surmish nope you need to use some terminal multiplexer, like tmux, screen etc.

**Comment by surmish** [comment]
Yes, I use tmux. I noticed another question asking a similar question. Will close the issue, thanks!
