### ISSUE TITLE
Setting output to another pts gives error on Ubuntu 20.04

### ISSUE THREAD

**Issue by hp-pepster** [cyrus-and/gdb-dashboard#241]
Hi,

first, thanks for your really helpful project, I love and use it a lot.

Usually I use manjaro for my daily work, but at the moment I am forced to use WSL2 with Ubuntu 20.04 on my company laptop.

When trying to set the output to another pts, I get the following error:

```
Cannot write the dashboard
Traceback (most recent call last):
File "<string>", line 504, in render
TypeError: write() argument 1 must be unicode, not str
```
every time the dashboard gets refreshed.

I also tried it on another PC with native kubuntu 20.04.

I do the following with gdb-dashboard v0.13.0 from git:
- open a new terminal with xterm, get the number with tty -> e.g. `/dev/pts/6`
- start gdb session for arm (arm-none-eabi-gdb)
- `dashboard variables -output /dev/pts/6`
- Seems to be ok
- `step`
- The error occurs and nothing is put on the terminal

It does not matter if I set the output for variables or anything else. I tried xterm and konsole.

Please tell me if you need more information

**Comment by cyrus-and** [comment]
Hi! I'm glad to hear that (the former part :).

What's the version compiled with your GDB? Try to run this GDB command:

```
python import sys; print(sys.version)
```

**Comment by hp-pepster** [comment]
Hi,

thanks for your quick reply.
```
>>> python import sys; print(sys.version)
2.7.18 (default, Mar  8 2021, 13:02:45)
[GCC 9.3.0]
```

**Comment by hp-pepster** [comment]
For anyone searching for an answer, here you can get a recent version with py3: https://xpack.github.io/arm-none-eabi-gcc/install/

I only use the binary for gdb and with that gdb-dashboard works as it should.

**Comment by cyrus-and** [comment]
Nice, it should work with Python 2 too though, so I'll try to reproduce it. What's the easiest way to obtain the Python 2 version?

**Comment by hp-pepster** [comment]
I guess here: https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

**Comment by hp-pepster** [comment]
The bin with python-support is called `arm-none-eabi-gdb-py`

**Comment by cyrus-and** [comment]
Alright, it should work even with Python 2 now.

**Comment by hp-pepster** [comment]
For me, the py2-version works as well. Thank you for the fix. Nevertheless I will stick to the py3-version of GDB.
