### ISSUE TITLE
Line break issue in variable module

### ISSUE THREAD

**Issue by raspine** [cyrus-and/gdb-dashboard#242]
I just found this excellent project and am trying to set it up. The variable view does not insert line breaks between variables, I just get a long line of all variables. I can see from the main example image that there are line breaks between each variable.
Is this at all a 'style' option?

**Comment by cyrus-and** [comment]
Yes there is!

    dashboard variables -style compact False

You can figure that out using the `help` command (for pretty much anything):

```
>>> help dashboard variables -style
[...]
dashboard variables -style align -- Align variables in column flag (only if not compact)
dashboard variables -style arguments -- Frame arguments visibility flag
dashboard variables -style compact -- Single-line display flag
dashboard variables -style locals -- Frame locals visibility flag
dashboard variables -style sort -- Sort variables by name
[...]
```

**Comment by raspine** [comment]
ah.. I see my error, I used that exact line with 'false' instead of 'False'. Thanks!

**Comment by cyrus-and** [comment]
Those values are actual Python values, so for example `0` and `1` will work too.
