### ISSUE TITLE
how to launch it?

### ISSUE THREAD

**Issue by laurentHYZ** [cyrus-and/gdb-dashboard#244]
I have installed your file as you explained, do you have a video or a detailed explanation showing how we can your dashboard? Right now I am using gdb, I set some breaks etc. but your dashboard does not show up.
thank you

**Comment by cyrus-and** [comment]
It should just work, the dashboard will appear as soon as the program stops on a breakpoint. What is your GDB prompt?

**Comment by laurentHYZ** [comment]
I launch GDB within my terminal, set my break, run my program and at each next things work without problem, the original debugging functionalities of GDB are working properly and your tool just does not appear at all. I guess I must have missed something obvious when installing it or something. I did copy your file within my home directory, I think that's what I am supposed to do.

**Comment by cyrus-and** [comment]
Please answer the following.

What is your GDB prompt?

What is the output of `ls -l ~/.gdbinit*`?

**Comment by laurentHYZ** [comment]
ls -l ~/.gdbinit*:
-rw-rw-r-- 1 laurent laurent    39 Jun  5 12:59 /home/laurent/.gdbinit
-rw-rw-r-- 1 laurent laurent 90195 Jun  8 13:05 /home/laurent/.gdbinit.1

As for the gdb prompt:
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
pwndbg: loaded 188 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
pwndbg> Quit
pwndbg>

**Comment by cyrus-and** [comment]
```
-rw-rw-r-- 1 laurent laurent 39 Jun 5 12:59 /home/laurent/.gdbinit
-rw-rw-r-- 1 laurent laurent 90195 Jun 8 13:05 /home/laurent/.gdbinit.1
```

You already had a `.gdbinit` file in your home directory (pwndbg?), so `wget` created `.gdbinit.1` (gdb-dashboard). If you don't mind losing the original `.gdbinit` file, you can fix this with:

```console
$ rm -i ~/.gdbinit*
$ wget -P ~ https://git.io/.gdbinit
```

**Comment by laurentHYZ** [comment]
Working now, thank you VERY much both for your product and your timely support. :+1: :pray:

**Comment by cyrus-and** [comment]
Thanks! I'm glad you made it work. :)
