### ISSUE TITLE
lldb alternative

### ISSUE THREAD

**Issue by zchrissirhcz** [cyrus-and/gdb-dashboard#245]
Hi, thanks for providing this awesome gdb config.

I'm currently debugging an android ndk program, and using lldb-server / lldb.

Wondering if this config is also suitable for lldb?

Thanks.

**Comment by cyrus-and** [comment]
Thanks!

Eh, sorry no. LLDB is a totally different beast, that would require a complete rewrite. Maybe in the future, but very unlikely.
