### ISSUE TITLE
layout asm not supported

### ISSUE THREAD

**Issue by fishiu** [cyrus-and/gdb-dashboard#251]
when i entered asm layout, the cmd window ran into a mess with meaningless characters, my gdb version is 8.2-3.el7, it init with no problem. By the way, if the dashboard has no planning for asm layout, i wonder how can i debug with asm (in the dashboard i can't dynamically move the code lines to see more)

**Comment by cyrus-and** [comment]
A screenshot would help me understanding your issue.

**Comment by fishiu** [comment]
Thanks for relying! here is a screen shot when i run "layout asm". By the way, i wonder how can i make some offset for the highlighted assembly line in dashboard so i can see the lines before it.
  
​
  
​

**Comment by cyrus-and** [comment]
> here is a screen shot when i run "layout asm"

I'm afraid there's no screenshot in your message. :)

> By the way, i wonder how can i make some offset for the highlighted assembly line in dashboard so i can see the lines before it.

See `help dashboard assembly scroll`. Similarly it applies to the `source` module as well.

**Comment by fishiu** [comment]
![image](https://user-images.githubusercontent.com/47969730/130409900-b7815c55-e1f3-459d-845b-620a484dfedf.png)

**Comment by cyrus-and** [comment]
That's not the dashboard, you entered TUI mode, which is not compatible.

**Comment by cyrus-and** [comment]
You don't need to enter TUI mode with `C-x C-a`, nor to start GDB with the `-tui` option. You just need to place the `.gdbinit` file in your home (which according to the screenshot you already did) then debug as usual. Please let me know if you cannot make it work.
