### ISSUE TITLE
highlight bg color of the current line by default

### ISSUE THREAD

**Issue by aaalgo** [cyrus-and/gdb-dashboard#252]
I think only highlight the line number of current line is really not sufficient.  I tried to change the background and it feels much better.

```
line = line.rstrip('\n')
line = '\x1b[42m{}\x1b[0m'.format(line)
```

![a](https://user-images.githubusercontent.com/5427210/131918126-844f5d56-6940-499c-a98a-9809d2efb07d.png)

**Comment by cyrus-and** [comment]
It does actually, I reverted this feature in 0736cf338ae810d9b4e374360589c6d7ada229cf because of [this](https://github.com/cyrus-and/gdb-dashboard/issues/116#issuecomment-386554430). Is this no more the case now?

**Comment by aaalgo** [comment]
Seems not any more.  It now makes sense to me why this is not done by default.

**Comment by cyrus-and** [comment]
Reverted again, now you can use the `highlight-line` option of source and assembly modules to do that.
