### ISSUE TITLE
Weird prompt (escape seq not recognized?)

### ISSUE THREAD

**Issue by mlomonaco** [cyrus-and/gdb-dashboard#253]
I installed the latest `.gdbinit` with gdb 8.2.1 linked against python 3.7.7
I get this weird prompt
```^A^[[90m^B>>>^A^[[0m^B```
What can it be? It looks a similar issue found in the past, about misinterpreted color escape sequences
Thanks

**Comment by cyrus-and** [comment]
What OS are you running?

Also what if you try the following in your terminal (plain shell, not GDB)?

```
PS1='\[\e[90m\]>>>\[\e[0m\] '
```

You should see the prompt changed like grey `>>> `.

**Comment by mlomonaco** [comment]
The PS1 works.
OS is Linux 4.19.
I get those wrong escape seqs everytime there is an output.
```^A^[[90m^B>>>^A^[[0m^B dashboard
^[[31mIs the target program running?^[[0m
^A^[[90m^B>>>^A^[[0m^B```

**Comment by mlomonaco** [comment]
Let's close this one.

**Comment by cyrus-and** [comment]
Glad you figured it out, cheers.
