### ISSUE TITLE
Show global variables

### ISSUE THREAD

**Issue by jjungo** [cyrus-and/gdb-dashboard#256]
Hello,

gdb-dashboard is very nice, thanks for your work! 
I cannot found how to show/watch global variable with gdb-dashboard ?
It would be nice to have something like `dashboard variables watch <my_symbol>`.

Best,

**Comment by cyrus-and** [comment]
> gdb-dashboard is very nice, thanks for your work!

Thanks! It's great to hear that. :)

> I cannot found how to show/watch global variable with gdb-dashboard ?

Yep, global variables are not shown in the Variables or Stack modules. Even in vanilla GDB they can't be found in `backtrace full`. But you can list them with `info variables`. 

> It would be nice to have something like `dashboard variables watch <my_symbol>`.

But there is! :) Only it's part of the Expressions module, and it's not limited to single values, you can put whatever complex expression in there. For example:

```
dashboard expressions watch my_global + 1000
```

And it renders like this:

```
─── Expressions ─────────────────
my_global + 1000 = 1042
```

Hope it helps!

**Comment by jjungo** [comment]
> dashboard expressions watch my_global + 1000

Ah I didn't expect that! Thanks
