### ISSUE TITLE
(Feature Request) Let users define the way that show values.

### ISSUE THREAD

**Issue by Afeather2017** [cyrus-and/gdb-dashboard#258]
Users write a function which returns a string to show variables of program.
The function is written in the language that users use.
I think it is pretty cool and a great convenience for users.
I programmed a function which returns an string that shows binary tree directly, and edited gdb-dashboard. I hope variables could print in Variables layout like this.
![Screenshot_20220130_213300.png](https://s2.loli.net/2022/01/30/m1CAGhZVTfD7tXY.png)
But there is a problem. Dashboard call my function before initialization, then program is killed by system because invalid dereference operate to a pointer.
So I try to use `gdb.lookup_symbol(name)[0].line` to get where the value defined, and use `gdb.selected_frame().find_sal().line`, simply compare two line to understand whether value is initialized or not.
Dashboard print my binary tree like this now.
![Screenshot_20220130_000116.png](https://s2.loli.net/2022/01/30/Csghu3RiAIXyeBF.png)
May be this way is not safe, but I don't know how to improve.
And this way is not always true.
Let me show my example.
![Screenshot_20220131_081736.png](https://s2.loli.net/2022/01/31/TBl5IUzaOYmRtWC.png)
Program runs into line 177, and then goes to line 176, variable i is initialized, but simply compare is not work.
And there is another problem: if there are 2 variables have same name, I just get only one of them.
Let me use an example to show what I said.
Here are my code. Dashboard run `traversal(list)` while debugging, which returns a string shows elements of LinkedList.
![Screenshot_20220130_214300.png](https://s2.loli.net/2022/01/30/E1y8dqpKHCPnMig.png)
Program runs to line 165, dashboard shows like this.
![Screenshot_20220130_215209.png](https://s2.loli.net/2022/01/30/MtQI5bFDig7jYd8.png)
while line 172, shows like this.
![Screenshot_20220130_215051.png](https://s2.loli.net/2022/01/30/tFXNLS7TVujBzap.png)
I know `gdb.lookup_symbol(name)[0].line` returns same value when program runs to the inner block.
And I know there is no way to use `gdb.parse_and_eval("traversal(list)")` to print the first list.
Can we hide the first list? Add a new command which choose hide or not may be good.

And, I upload the code I edited.
https://github.com/Afeather2017/gdb-dashboard
Edit it as you like!

**Comment by cyrus-and** [comment]
Though convenient, I don't believe that letting GDB using pieces of the target code to print some data structures while debugging the same code is a great idea after all.

GDB developers already have solved this issue by introducing the concept of [pretty printing][1]. Follows an example for your convenience.

Take this simple C++ program:

```c++
#include <iostream>
using namespace std;

class Foo {
    public:

        Foo(int x)
            : x_(x) {}

        int x() const {
            return x_;
        }

    private:

        int x_;
};

int main() {
    Foo foo(123);
    std::cout << "= " << foo.x() << "\n";
}
```

Then create this [configuration file][2], say `foo_pretty_printer.py`:

```py
import gdb.printing


class FooPrinter:
    def __init__(self, value):
        self._value = value

    def to_string(self):
        x = self._value['x_']
        return '< Foo | x = {} >'.format(x)


def build_pretty_printer():
    pp = gdb.printing.RegexpCollectionPrettyPrinter("foo_library")
    pp.add_printer('foo', '^Foo$', FooPrinter)
    return pp


gdb.printing.register_pretty_printer(
    gdb.current_objfile(),
    build_pretty_printer()
)
```

Now if you debug the above program, every time an instance of the `Foo` class is to be displayed, the custom pretty printer is used:

```
─── Variables ───────────────
loc foo = < Foo | x = 123 >
─────────────────────────────
```

[1]: https://sourceware.org/gdb/onlinedocs/gdb/Writing-a-Pretty_002dPrinter.html
[2]: https://github.com/cyrus-and/gdb-dashboard/wiki/Use-personal-configuration-files

**Comment by cyrus-and** [comment]
Glad to help! :)

> By the way, this piece of code could add to '.gdbinit'

Maybe overkill to add it, but hopefully interested people will find this issue.
