### ISSUE TITLE
Why after entering the kernel, there are only hexadecimal numbers and no assembly instructions？？

### ISSUE THREAD

**Issue by Leejiajian** [cyrus-and/gdb-dashboard#261]

**Comment by cyrus-and** [comment]
What about some screenshots or a way to reproduce it...?

**Comment by Leejiajian** [comment]
I figured out that jumping in is a piece of assembly code, but it still doesn't feel right.
![ZU695WH1}H)%T8ROSGDG_SG](https://user-images.githubusercontent.com/86450450/155863715-5dfdc3d7-6f78-4d42-a30a-5a9afd33f804.png)

**Comment by cyrus-and** [comment]
Hmm, weird, can you show me the output of `disassemble`, `info registers`, and `info stack`? Also, does continuing the program *works* or eventually causes a crash?

**Comment by Leejiajian** [comment]
the program is fun, just can not show the assembly code.  weird, can not solve this problem. Maybe gdb something is wrong.

**Comment by cyrus-and** [comment]
> Hmm, weird, can you show me the output of `disassemble`, `info registers`, and `info stack`?

Can you?
