### ISSUE TITLE
border line too long

### ISSUE THREAD

**Issue by laoshaw** [cyrus-and/gdb-dashboard#262]
my border line somehow takes two lines, is there a way to make it one line only?

![image](https://user-images.githubusercontent.com/18351761/159101820-e99475c9-9865-41fb-b822-b3af4396cb01.png)

**Comment by cyrus-and** [comment]
This should only happen if you resize your terminal after the dashboard rendered, in that case the next redraw will be correct.

If that's not the case, what's the output of the following command in GDB?

```
python print(Dashboard.get_term_size())
```

And this one in your shell?

```
echo $COLUMNS $LINES
```
