### ISSUE TITLE
IOError: [Errno 25] Ioctl() Inappropriate ioctl for device

### ISSUE THREAD

**Issue by chaumetteh** [cyrus-and/gdb-dashboard#264]
Hi, this issue appeared recently (even with latest `.gdbinit`):
```
Cannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 516, in render
  File "<string>", line 608, in get_term_size
IOError: [Errno 25] Ioctl() Inappropriate ioctl for device
```
As a workaround I have added `IOError` to the exception handling of `get_term_size` and hardcoded my usual terminal size.
According to gdb's python-interactive console, `sys.platform = 'linux2'` on my system (Ubuntu 20.04).

**Comment by cyrus-and** [comment]
Any non default configuration that I should know of?

What if you run the following command within GDB itself?

```sh
!tty; [ -t 1 ] && echo TTY || echo NOT
```

**Comment by chaumetteh** [comment]
I have the issue even with the default configuration.
```
>>> !tty; [ -t 1 ] && echo TTY || echo NOT
/dev/pts/3
NOT
```

**Comment by cyrus-and** [comment]
Well, it seems that for some reason your terminal is not a TTY, this is not strictly a problem with the dashboard.

**Comment by cyrus-and** [comment]
OK, I still think that there's something wrong with your configuration, I cannot think of any scenario in which `stdout` (1) is not a TTY inside a terminal.

Can you please show me the output of this GDB command?

```
!ls -l /proc/self/fd
```

**Comment by chaumetteh** [comment]
I use gdb through ssh:
```
>>> !ls -l /proc/self/fd
total 0
lrwx------ 1 chaumetteh chaumetteh 64 mars  23 13:06 0 -> /dev/pts/3
l-wx------ 1 chaumetteh chaumetteh 64 mars  23 13:06 1 -> pipe:[1476961]
lrwx------ 1 chaumetteh chaumetteh 64 mars  23 13:06 2 -> /dev/pts/3
lr-x------ 1 chaumetteh chaumetteh 64 mars  23 13:06 3 -> /proc/193201/fd
```

**Comment by cyrus-and** [comment]
> I use gdb through ssh

It still doesn't explain... how do you launch everything? Like the following or something more convoluted?

```
local$ ssh user@remote
remote$ gdb /some/program
```

> `1 -> pipe:[1476961]`

Here's the issue.

**Comment by chaumetteh** [comment]
```
gdb -ex "target extended-remote <ip>:<port>" -ex "set remote exec-file <remote_path>" -ex "file <local_file>"
```

**Comment by cyrus-and** [comment]
That's not SSH, anyway I cannot reproduce the issue with.

### Remote

```
$ gdbserver --multi 0.0.0.0:4444
```

### Local

```
$ gdb -ex 'target extended-remote 192.168.1.171:4444'
Remote debugging using 192.168.1.171:4444
>>> python print(Dashboard.get_term_size())
(120, 44)
```

**Comment by chaumetteh** [comment]
It might be a quirk of my target system (embedded ARM 64 board with petalinux).

**Comment by cyrus-and** [comment]
In the meantime, a probably better workaround that respects the actual terminal size, would be to replace `1` with `0` or `2`, in the following, since your `stdin` and `stderr` files still point to the TTY.

https://github.com/cyrus-and/gdb-dashboard/blob/13df4b1267b6cf3545601db0ac5c872317beb189/.gdbinit#L597

**Comment by chaumetteh** [comment]
I have the root cause : GDB is launched from a series of makefiles so badly written I wrapped them in a script and I recently added a `| tee <test_target>.log` in the end.

**Comment by cyrus-and** [comment]
That makes sense, so I guess you can easily fix that. Thanks for letting me know.
