### ISSUE TITLE
"dashboard" in a hookpost-next with recent gdb versions fails

### ISSUE THREAD

**Issue by ajohnson23** [cyrus-and/gdb-dashboard#27]
Firstly, I'm using the latest version of gdb, 7.11, but anything newer than https://github.com/bminor/binutils-gdb/commit/329ea57934a9d4b250a0b417af1ec47bc2d0ceb6 is fine to reproduce the issue.

If I define the following in my .gdbinit:
```
define hookpost-next
dashboard
end
```

Any time I use 'next', I get the following:
```
Traceback (most recent call last):
  File "<string>", line 467, in invoke
  File "<string>", line 260, in redisplay
  File "<string>", line 283, in build
  File "<string>", line 744, in lines
gdb.error: No frame is currently selected.
Error occurred in Python command: No frame is currently selected.
```
It would appear that gdb is trying to run certain things async, and it calls the hookpost-next before the current frame is even set. Interestingly, hookpost-up or hookpost-down with "dashboard" does not cause a problem.

I grabbed the latest git checkout of gdb and ran a bisect on it, and narrowed it down to this commit when the problem started happening:
https://github.com/bminor/binutils-gdb/commit/329ea57934a9d4b250a0b417af1ec47bc2d0ceb6
Which is actually quite old.

No combination of "mt set target-async off" or "set target-async off" seemed to help the issue.
Also potentially relevant:
https://sourceware.org/ml/gdb-prs/2014-q4/msg00102.html

My current workaround is:
```
define n
next
dashboard
vo
end
```
Then I use 'n' instead of 'next'. This actually works fine.
So I guess this is more of a "gotchas with using hookpost-next and workaround" thread rather than a bug report :)

Unless you have an idea on how to make hookpost-next work properly -- I'm actually curious if you observe the same issue.

**Comment by cyrus-and** [comment]
I'm maybe misunderstanding your problem but, why are you hooking `dashboard` to `next`? The default behavior is to draw the dashboard whenever the target stops, hence after each `next`.

**Comment by ajohnson23** [comment]
Ah I hadn't realized that, but the fact is, I do a bunch of other stuff in my hookpost-next, namely I tell my current vim instance to go to the file / line stopped on (which, just like "dashboard", grabs the gdb.current_frame(). So I still need to be able to do stuff in hookpost-next and the original problem still stands. I was just trying to give you a simple repro case without dragging my other vim scripts into the mix.

Can you give me a pointer to how you're running dashboard when the target stops? Since that is working fine whereas the hookpost-next is not, I'll try just using that method for my vim stuff.

**Comment by ajohnson23** [comment]
Just to be clear: Any call to gdb.selected_frame() seems to fail in a hookpost-next... it's not just a 'dashboard' thing. It's very very likely this is a gdb issue and not really a gdb-dashboard issue, but at this point I'm curious what you're using to run 'dashboard' on stoppage so I can just copy that :)

**Comment by ajohnson23** [comment]
(No need to respond on that, I see how it's done)

**Comment by cyrus-and** [comment]
OK, so I can confirm that with the latest GDB version (from [bminor/binutils-gdb](/bminor/binutils-gdb)) the following fails as you say with `gdb.error: No frame is currently selected.`:

```
define hookpost-next
python print gdb.selected_frame()
end
```

Whereas it work with GDB version 7.7; they must have broken something I guess...

Anyway the dashboard is not affected because I'm registering to that event using the [Python API][1] as you can see [here][2]. Hope this helps.

[1]: https://sourceware.org/gdb/onlinedocs/gdb/Events-In-Python.html
[2]: https://github.com/cyrus-and/gdb-dashboard/blob/f6d90de40229abbcb75fc5fa22245f0c0f08c5a9/.gdbinit#L228

**Comment by cyrus-and** [comment]
So as it doesn't seem to be related to the dashboard, can I close this? Feel free to comment here or reach me by email if you have any questions.

**Comment by ajohnson23** [comment]
Thanks for taking the time to confirm that, it's good to have a sanity check.

After using the python API to connect to the stop event, all is well again. Thanks!

**Comment by cyrus-and** [comment]
Great! You're welcome.
