### ISSUE TITLE
(feature request?) Horizontal split

### ISSUE THREAD

**Issue by kazi-code** [cyrus-and/gdb-dashboard#274]
Hi, thanks so much for developing this great tool!

It appears that a horizontal split as provided in the default tui mode[0] does not work with the modules in dashboard.
Am I missing the trick to configure or is it not supported with dashboard at this point?

[0] _e.g._ **tui new-layout example {-horizontal src 1 asm 1} 2 status 0 cmd 1**

**Comment by cyrus-and** [comment]
The dashboard is a replacement for TUI mode; they can't work together. Horizontal split is not supported in a single terminal, but you can use multiple terminals (or `tmux`/`screen` splits). See this [wiki page](https://github.com/cyrus-and/gdb-dashboard/wiki/Use-multiple-terminals).
