### ISSUE TITLE
dashboard commands with convenience variables as arguments issue

### ISSUE THREAD

**Issue by mirekfoo** [cyrus-and/gdb-dashboard#275]
Hi, Dashboard is a great tool !

There is an issue for dashboard commands when invoked with convenience variables as arguments - example:
```
set $limit = 20
dashboard stack -style limit $limit
>>> Invalid argument "$limit"
```

There is an workaround too:
```
define set_stack_view_limit 
python
gdb.execute("dashboard stack -style limit " + str(gdb.convenience_variable("limit"))) 
end
end
```

**Comment by cyrus-and** [comment]
Thanks!

Yes, that's not planned and I don't see an easy way to integrate that. The values used as styles are just plain Python values.

**Comment by cyrus-and** [comment]
You could even go full Python:

```
python
limit = 42
gdb.execute('dashboard stack -style limit {!r}'.format(limit))
end
```
