### ISSUE TITLE
Unable to get gdb-dashboard to load

### ISSUE THREAD

**Issue by mytechnotalent** [cyrus-and/gdb-dashboard#278]
```
warning: File "C:\Users\mytec\Documents\c-stm32f103c8t6-test\.gdbinit" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path C:\Users\mytec\Documents\c-stm32f103c8t6-test\.gdbinit
line to your configuration file "$HOME/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "$HOME/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
```

I have added these lines in `.gdbinit` within the folder and in HOME and it does nothing.

**Comment by cyrus-and** [comment]
This is not a dashboard issue. Does the GDB auto load feature works for any other file?

**Comment by mytechnotalent** [comment]
@cyrus-and thank for getting back to me!  I only have this issue on the Windows `arm-none-eabi-gdb.exe` as this works perfectly in MAC and Linux.  You are likely right it is not a dashboard issue however I am not certain how to resolve to use on Windows.

**Comment by cyrus-and** [comment]
You can start debugging from `show auto-load` and see what's enabled and what's not, then change it accordingly.

**Comment by mytechnotalent** [comment]
`
# Better GDB defaults ----------------------------------------------------------

set history save
set verbose off
set print pretty on
set print array off
set print array-indexes on
set python print-stack full
set auto-load safe-path /

# Start ------------------------------------------------------------------------

python Dashboard.start()

# File variables ---------------------------------------------------------------

# vim: filetype=python
# Local Variables:
# mode: python
# End:
`

I have added the line in `.gdbinit` to completely disable however it still shows up.


`
Type "apropos word" to search for commands related to "word".
warning: File "C:\Users\mytec\Documents\embedded-c\.gdbinit" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path C:\Users\mytec\Documents\embedded-c\.gdbinit
line to your configuration file "$HOME/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "$HOME/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
`

gdb show auto-load
`
(gdb) show auto-load
auto-load gdb-scripts:  Auto-loading of canned sequences of commands scripts is on.
auto-load local-gdbinit:  Auto-loading of .gdbinit script from current directory is on.
auto-load safe-path:  List of directories from which it is safe to auto-load files is $debugdir:$datadir/auto-load.
auto-load scripts-directory:  List of directories from which to load auto-loaded scripts is $debugdir:$datadir/auto-load.
`

**Comment by mytechnotalent** [comment]
```add-auto-load-safe-path C:\Users\mytec\Documents\embedded-c\.gdbinit
```

I also added that to `.gdbinit` as well and same issue.

**Comment by cyrus-and** [comment]
The problem is that GDB does not autoloads the dashboard, hence you cannot expect to fix this issue by altering *this* `.gdbinit`, rather add the suggested line to the global `.gdbinit`.

BTW you can just replace the global `.gdbinit` with the one provided by this repo, but I assume you have good reasons to not doing so.

**Comment by mytechnotalent** [comment]
@cyrus-and thank you for getting back so quick!  Yes I did replace the global `.gdbinit` in my `C:\Users\kevin` directory with the following and it is still not working as expected.
```
# Better GDB defaults ----------------------------------------------------------

set history save
set verbose off
set print pretty on
set print array off
set print array-indexes on
set python print-stack full
add-auto-load-safe-path C:\Users\mytec\Documents\embedded-c\.gdbinit
```

**Comment by cyrus-and** [comment]
Are you sure that the file in `C:\Users\kevin` is sourced when running GDB in `C:\Users\mytec\Documents\embedded-c`?

**Comment by mytechnotalent** [comment]
That is a great question, I know how to do that in Linux however not sure in Windows.  I Googled that for the last few days as I it definiately sees the `.gdbinit` as shown below.
```
PS C:\Users\kevin> arm-none-eabi-gdb.exe
GNU gdb (Arm GNU Toolchain 12.2.MPACBTI-Bet1 (Build arm-12-mpacbti.16)) 13.0.50.20220406-git
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=i686-w64-mingw32 --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.linaro.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
warning: File "C:\Users\mytec\.gdbinit" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path C:\Users\kevin\.gdbinit
line to your configuration file "$HOME/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "$HOME/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
(gdb)

**Comment by cyrus-and** [comment]
The `.gdbinit` file sourced by GDB is the one in your *home* according to the `$HOME` environment variable, make sure it's set to the right value. See [Startup](https://sourceware.org/gdb/onlinedocs/gdb/Startup.html).

**Comment by mytechnotalent** [comment]
It is set to the right value.  I guess this is some Windows permissions issue.
```
$HOME
C:\Users\kevin
```

I appreciate all the help but I don't think there is a work around here.  I am sorry for all the trouble.

**Comment by cyrus-and** [comment]
No worries, I am not a Windows user so I'm afraid I cannot help you further. Good luck!

**Comment by mytechnotalent** [comment]
Thanks!  Your product works amazing in Linux!
