### ISSUE TITLE
Wrong colors displayed

### ISSUE THREAD

**Issue by amab8901** [cyrus-and/gdb-dashboard#279]
This is what I get when I apply `gdb-dashboard`'s `.gdbinit` file:
![image](https://user-images.githubusercontent.com/83634595/198848529-8ca92299-bf15-4294-990a-11f44b92d17c.png)

Here is the color theme I'm expecting (but not getting):
![image](https://user-images.githubusercontent.com/83634595/198848549-03048020-e354-49d4-8a06-ad3422dd2dcf.png)

What am I doing wrong?

**Comment by cyrus-and** [comment]
You cannot use the dashboard in TUI mode.

**Comment by amab8901** [comment]
> You cannot use the dashboard in TUI mode.

oh, thanks. That explains it. I realize that I don't even need TUI if I use dashboard since dashboard has its own built-in version of TUI basically
