### ISSUE TITLE
pycharm не конектит с терминалом ("TERM", "unknown") МАКОС

### ISSUE THREAD

**Issue by VitaliiNaletov** [cyrus-and/gdb-dashboard#282]
setupterm(term=_os.environ.get("TERM", "unknown"), _curses.error: setupterm: could not find terminal
Вот такая ошибка, МАКОС

Доброго времени суток
Как правильно настроить связь pycharm и терминала?
Какие именно переменные нужно прописать в pycharm, чтобы заработало?
<img width="571" alt="qaqa" src="https://user-images.githubusercontent.com/122975812/214969541-57aff4ea-4e75-4f4a-9177-9f6afcfe6b38.png">
<img width="1300" alt="1й1" src="https://user-images.githubusercontent.com/122975812/214969569-b8294a86-ecac-45cd-a6ca-4f3498dd0403.png">
<img width="1295" alt="кук" src="https://user-images.githubusercontent.com/122975812/214969678-f03bc7e9-22f3-4088-9e3c-6be17d322e79.png">

**Comment by cyrus-and** [comment]
English please.

**Comment by VitaliiNaletov** [comment]
That's the error, MACOS

Good day
How to properly set up pycharm and terminal communication?
What variables need to be set in pycharm to make it work?

**Comment by cyrus-and** [comment]
And why would this be about `gdb-dashboard`?

**Comment by VitaliiNaletov** [comment]
I guess I didn't choose the right topic. I'm sorry) Not long ago on your site, I'm still figuring out how to do it. How to do prompt?

**Comment by cyrus-and** [comment]
> How to do prompt?

What do you mean?

This is the bug tracker for [gdb-dashboard](https://github.com/cyrus-and/gdb-dashboard), are you even using GDB?

**Comment by VitaliiNaletov** [comment]
Now I read what it is)

**Comment by VitaliiNaletov** [comment]
My problem is that when I run the program in pycharm, it gives an error (setupterm(term=_os.environ.get("TERM", "unknown"), _curses.error: setupterm: could not find terminal)
Do I need to install gdb?

**Comment by cyrus-and** [comment]
Your issue has nothing to do with this repository.
