### ISSUE TITLE
Wrap registers module into columns?

### ISSUE THREAD

**Issue by shivamkedia17** [cyrus-and/gdb-dashboard#283]
Hello, my currently displayed registers module is too long and it doesn't wrap into columns like the other modules or the ones displayed in the preview screenshots. Switching the -column-Major flag doesn't help. How can I make the registers pane wrap into columns?

Here's what's shown:
<img width="1440" alt="Screenshot 2023-02-17 at 2 20 47 PM" src="https://user-images.githubusercontent.com/65805659/219597806-5e31ee78-d373-49d2-bec1-4637b58485ed.png">
<img width="1440" alt="Screenshot 2023-02-17 at 2 20 54 PM" src="https://user-images.githubusercontent.com/65805659/219597770-ba11c597-d960-4717-a181-3f1271d9c2d2.png">

**Comment by cyrus-and** [comment]
You have to get rid of the `xmm0` register, which due to its format doesn't play nice with the others. If you really need to have a glance at it during the debugging you can create an expression for that, for example:

```
dashboard expressions watch $xmm0.v2_double
```

**Comment by shivamkedia17** [comment]
I don't think `xmm` registers are that important for me to see but although I didn't attach the whole screenshot, there are about 7 of those `xmm` registers. Can you please let me know how to choose to hide that `xmm` register group in the registers pane?

**Comment by cyrus-and** [comment]
They are usually not shown by default, it depends on the architecture and how it's handled by GDB, see this [wiki page](https://github.com/cyrus-and/gdb-dashboard/wiki/Support-architectures-different-from-x86), just put there the ones you need.

What's your architecture anyway?

**Comment by shivamkedia17** [comment]
Thanks! I'm emulating i386 on x86_64 to run MIT's xv6.
