### ISSUE TITLE
gibberish when stop

### ISSUE THREAD

**Issue by approxdec** [cyrus-and/gdb-dashboard#288]
g'day.

gdb-dashboard is 'working'
but it when it stops it shows lines of blue
 â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?

like this

0x00007ff65b961818  main+13 lea    0xf891(%rip),%rax        # 0x7ff65b9710b0
 0x00007ff65b96181f  main+20 mov    %rax,%rcx
 0x00007ff65b961822  main+23 call   0x7ff65b961584 <printf>
 0x00007ff65b961827  main+28 lea    -0xc(%rbp),%rcx
 0x00007ff65b96182b  main+32 lea    -0x8(%rbp),%rdx
â"?â"?â"? Breakpoints â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?
[1] break at 0x00007ff65b961818 in quadratic.c:42 for main hit 1 time
â"?â"?â"? Expressions â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?
â"?â"?â"? History â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?
â"?â"?â"? Memory â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?
â"?â"?â"? Registers â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?
      rax 0x0000000000000001         rbx 0x000001d42f7e14a8      rcx 0x0000000000000001      rdx 0x000001d42f7e14a0
      rsi 0x000000000000001b         rdi 0x000001d42f7e14e0      rbp 0x000000440afff6b0      rsp 0x000000440afff680
       r8 0x000001d42f7e1f70          r9 0x000000002f7e0000      r10 0x0000000000000013      r11 0x000000440afff4d8
      r12 0x0000000000000008         r13 0x0000000000000000      r14 0x0000000000000000      r15 0x0000000000000000
      rip 0x00007ff65b961818      eflags [ IF ]                   cs 0x00000033               ss 0x0000002b
       ds 0x0000002b                  es 0x0000002b               fs 0x00000053               gs 0x0000002b
â"?â"?â"? Source â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?

![dashboard](https://user-images.githubusercontent.com/3886404/225213055-7ab2b6b0-1825-4d0c-bb34-39ce8c0755c6.jpg)

i am using **mingw64-gcc12.2.0**

how to fix this?

regards

joe

**Comment by cyrus-and** [comment]
It seems your terminal doesn't like UTF8, you can try with:

```
dashboard -style divider_fill_char_primary '-'
dashboard -style divider_fill_char_secondary '-'
```

**Comment by approxdec** [comment]
😀
thanks.
it is working well .
