### ISSUE TITLE
disconnect stop/cont events for db -enabled off

### ISSUE THREAD

**Issue by ajohnson23** [cyrus-and/gdb-dashboard#29]
I would suggest disconnecting the stop and cont events when dashboard is disabled (and reconnect them when enabled). event connections can significantly slow things down if you have define some commands on a breakpoint like this:
```
commands 1
output somevar
cont
end
```
aka a *trace point* in msvc terminology. When doing this kind of debugging it's handy to have a way to "fully" disable dashboard.

**Comment by ajohnson23** [comment]
Something like:
https://github.com/ajohnson23/gdb-dashboard/commit/11c08d6a7efece793c78c721ee905fbf8aea5774

(python is not my native tongue)

**Comment by cyrus-and** [comment]
While I agree that disconnecting the events may be a better approach, can you please provide a minimal example to reproduce that slowing you mentioned?

I've tried the following and I didn't notice any difference between having the dashboard disabled and removing the `.gdbinit` file altogether.

```c
int main () {
    int i = 10000;
    while (i) {
        i--;
    }
}
```

Compile with `gcc -g3 test.c`, then:

```
$ cat commands
dashboard -enabled off

break 4

commands 1
output i
continue
end

run
quit
```

Finally:

```
$ time gdb -x commands a.out
[...]
Breakpoint 1, main () at test.c:4
4               i--;
2
Breakpoint 1, main () at test.c:4
4               i--;
1[Inferior 1 (process 17727) exited with code 0266]

real    0m3.971s
user    0m2.540s
sys     0m1.192s
```

**Comment by cyrus-and** [comment]
Your patch worked fine but I seized the opportunity to refactor that part.

**Comment by ajohnson23** [comment]
It was happening in my project which is rather large (maybe project size / deeper call stacks exacerbates / causes the issue), but I can't include it here. And sorry, I've no spare time at the moment try  to minimize it! If you're saying it doesn't happen with smaller programs, I believe you.
No pressure to merge it on your part, I can just maintain it in my fork.

**Comment by ajohnson23** [comment]
(Ah you included it anyway.. Thanks!)

**Comment by cyrus-and** [comment]
> And sorry, I've no spare time at the moment try to minimize it!

No problem! Thanks for the suggestion.
