### ISSUE TITLE
crashed when I debug a cuda app

### ISSUE THREAD

**Issue by shenxiaolong-code** [cyrus-and/gdb-dashboard#290]
I only open the source windows.
if not load this script, the application works.

─── Variables ──────────────────────
Traceback (most recent call last):
  File "<string>", line 550, in render
  File "<string>", line 1556, in lines
  File "<string>", line 1612, in format_frame
  File "<string>", line 1631, in fetch
gdb.error: dwarf2_find_location_expression: Corrupted DWARF expression.

**Comment by cyrus-and** [comment]
This is likely a GDB bug, you should report to them. Or maybe it has been already reported, like: https://bugzilla.redhat.com/show_bug.cgi?id=439234

Upgrade your GDB if that's the case. I cannot, obviously, do anything about this with only that piece of information you provided, no versions, no program, no nothing. Plus I currently have no way to debug CUDA apps.
