### ISSUE TITLE
[Feature Request]: unwatch expression by id

### ISSUE THREAD

**Issue by N-R-K** [cyrus-and/gdb-dashboard#291]
I find it very cumbersome to re-type the entire expression (which sometimes can be complicated) just to unwatch something. Would it be possible to unwatch via id, e.g `dash exp unwatch 1` ?
(Or anything else that's easier than typing the entire expression?)

**Comment by gavinhoward** [comment]
User here, not author.

I also want this, and I'd be willing to give an attempt if @cyrus-and approves.

**Comment by cyrus-and** [comment]
That's a good idea, done.
