### ISSUE TITLE
Cannot write the dashboard

### ISSUE THREAD

**Issue by bj-edward** [cyrus-and/gdb-dashboard#295]
gdb> target remote 127.0.0.1:1234
Remote debugging using 127.0.0.1:1234
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0x0000fff0 in ?? ()
Cannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 512, in render
PermissionError: [Errno 13] Permission denied: '/dev/pts/10'

ls /dev/pts/10
ls: cannot access '/dev/pts/10': No such file or directory

gdb> !tty; [ -t 1 ] && echo TTY || echo NOT
/dev/pts/2
TTY

**Comment by cyrus-and** [comment]
Do you think this is a comprehensive bug report?
