### ISSUE TITLE
AttributeError: 'module' object has no attribute 'COMMAND_USER'

### ISSUE THREAD

**Issue by gowithqi** [cyrus-and/gdb-dashboard#3]
here are my commond:
$ wget -P ~ git.io/.gdbinit
$ gdb

it should be a more gui interface, but i didn't see it. 
the Traceback here:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 241, in start
  File "<string>", line 171, in __init__
AttributeError: 'module' object has no attribute 'COMMAND_USER'

**Comment by RedAntCN** [comment]
I met the same problem and solved it by upgrading gdb to the latest version

**Comment by cyrus-and** [comment]
@gowithqi Yes, as @RedAntCN said you can fix this by upgrading your GDB. Anyway, can you tell me which is your current version?

**Comment by fdicarlo** [comment]
Same here:

GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2.1) 7.4-2012.04

**Comment by cyrus-and** [comment]
@fdicarlo same traceback too?

> AttributeError: 'module' object has no attribute 'COMMAND_USER'

**Comment by fdicarlo** [comment]
I've this one:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 241, in start
  File "<string>", line 171, in __init__
AttributeError: 'module' object has no attribute 'COMMAND_USER'
/home/fabrizio/.gdbinit:1093: Error in sourced command file:
Error while executing Python code.

**Comment by gowithqi** [comment]
@cyrus-and my GNU gdb is the same as @fdicarlo 

GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2.1) 7.4-2012.04

**Comment by cyrus-and** [comment]
I think that:

    sed -i 's/COMMAND_USER/COMMAND_NONE/g' .gdbinit

will solve this particular issue, but I'm afraid it will be useless. Please refer to #1 as it concerns compatibility issues with a newer GDB version (7.6).

I strongly recommend you to upgrade your GDB to a newer version, at least 7.7.
