### ISSUE TITLE
Clion GDB

### ISSUE THREAD

**Issue by kaboussi** [cyrus-and/gdb-dashboard#302]
The debugger script performs optimally when using the FiraCode Nerd Font in the terminal, but when utilizing the same font in the CLion IDE, it does not function as anticipated.
![image](https://github.com/cyrus-and/gdb-dashboard/assets/95357302/a8f5d311-a21e-46b8-96c2-7916a4b73aa7)

**Comment by cyrus-and** [comment]
I suspect your IDE's terminal does not support [ANSI codes](https://en.wikipedia.org/wiki/ANSI_escape_code). You can disable colors in the dashboard with:

```
dashboard -style ansi False
```
