### ISSUE TITLE
armv8 registers cannot be displayed

### ISSUE THREAD

**Issue by angcaisenscomm** [cyrus-and/gdb-dashboard#303]
When I use the GDB Dashboard to debug an ARMv8 program, I find that the 'registers' section cannot be displayed.

─── Registers───────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "<string>", line 550, in render
  File "<string>", line 2012, in lines
  File "<string>", line 2085, in format_value
  File "<string>", line 275, in to_unsigned
OverflowError: long too big to convert

**Comment by cyrus-and** [comment]
Does this happen always, with any program? If not, can you come up with a minimal source code that reproduces this issue?

**Comment by angcaisenscomm** [comment]
It seems to be related to my environment. There's no need to investigate this issue further. I will close it. Sorry for the inconvenience.
