### ISSUE TITLE
Last command still fails on gdb 8.2-19.el8 on rocky 8

### ISSUE THREAD

**Issue by fj526** [cyrus-and/gdb-dashboard#304]
For example:
(gdb) python gdb.execute('echo asd')
asd
(gdb)
(gdb)
(gdb)
(gdb)

See
 Last command in GDB no longer functions after installing dashboard #165 
for prior mention in 2018.

Sadly disabling register and assembly doesn't help.
Is there another workaround?
Thanks

**Comment by cyrus-and** [comment]
Works for me in GDB 13.2, I guess they eventually fixed it again in some later version. Unfortunately there's nothing I can do about it. This seems to be a bug in your version of GDB.

**Comment by fj526** [comment]
Thanks very much for looking into this.  I had not realized I was so far in the past on versions, as that's all that comes up 
for rocky 8 update using dnf (unless I'm botching that as well...). I'll look into getting a more modern gdb.  
By the way, the dashboard thing is a huge improvement in productivity.
Regards,
f
