### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by vs97849** [cyrus-and/gdb-dashboard#308]
Not able to install on linux bash environment. Gives python errors.
Tried with multiple gdb version newer and older. nothing works. (and with newer and older version of python too)
kindly try configuring and make it compatible with linux bash env too.

**Comment by cyrus-and** [comment]
> Gives python errors.

Do you really think that this can be somehow helpful?! The dashboard _obviously_ works with Linux, and Bash has nothing to do with it. I can't help you if you don't provide additional information, like, you know, the actual "python errors"...

**Comment by vs97849** [comment]
Ok, will share errors by tomorrow. Meanwhile kindly correct me if I am
wrong in process ? :
Download .gdbinit into my home.
That's it

**Comment by cyrus-and** [comment]
Yes, that's correct.

**Comment by vs97849** [comment]
Hi, please find the steps & error below:

*wget -P ~ https://git.io/.gdbinit <https://git.io/.gdbinit>*

$ gdb
GNU gdb (GDB) 12.1
....
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 590, in start
  File "<string>", line 643, in parse_inits
ValueError: zero length field name in format
~/.gdbinit:2375: Error in sourced command file:
Error while executing Python code.
>>>

**Comment by cyrus-and** [comment]
You seem to be using an [incompatible](https://github.com/cyrus-and/gdb-dashboard/wiki/Support-older-GDB-versions) Python [version](https://github.com/cyrus-and/gdb-dashboard/wiki/Obtain-the-Python-version-used-by-GDB), can you confirm?

**Comment by vs97849** [comment]
Seems reasonable, shell environment is set up with 3.6 python but gdb is
still picking 2.7 from !/usr/bin/python, and I do not have permission to do
that.
Can you suggest how to start gdb with required version of python?

**Comment by cyrus-and** [comment]
What's the output of the following command? Python >= 2.7 should be fine.

```
gdb --batch -ex 'python import sys; print(sys.version)'
```

> Can you suggest how to start gdb with required version of python?

You can compile GDB yourself and use it from your home folder directly.

**Comment by vs97849** [comment]
error/output of your command:
$ *gdb --batch -ex 'python import sys; print(sys.version)'*
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 590, in start
  File "<string>", line 643, in parse_inits
ValueError: zero length field name in format
/u/vinods/.gdbinit:2375: Error in sourced command file:
Error while executing Python code.
2.6.5 (r265:79063, Jul 14 2010, 00:26:33)
[GCC 3.2.3 20030502 (Red Hat Linux 3.2.3-20)]

**Comment by cyrus-and** [comment]
> Seems reasonable, shell environment is set up with 3.6 python but gdb is still picking 2.7 from !/usr/bin/python, and I do not have permission to do that.

... so you have version 2.6.5 available. Try to build your own GDB locally.

**Comment by vs97849** [comment]
Hi, why closed , giving error with python 3.9 too

**Comment by cyrus-and** [comment]
What error...?

**Comment by vs97849** [comment]
Pls confirm the error receipt.

Errors highlighted Red:


*$ python --versionPython 3.9.2*

$ gdb

For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 590, in start
  File "<string>", line 643, in parse_inits
ValueError: zero length field name in format
/u/vinods/.gdbinit:2375: Error in sourced command file:
Error while executing Python code.

**Comment by cyrus-and** [comment]
It's the version of Python inside GDB that counts, not the one that you run from your shell, see, again, this [wiki page](https://github.com/cyrus-and/gdb-dashboard/wiki/Obtain-the-Python-version-used-by-GDB).

**Comment by vs97849** [comment]
Thanks for saying, as found the cause *it was due to screen session (screen
-S <name>) when a screen shell is opening, python , gdbs were set to as
before*.
Then I tested without screen, then it ran without error.

*could you please suggest what can I do , so that it runs with screen
session too.*
*I tried removing my personal .screenrc too, but didn't work. *

Thanks

**Comment by cyrus-and** [comment]
Screen has nothing to do about it. You just have a GDB version not compatible with the dashboard as it is compiled against a too old Python version.

**Comment by vs97849** [comment]
Actually, without screen session, it is working fine. But when screen
session is started, python version is being reset to older version.
Why this might be happening, how can we resolve this issue?

**Comment by cyrus-and** [comment]
Running `python --version` does not prove anything, related to this issue.

**Comment by vs97849** [comment]
Hi Andrea,  Any solution or I can do to find the root cause?
Explain problem in detail in previous reply

**Comment by cyrus-and** [comment]
This has nothing to do with the dashboard, it rather concerns your environment. I'm sorry but it would be too hard for me helping you debugging that.

**Comment by vs97849** [comment]
You are right. It's all about python version being reset , checked in
*.screenrc* too but couldn't find anything .
So need to know what else might be involved when screen shell is started
