### ISSUE TITLE
[Enhancement] trace from born till death 

### ISSUE THREAD

**Issue by vs97849** [cyrus-and/gdb-dashboard#310]
Hi pls suggest a way, it will save huge time and manual efforts, 
How can we get each and every line information/code statements via gdb from start of program till next breakpoint or program completes

@cyrus-and

**Comment by cyrus-and** [comment]
I think you want [tracepoints](https://ftp.gnu.org/old-gnu/Manuals/gdb-5.1.1/html_chapter/gdb_10.html), but this is something unrelated to the dashboard's behaviour.
