### ISSUE TITLE
gdb attach (dashboard not display)

### ISSUE THREAD

**Issue by huangxueyan** [cyrus-and/gdb-dashboard#320]
When I use sudo to launch gdb and attach it to some process, the dashboard does not appear. 
I think the dashboard cannot run with the attach or sudo command. Is it right?

**Comment by cyrus-and** [comment]
That's likely because you installed the dashboard in your home only, you need to install it in `/root/.gdbinit` too.

**Comment by huangxueyan** [comment]
You're right, I just need to symlink the gdbinit file to the /root directory. But the C++ syntax highlighting doesn't seem to be working anymore. Do you know what could be the reason for that。 Thanks！

**Comment by cyrus-and** [comment]
Pygments must be available for the root user as well.

**Comment by huangxueyan** [comment]
that is great !
