### ISSUE TITLE
how to expand stack?

### ISSUE THREAD

**Issue by dragonxlwang** [cyrus-and/gdb-dashboard#33]
It seems the stack info is folded when there is more than two levels. How can I expand it?

**Comment by cyrus-and** [comment]
The default limit is 2, you can expand it with:

    dashboard stack -style limit 10

Or remove the limit altogether:

    dashboard stack -style limit 0

---

FYI you can use the GDB `help` command with pretty much all the dashboard sub/commands; in this case:

    help dashboard stack
