### ISSUE TITLE
error on initialization

### ISSUE THREAD

**Issue by albfan** [cyrus-and/gdb-dashboard#35]
after issuing start

    >>> start

get this output

<pre>
Traceback (most recent call last):
  File "<string>", line 199, in <lambda>
  File "<string>", line 215, in on_stop
  File "<string>", line 254, in build
  File "<string>", line 961, in lines
  File "<string>", line 119, in run
gdb.error: Undefined command: "when".  Try "help".
</pre>

and it keeps showing after every command (next, step)

calling

    >>> dashboard -layout source

fixes error and subsequent commands do not output that trace.

**Comment by cyrus-and** [comment]
That's quite strange since that `run()` is always called with some constant strings (and none of them starts with `"when"`). Try again with a pristine setup: delete `~/.gdbinit*` and reinstall gdb-dashboard as shown in the README.

**Comment by albfan** [comment]
Sorry, seems I get script from a fork

https://github.com/bgirard/gdb-rr-dashboard/blob/master/.gdbinit#L965
