### ISSUE TITLE
How to create an alias/function for a command like bash/fish?

### ISSUE THREAD

**Issue by c02y** [cyrus-and/gdb-dashboard#37]
Every time I open gdb to debug a binary, I create a pane side by side (I use tmux), and then use *tty* command to get the info of the new created pane, and then back to the gdb session pane, use 

    dashboard -output /dev/pts/N

to ouput the info to the new created pane.

So, if there a way to create an alias/function, for example, if I'm in fish-shell, I would this:

    function dod
        dashboard -output /dev/pts/$argv[1]
    end

so in gdb session I can just use `dod N` to execute the long 'dashboard -output /dev/pts/N' command.

Or you have better solution?

BTW: I have no knowledge of Python.

**Comment by cyrus-and** [comment]
A [GDB function](https://sourceware.org/gdb/onlinedocs/gdb/Define.html) should work:

```
define dod
    dashboard -output /dev/pts/$arg0
end
```
