### ISSUE TITLE
How to print stl container pretty?

### ISSUE THREAD

**Issue by littletiny** [cyrus-and/gdb-dashboard#38]

**Comment by littletiny** [comment]
Thank you
I found this:  https://sourceware.org/bugzilla/show_bug.cgi?id=16310

**Comment by cyrus-and** [comment]
You're welcome.

> I found this: https://sourceware.org/bugzilla/show_bug.cgi?id=16310

I meant issues about the integration of the STL scripts with the dashboard, if you managed to make it work then OK.
