### ISSUE TITLE
Cgdb-like source listing. [feature request]

### ISSUE THREAD

**Issue by dariomanesku** [cyrus-and/gdb-dashboard#4]
I use cgdb instead of gdb because of the nice source code listing. Whenever I use 'up/down/next/step...', I know where I'm at, all the time. Other than that, I have many issues with cgdb and I would like to stop using it. The only thing I want in gdb is the nice code listing, which gdb-dashboard provides, but only half way through.

I see gdb-dashboard is using 'gdb.newest_frame()' in some places and it's only showing the source code of the last frame and not the current frame. Can you make gdb-dashboard behave like cgdb in terms of source code listing when using 'up/down' commands to change the current frame. Have a look at cgdb behavior and tell me what you think.

**Comment by dariomanesku** [comment]
If I change 'newest_frame()' to 'selected_frame()' it kind of does what it should, but 'dashboard' command resets the frame to #0 after the call. How do I make it NOT do that?

**Comment by oblitum** [comment]
+1

**Comment by cyrus-and** [comment]
That was a good advice, thank you guys.

**Comment by dariomanesku** [comment]
:+1:

**Comment by dariomanesku** [comment]
Dashboard redraws itself after 'step/next' and similar, but not after 'up/down'. Can you add that?

**Comment by cyrus-and** [comment]
@dariomanesku right now the dashboard shows up whenever the target program *stops*; I receive an event for that from GDB. To implement what you suggest the only way I know is to add an hook to both `up` and `down` commands, but then I should add one to the `frame` command too (e.g., `frame 0`), and probably to a bunch of other commands which alter the information shown by the dashboard, e.g., `set $rax = 0`. This is clearly a mess. The preferred approach, for the moment being, is that users willing to have the dashboard updated after a specific GDB command add custom hooks to their own [init file](/cyrus-and/gdb-dashboard#configuration). In your case:

```
define hookpost-up
dashboard
end

define hookpost-down
dashboard
end
```

I probably should mention this in the README...

P.S., anyway remember that `db` is enough to redraw the dashboard.

**Comment by dariomanesku** [comment]
Those hooks are doing exactly what I want. Thanks.
