### ISSUE TITLE
allow resizing of modules

### ISSUE THREAD

**Issue by mellowcandle** [cyrus-and/gdb-dashboard#41]
Feature request:
Allow resizing of modules using commands or mouse (in browser)

**Comment by cyrus-and** [comment]
I'm afraid this is impossible at the moment, the outputs are *read-only*, that is, GDB dashboard simply dumps its content to a TTY. And quite frankly I doubt I'll ever implement such a feature; it would be a too big change and something that goes beyond the goals of this init script; it's important to understand that this is not a GDB frontend, rather, this is a GDB *helper*.

Nevertheless, there's a related (planned) feature that will allow to choose the TTY of each module, in this way one will be able to distribute the dashboard over more than one terminal.

Thanks for the suggestion though.

**Comment by cyrus-and** [comment]
> Nevertheless, there's a related (planned) feature that will allow to choose the TTY of each module, in this way one will be able to distribute the dashboard over more than one terminal.

[Landed][1]! I'm closing this issue as I'm afraid this is the best we can have right now.

[1]: https://github.com/cyrus-and/gdb-dashboard#display-each-module-in-a-separate-terminal
