### ISSUE TITLE
Add a datastructure browser

### ISSUE THREAD

**Issue by jenstroeger** [cyrus-and/gdb-dashboard#45]
This is a great extension to gdb, thanks!

Have you ever worked with [ddd](https://www.gnu.org/software/ddd/), the Data Display Debugger? It has a very handy feature where data structures are displayed a connected boxes, and I can browse them. Together with gdb's [STL pretty printer](https://sourceware.org/gdb/wiki/STLSupport) this would be a very helpful additional dashboard panel, ncurses style.

Any chance you'd add something like that?

**Comment by cyrus-and** [comment]
Hey thanks!

Yeah I remember DDD, a great tool with an horrible GUI!

That would be very cool actually, I thought about it some time ago, but I'm sure that implementing that graph interface in the terminal would be a quite mess. Nevertheless, there are some successful attempts to perform that kind of visualization in the terminal, notably  [Radare][1], so I guess that maybe there is a chance to find some ready-to-use libraries. But you have to consider that here (in the dashboard) the user interaction is limited, there would be no (easy) way to move the boxes around using mouse or arrows.

I don't plan to attempt to develop such module anytime soon, but if you feel brave enough you could start experimenting with your own custom module, the dashboard [API][2] is quite straightforward.  :) See a minimal example [here][3].

FYI you can already integrate the STL pretty printer as described [here][4].

[1]: http://rada.re/r/img/r2cg.png
[2]: https://github.com/cyrus-and/gdb-dashboard#custom-modules
[3]: https://github.com/cyrus-and/gdb-dashboard#example
[4]: https://github.com/cyrus-and/gdb-dashboard/issues/38#issuecomment-239860413
