### ISSUE TITLE
Error occured in Python command: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by clawoflight** [cyrus-and/gdb-dashboard#46]
I am getting the following error:

     >>> db
     Traceback (most recent call last):
      File "<string>", line 545, in invoke
      File "<string>", line 293, in redisplay
      File "<string>", line 327, in render
    AttributeError: 'dict' object has no attribute 'iteritems'
    Error occurred in Python command: 'dict' object has no attribute 'iteritems'

I don't know what could cause this.

    $ python --version && python2 --version
    Python 3.5.2
    Python 2.7.12
    $ pacman -Qi gdb-dashboard | grep Version
    Version         : 0.1.2-1

    $ cat .gdbinit.d/main
    set auto-load safe-path
    set follow-fork-mode child
    #dashboard -style syntax_highlighting "monokai"

It's worth noting that my process forks, in case that changes anything.

**Comment by cyrus-and** [comment]
I think I know the problem, but can you please run this inside GDB in the meanwhile?

    python import sys; print sys.version

**Comment by clawoflight** [comment]
Wow, that was fast!
Output:

```
>>> python import sys; print sys.version
  File "<string>", line 1
    import sys; print sys.version
                        ^
SyntaxError: invalid syntax
Error while executing Python code.

>>> python import sys; print(sys.version)
3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602]
```

Is your code only compatible with python 2?

**Comment by cyrus-and** [comment]
Nope, but one of the last changes broke the compatibility. The fix is on the way...

**Comment by clawoflight** [comment]
Okay, good to know :)
No need to rush for me, I'm not using this for work right now and don't need it urgently :)

**Comment by cyrus-and** [comment]
Here we go, it should work now, thanks for reporting! :)

Just out of curiosity, what distro are you using?

**Comment by clawoflight** [comment]
Yes, it does, thanks a bunch! :)

Plain Arch Linux :)
In case that's what you are asking about, someone called anthraxx (Levente Polyak) maintains stable and git packages in the [AUR](https://aur.archlinux.org/packages/?K=gdb%2Ddashboard).

**Comment by cyrus-and** [comment]
You're welcome!

Yes that's exactly what I wanted to know, thank you.

**Comment by clawoflight** [comment]
You're welcome :) Arch is great in that respect, there is a package for nearly everything.

**Comment by wuxb45** [comment]
Thanks for the timely fix.
