### ISSUE TITLE
How to print the pretty structure of something like array?

### ISSUE THREAD

**Issue by c02y** [cyrus-and/gdb-dashboard#47]
How can get this:

![gdb-pretty-printing-9b0c4ff4b7e3cfa53505f5ff2febb6783e933fad3c12de2b67b98dbdafbcb8d5](https://cloud.githubusercontent.com/assets/2135996/20436271/33ffa5b2-ad75-11e6-9c5e-e9f531075075.png)

**Comment by cyrus-and** [comment]
I guess you need to write your own [pretty printer][1]. Not related to the dashboard though, a pretty printer can be provided via an esternal `.py` file.

[1]: https://sourceware.org/gdb/onlinedocs/gdb/Writing-a-Pretty_002dPrinter.html
