### ISSUE TITLE
How to reload .gdbinit once modified it?

### ISSUE THREAD

**Issue by c02y** [cyrus-and/gdb-dashboard#48]
How to reload `.gdbinit` once modified it? For example, I add lines or modify the lines in `.gdbinit`, and I want to see the effect, but I don't want to exit-start gdb again, how can I do that inside the current gdb session?

I tried to execute `source ~/.gdbinit` at gdb prompt, the changes will take affect, but the command will output some error message such as:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<string>", line 386, in start
      File "<string>", line 127, in run
    gdb.error: Alias already exists: db
    ~/.gdbinit:1368: Error in sourced command file:
    Error while executing Python code.

**Comment by cyrus-and** [comment]
The point is that you usually don't do that. I maybe could avoid the double initialization, but what's the use case exactly?

**Comment by cyrus-and** [comment]
Yeah, thanks, I can read... The main `.gdbinit` file is not meant to be modified by *users*, so it is not a valid use case. Customization is meant to be achieved by means of external modules/configuration files. If you are maintaining your own version of the dashboard then you're probably savvy enough to figure out what went wrong.
