### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by andrewrk** [cyrus-and/gdb-dashboard#5]
```
Traceback (most recent call last):
  File "<string>", line 180, in <lambda>
  File "<string>", line 191, in on_stop
  File "<string>", line 222, in display
  File "<string>", line 582, in lines
ValueError: invalid literal for int() with base 10: 'file: "/home/andy/dev/lmms/build/src/../../include/AudioDevice.h", line number: 126'
```

line in question:

```c++
		m_sampleRate = _new_sr;
```

**Comment by cyrus-and** [comment]
I would ask you to send me a minimal program to reproduce it, but probably it's easier if you temporarily patch the code to print some debugging info:

    sed -i '569s/$/; print("<--",source,"-->")\n/' .gdbinit

Step until you get that error, scroll the terminal up and copy the line surrounded with `<--` and `-->`.

**Comment by cyrus-and** [comment]
Since in [`AudioDevice.h:126`](https://github.com/LMMS/lmms/blob/98346f7a9a7a7c07e91bdad953229f1ba7523c2e/include/AudioDevice.h#L126) there's an inline method I was hoping to reproduce it in a similar way, but without success. So I cloned and built `lmms` with `-DCMAKE_BUILD_TYPE=Debug`.
Can you tell me how to reproduce your issue?

**Comment by cyrus-and** [comment]
OK, it seems that a similar problem can be reproduced with `gdb lmms -ex 'b Mixer.h:116' -ex r`.

**Comment by cyrus-and** [comment]
Can you please confirm that this is actually fixed?

**Comment by andrewrk** [comment]
Sorry, I should have done better issue reporting. I was neck-deep debugging some issue and I don't remember what I did to cause the issue. If it comes up again I'll include steps to reproduce in the issue.

**Comment by rc0r** [comment]
I ran into that same issue and for me it's fixed.

**Comment by cyrus-and** [comment]
@andrewrk no problem. :)

@rc0r good, thanks!
