### ISSUE TITLE
Cannot write the dashboard: 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)

### ISSUE THREAD

**Issue by cyrus-and** [cyrus-and/gdb-dashboard#50]
From [this][1] comment:

```
Traceback (most recent call last):
File "", line 357, in render
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)
```

GDB 7.7 with Python ~~2.7.4~~ 3.4.0

[1]: https://github.com/cyrus-and/gdb-dashboard/issues/1#issuecomment-263639924

**Comment by cyrus-and** [comment]
@mohit3112 are you able to identify which is the module that causes this error? You can figure this out by disabling all modules then enabling one at a time.

Also, what is it supposed to print?

Thank you.

**Comment by mohit3112** [comment]
@cyrus-and 
i don't think it's specific to module , i enabled assembly module only disabled all other still getting this error

**Comment by mohit3112** [comment]
@cyrus-and  

ok so i just did following 
```
import platform 
print(platform.python_version())
```
to check the version of python used , out put is 3.4.0 

but when i do python --version , i get 2.7.4

**Comment by cyrus-and** [comment]
OK, good to know, the Python version used by GDB may be different from the system-wide version.

**Comment by cyrus-and** [comment]
Does this happen with **every** file you are trying to debug?

For example try the following:

```
$ gdb $(which sleep)
>>> run 100
(press Ctrl-C)
```

You should see the dahboard.

**Comment by mohit3112** [comment]
@cyrus-and  
yes this works problem is when i use 

dashboard -output <tty>

it's gives error

**Comment by cyrus-and** [comment]
Oh, I see, I can reproduce that now.

**Comment by cyrus-and** [comment]
Can you try to run:

```sh
python -c "import sys; print(sys.stdout.encoding)"
```

in your shell where you usually run GDB and get the error?

**Comment by mohit3112** [comment]
first one gives : UTF-8
second one gives : en_IN

**Comment by cyrus-and** [comment]
I can only reproduce your issue on a machine where the locale is set to `C`, basically no locale, but I'm able to fix the behavior by exporting the UTF-8 variant before starting GDB, in my case:

```sh
export LC_CTYPE=C.UTF-8
```

For example:

```sh
$ gdb -nx -ex 'python with open("/dev/null") as f: print(f.encoding)' -ex quit
ANSI_X3.4-1968
$ export LC_CTYPE=C.UTF-8
$ gdb -nx -ex 'python with open("/dev/null") as f: print(f.encoding)' -ex quit
UTF-8
```

Can you try to run:

```sh
gdb -nx -ex 'python with open("/dev/null") as f: print(f.encoding)' -ex quit
```

**Comment by mohit3112** [comment]
yep i got ANSI_X3.4-1968, i tried to export LC_CTYPE=C.UTF-8 and it worked !!

**Comment by cyrus-and** [comment]
Good! Now, I'm not sure whether this is a thing I should fix myself or not, to my knowledge Python falls back to that encoding when it cannot figure out the proper encoding from the environment, so probably you're experiencing this because your setup is not UTF-8-ready...

Anyway, you can use an alias, in your `.bashrc` or whatever so you don't have to export it every time, plus in this way it will only affect GDB:

```sh
alias gdb='LC_CTYPE=C.UTF-8 gdb'
```

I'm closing this for now. Thanks for your patience!
