### ISSUE TITLE
Fixes for MS Windows

### ISSUE THREAD

**Issue by vburdo** [cyrus-and/gdb-dashboard#52]
Hi,

Here is small patch to make dashboard working in MS Windows.
Issues fixed:
1. excluded imports not available in Windows
2. style map updated to exclude UTF-8 chars - Windows console dont support them.
3. implemented Windows-specific terminal width calculation. Algorithm is like this:
3.1 try to use ANSICON env variable - it contains necessary values
3.2 pipe "mode con:" command - it outputs term width/height
3.3 try use LINES and COLUMNS env vars if available
3.4 fall back to 80x25

Windows console does not support ANSI control sequences directly, but there is ANSICON utility which fixes this. You can get it here: https://github.com/adoxa/ansicon

[patch.zip](https://github.com/cyrus-and/gdb-dashboard/files/636723/patch.zip)

**Comment by cyrus-and** [comment]
I'll need to find a Windows machine in order to properly try this out. Thank you!

**Comment by vburdo** [comment]
>I'll need to find a Windows machine in order to properly try this out. Thank you!
Get VirtualBox and some Windows VM image :)
If you need GDB binaries w/ Python support - I have them

**Comment by cyrus-and** [comment]
That's surely an option. I'll get back to you if I need them, thanks!

**Comment by cyrus-and** [comment]
Fixed in e3a3d68ceb9a094b6690fcabe2edc3960d66313d.
