### ISSUE TITLE
Strange highlighting

### ISSUE THREAD

**Issue by oblitum** [cyrus-and/gdb-dashboard#53]
I just noticed this strange highlighting behaviour while providing [this sample code on reddit](https://www.reddit.com/r/cpp/comments/5qu8fr/a_guide_to_porting_c_and_c_code_to_rust/dd40vau/?context=2):

```c++
#include <memory>
#include <future>

int main() {
    using namespace std;

    auto foo = make_unique<int>(42);

    auto inc1 = async(launch::async, [foo = move(foo)] { (*foo)++; });

    // ...

    auto inc2 = async(launch::async, [foo = move(foo)] { (*foo)++; });
}
```

I was checking how gdb would behave on segfault. The c++ sample was compiled with `g++ -g3 -O0 -std=c++14 -Wall -Wextra -pedantic -lpthread sample.cpp -o sample`.

Running `gdb ./sample` + `>>> r` gives:

![screenshot from 2017-01-30 18-55-31](https://cloud.githubusercontent.com/assets/1269815/22441358/37d1b044-e71e-11e6-823b-0a2214e033c0.png)
Notice how `mov    DWORD PTR [rax],edx` is not correctly highlighted.

My custom gdb-dashboard initialization is:

```
set disassembly-flavor intel
dashboard -style syntax_highlighting "algol_nu"

define hookpost-up
dashboard
end

define hookpost-down
dashboard
end
```

**Comment by cyrus-and** [comment]
I'm unable to reproduce this issue, does it happen reliably to you?

Also, start GDB (with and without the `-q` flag) and paste the following:

```python
python
import pygments.lexers
import pygments.formatters
formatter_class = pygments.formatters.Terminal256Formatter
formatter = formatter_class(style='algol_nu')
lexer = pygments.lexers.get_lexer_for_filename('.asm')
source = 'mov\tDWORD PTR [rax],edx'
print(pygments.highlight(source, lexer, formatter))
end
```

Is the line correctly highlighted in this way?

**Comment by oblitum** [comment]
Same problem...

![screenshot from 2017-02-01 13-41-22](https://cloud.githubusercontent.com/assets/1269815/22513871/ad8b1a52-e884-11e6-8e1a-ea79a040d15f.png)

**Comment by oblitum** [comment]
For notice, I'm on pygments 2.2.0-1 on ArchLinux.

**Comment by oblitum** [comment]
Executing your sample from a python file gives the same, it's just a pygments issue.

**Comment by oblitum** [comment]
Thanks ;)

**Comment by cyrus-and** [comment]
Oh great, you're welcome!

**Comment by oblitum** [comment]
Reported at https://bitbucket.org/birkenfeld/pygments-main/issues/1326/intel-flavor-assembly-asm-highlighting.

**Comment by cyrus-and** [comment]
Finally fixed, the problem was in how the lexer was chosen. (See the [Pygments][1] issue.)

[1]: https://bitbucket.org/birkenfeld/pygments-main/issues/1326/intel-flavor-assembly-asm-highlighting
