### ISSUE TITLE
Interferes with QtCreator

### ISSUE THREAD

**Issue by Asalle** [cyrus-and/gdb-dashboard#54]
Hi there, 
first of all, thank for such an awesome tool, I  use it everyday and it saves my life :)

Problem report:
Qt Creator 4.1.0 (Qt 5.7) 64b cannot debug any external app with gdb-dashboard's .gdbinit. It crashes with an error 
`*** UNEXPECTED STATE TRANSITION:  Debugger::Internal::GdbPlainEngine(0x449b1a0, name = "GdbEngine") "State changed from EngineSetupRequested(1) to EngineShutdownRequested(20)`. 
Qt's UI said `The gdb process terminated`. After removal of .gdbinit everything worked as expected.
The same was reproduced with Qt Creator 3.0.1 (Qt 5.2.1).

**Comment by cyrus-and** [comment]
> first of all, thank for such an awesome tool, I use it everyday and it saves my life :)

So glad to hear that! :)

I'm not a QtCreator user myself (just giving it a try right now), but the point is that it uses GDB via the [gdb/mi][1] interface (`gdb -i mi`):

>  It is specifically intended to support the development of systems which use the debugger as just one small component of a larger system.

That is, a kind of alternative REPL interface where commands and replies have a strict format so to be easily parsable from third-party programs which want to use GDB as a pure debugging backend.

I don't know exactly the cause of the error but it's clear that the dashboard is not compatible with that mode.

I noticed that QtCreator has an option (Tools -> Options -> Debugger -> GDB -> Load .gdbinit file on startup) which you can use to prevent the loading of the `.gdbinit` file.

Do you think it can be reasonable?

Obviously in this way you'll also lose the ability to load additional init files via the [`.gdbinit.d`][2] directory, but it kind of makes sense IMHO; you can always add additional init files to QtCreator by adding "Extra Debugging Helpers" in the same option pane.

[1]: https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html
[2]: https://github.com/cyrus-and/gdb-dashboard#configuration

**Comment by Asalle** [comment]
Thanks, I don't use `.gdbinit.d`, so this solution totally works for me. I think this issue can be mentioned in some kind of wiki to prevent future issues of the same problem?

**Comment by cyrus-and** [comment]
You're right, I'll mention this [here][1], thanks for the suggestion!

[1]: https://github.com/cyrus-and/gdb-dashboard#additional-gdb-front-ends

**Comment by cyrus-and** [comment]
Just noticed/remembered that someone (#19) already had this issue with QtCreator.
