### ISSUE TITLE
Stack/Source does not changes , when using Up/Down

### ISSUE THREAD

**Issue by SachinSetiya** [cyrus-and/gdb-dashboard#55]
Hi,

While using up or down from gdb Source/stack shown in dashboard does not changes.

Regards
sachin

**Comment by cyrus-and** [comment]
`up` and `down` don't trigger a dashboard refresh, you have to either redraw the dashboard manually with the `dashboard` command or define some [hooks][1]:

```
define hookpost-up
dashboard
end

define hookpost-down
dashboard
end
```

Have you tried any of this?

[1]: https://github.com/cyrus-and/gdb-dashboard#dashboard--enabled-onoff

**Comment by SachinSetiya** [comment]
Tried , And it worked. Thanks!!!!!

**Comment by jason-assc** [comment]
why would you ever not want the display to refresh on a stack change?
