### ISSUE TITLE
Center the output of Source around current gdb line

### ISSUE THREAD

**Issue by phcerdan** [cyrus-and/gdb-dashboard#58]
In `dashboard source -style context X` the code is not centered around the current line of gdb (`info line`). If X is big enough (relative to the size of the terminal), you can even miss the current gdb line without scrolling.

**Comment by cyrus-and** [comment]
The current line should always be centered with respect to the height of the source module (which as you said can be greater than the size of the terminal) provided that there are enough code lines to display in both the directions, i.e., not if the current line is in the first/last X lines. If you're not referring to this behavior then please provide an example.

As you can see, this is somewhat related to #51.

**Comment by phcerdan** [comment]
My Source output is a terminal in a tmux pane. Using the default `dashboard source -style context 5`, it is good and centered in the terminal. If I use a value big enough, say from 30 to 1000, I only see the last 30 lines of the file. I can still scroll in the tmux pane though, but not the best behavior.

I can reproduce it if I once I hit a breakpoint. I write `dashboard source -style context 40`, then my Source terminal is refreshed, but the current line is not centered anymore.

**Comment by cyrus-and** [comment]
As far I can tell this is the intended behavior, the source module is currently unaware of the height of the terminal so it simply displays X lines before and after the current line.

> I can reproduce it if once I hit a breakpoint I type dashboard source -style context 40, then my Source terminal is refreshed, but the current line is not centered anymore.

That's probably because your terminal is shorter than 40+40 lines.

**Comment by phcerdan** [comment]
All good then, I will keep an eye on #51
