### ISSUE TITLE
Dashboard crashes with MIPS target

### ISSUE THREAD

**Issue by unwiredben** [cyrus-and/gdb-dashboard#6]
When using this with a MIPS remote target, I get this crash at connect time

```
Traceback (most recent call last):
  File "<string>", line 180, in <lambda>
  File "<string>", line 191, in on_stop
  File "<string>", line 222, in display
  File "<string>", line 952, in lines
```

I think the problem is for MIPS, `info registers` gives you the output

```
>>> info registers
          zero       at       v0       v1       a0       a1       a2       a3
 R0   00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
            t0       t1       t2       t3       t4       t5       t6       t7
 R8   00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
            s0       s1       s2       s3       s4       s5       s6       s7
 R16  00536b28 7e3697b4 00531d74 00000000 7e369a9d 7e3694eb 00000008 7e3694e6 
            t8       t9       k0       k1       gp       sp       s8       ra
 R24  00000000 00000000 00000000 00000000 00000000 78fabf60 7e3694f0 00000000 
        status       lo       hi badvaddr    cause       pc
      01000013 cf24a617 0013b819 004734a0 00802420 30eea250 
          fcsr      fir      hi1      lo1      hi2      lo2      hi3      lo3
      00000000 01739700 00000000 00000000 00000000 00000000 00000000 00000000 
        dspctl  restart
      00000000 00000000 
```

which is a special format that's just for MIPS, defined in gdb/mips-tdep.c.

**Comment by cyrus-and** [comment]
Oh yes, definitely, that's the problem. Let me see if I can find a reliable way to fetch registers from GDB without hard coding their names.

**Comment by unwiredben** [comment]
I didn't see any flags in the GDB code that would change the "info registers" output.  Even the one-register output was slightly different on MIPS between integer and FP registers :(

**Comment by cyrus-and** [comment]
Yep, no flags. There is also `info all-registers` but even assuming to be able to parse all the register names in a reliable way the problem would become how to distinguish regular registers from floating-point and vector registers.

I was also thinking about the [Python API](https://sourceware.org/gdb/onlinedocs/gdb/Frames-In-Python.html) but it seems it is only possible to fetch registers by name.

-

FYI, in the meantime you can disable that module to get rid of that error.

**Comment by unwiredben** [comment]
Good advice.  info all-registers uses the same format (except inserting the FP registers with a different format in the middle), so it's out.  This seems like a good argument for a gdb patch to make that output more universal or to add an option for info registers to force the generic form.

**Comment by cyrus-and** [comment]
> This seems like a good argument for a gdb patch to make that output more universal or to add an option for info registers to force the generic form.

I totally agree with you!

**Comment by cyrus-and** [comment]
A small step forward... the GDB command (mind the trailing space):

    complete info registers 

In this way we would have at least *all* the registers names, alas including floating-point and vector registers and with some redundancy too, e.g., both `eax` and `rax` on `x86-64`.

Sadly this has been introduced only quite recently; somewhere between GDB 7.8 and 7.10 (inclusive).

**Comment by cyrus-and** [comment]
460cf28c3fd898159510cc610d6c2a7c57c34247:

> `dashboard registers -style list` defaults to show all the registers as provided
by GDB. This setting is not meant to be interactively manipulated, rather it can
be specified just once in a per-project `.gdbinit` or `~/.gdbinit.d/init` files,
only when needed.
