### ISSUE TITLE
Add style option to print stack arguments on a single line

### ISSUE THREAD

**Issue by cirosantilli** [cyrus-and/gdb-dashboard#60]
Much like the default backtrace, but with your pretty highlight.

If line would be too long, cut it off.

One arg per line overflows terminal height too easily, and is easily doable with `i args`.

**Comment by cyrus-and** [comment]
Yeah, this makes sense. I don't agree on cutting off long lines though; it would give precedence to some entries over others, I would let the line wraps instead.

The fix is on the way, thanks for the suggestion!

**Comment by cyrus-and** [comment]
Here it is, the style attribute is `compact` and it's disabled by default:

    dashboard stack -style compact True

**Comment by cirosantilli** [comment]
:rocket:
