### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)

### ISSUE THREAD

**Issue by noidwasavailable** [cyrus-and/gdb-dashboard#61]
I opened two tmux panes and tried using 
dashboard -output /dev/pts/3
but then it showed me an error 
Cannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 357, in render
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)
what is wrong with it?

**Comment by noidwasavailable** [comment]
basically my error seems to be the same as one of the threads already closed, about UTF-8 and stuff.
I tried the solution posted in there too, by trying 
export LC_CTYPE=C.UTF-8
but then even after that, I get
ANSI_X3.4-1968
as output for 
gdb -nx -ex 'python with open("/dev/null") as f: print(f.encoding)' -ex quit

What do I do now?

**Comment by cyrus-and** [comment]
Do you have the same problem if you try the same with two terminal windows instead of two tmux panes?

Just to make sure you did right, `export LC_CTYPE=C.UTF-8` must be run in the pane/terminal where you run GDB not where you want to send the output.

**Comment by cyrus-and** [comment]
(For completeness the other related issue is: #50)

**Comment by noidwasavailable** [comment]
I ran 
`$ python -c "import sys; print(sys.stdout.encoding)"`
and got 
`ANSI_X3.4-1968`

and for
`$echo $LANG`
I get 
`en_US.UTF-8`

then I did 
`
$ gdb -nx -ex 'python with open("/dev/null") as f: print(f.encoding)' -ex quit`
`ANSI_X3.4-1968`
`$ export LC_CTYPE=C.UTF-8`
`$ gdb -nx -ex 'python with open("/dev/null") as f: print(f.encoding)' -ex quit`
`ANSI_X3.4-1968
`

Apparently my pyhton is version Python 2.7.6 
and GDB is GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1


I tried setting output to another window too, (Ctrl + B C) and I got the same answer.

**Comment by cyrus-and** [comment]
> I tried setting output to another window too, (Ctrl + B C) and I got the same error.

No I meant another terminal, without tmux.

**Comment by noidwasavailable** [comment]
Yeap, I just tried doing the same thing for 2 PuTTy windows open and I got the same error.

**Comment by cyrus-and** [comment]
I think it's a problem with your environment, I mean the point is to have `UTF-8` as a result of `python -c "import sys; print(sys.stdout.encoding)"`. AFAIK `ANSI_X3.4-1968` is used by Python as a fallback encoding when it's unable to recognize the value in `LC_CTYPE`, e.g.:

```console
$ export LC_CTYPE=nope
$ python -c "import sys; print(sys.stdout.encoding)"
ANSI_X3.4-1968
```

**Comment by noidwasavailable** [comment]
Okay, thank you. I will check with the machine admins if there's a way to help it. 
I'll comment if it's solved.

**Comment by cyrus-and** [comment]
Here's another thing you can try:

    export PYTHONIOENCODING=utf8

I'm sorry if I'm shooting in the dark here, the way Python handles the encoding is a mess IMHO.

**Comment by noidwasavailable** [comment]
oh I think it works, because after doing that, I tried
` python -c "import sys; print(sys.stdout.encoding)"`
and got
`utf8`

**Comment by cyrus-and** [comment]
Yeah but it seems it would print any string you write:

```console
$ export PYTHONIOENCODING="any string you write"
$ python -c "import sys; print(sys.stdout.encoding)"
any string you write
```

Give the dashboard a try...

**Comment by noidwasavailable** [comment]
Unfortunately, I don't think it changed for GDB because I still got the same error and when I tried
`gdb -nx -ex 'python with open("/dev/null") as f: print(f.encoding)' -ex quit`
it still gave me `ANSI_X3.4-1968`

**Comment by noidwasavailable** [comment]
hmm yeap, I got "anything you write"

**Comment by noidwasavailable** [comment]
but then after I changed it to "any string you write"
`gdb -nx -ex 'python with open("/dev/null") as f: print(f.encoding)' -ex quit`
does not work.
It says:
Fatal Python error: Py_Initialize: can't initialize sys standard streams
LookupError: unknown encoding: any string you write
Aborted (core dumped)

**Comment by noidwasavailable** [comment]
I tried using `export LC_ALL=C.UTF-8`
and `gdb -nx -ex 'python with open("/dev/null") as f: print(f.encoding)' -ex quit`
finally gave me UTF-8
but the dashboard will still not display in another terminal.

**Comment by noidwasavailable** [comment]
Update:
I did `export LC_ALL=C.UTF-8` in both terminals open
and now it works. Is there any way that I don't have to do this every time?

**Comment by cyrus-and** [comment]
Good find! Thanks for your patience.

> Is there any way that I don't have to do this every time?

Yes, you can put `export LC_ALL=C.UTF-8` in your `~/.bashrc` (I'm assuming your're using bash here), next instances will have the variable exported by default.
