### ISSUE TITLE
how to debug shared lib

### ISSUE THREAD

**Issue by forestlei** [cyrus-and/gdb-dashboard#62]

**Comment by cyrus-and** [comment]
As you normally would using GDB alone, the dashboard does not alter the debugging workflow.

Anyway, assuming that the shared library is compiled with debugging information you can just *step into* its exported functions when you debug a program that has been linked against it. Take a look at the following example.

```console
$ gcc -g -shared -fPIC lib.c -o liblib.so
$ gcc -g -c main.c
$ gcc main.o -L. -llib -o main
$ LD_LIBRARY_PATH=. gdb ./main
```

#### lib.h

```c
#pragma once
void foo(int x);
```

#### lib.c

```c
#include <stdio.h>

void foo(int x)
{
    while (x-- > 0) {
        printf("foo %i\n", x);
    }
}
```

#### main.c

```c
#include "lib.h"

int main()
{
    foo(5);
}
```
