### ISSUE TITLE
Wrongly displayed offsets in disassembly

### ISSUE THREAD

**Issue by 10110111** [cyrus-and/gdb-dashboard#68]
When I debug a 32-bit application (with 32-bit GDB 8.0.50.20170709-git, if this matters), I get the following disassembly view:
```
─── Assembly ─────────────────────────────────────────────
0xf7ff2ab0 _dl_runtime_resolve+-18446744069414584320 push   eax
0xf7ff2ab1 _dl_runtime_resolve+-18446744069414584319 push   ecx
0xf7ff2ab2 _dl_runtime_resolve+-18446744069414584318 push   edx
0xf7ff2ab3 _dl_runtime_resolve+-18446744069414584317 mov    edx,DWORD PTR [esp+0x10]
0xf7ff2ab7 _dl_runtime_resolve+-18446744069414584313 mov    eax,DWORD PTR [esp+0xc]
```
Obviously the offsets are wrong (well, techically somewhat right, but very weird, especially for a 32-bit app). Here's what they should actually look like:
```
>>> x/5i $pc
=> 0xf7ff2ab1 <_dl_runtime_resolve+1>:  push   ecx
   0xf7ff2ab2 <_dl_runtime_resolve+2>:  push   edx
   0xf7ff2ab3 <_dl_runtime_resolve+3>:  mov    edx,DWORD PTR [esp+0x10]
   0xf7ff2ab7 <_dl_runtime_resolve+7>:  mov    eax,DWORD PTR [esp+0xc]
   0xf7ff2abb <_dl_runtime_resolve+11>: call   0xf7fec030 <_dl_fixup>
```

**Comment by cyrus-and** [comment]
Hey thanks for reporting. I think they are just wrong, it's not a matter of representation or integer sizes, that values are computed by Python using memory offsets obtained by GDB; either the instruction offsets or the function base address are wrong here.

Can you provide a simple way to reproduce that?

**Comment by 10110111** [comment]
```
g++ -g -o test -x c++ - <<< $'#include <stdio.h>\nint main() { printf("test\\n"); }'
gdb -ex start -ex 'si 10' ./test
```
If after `si 10` you still aren't inside `_dl_runtime_resolve`, make sure you don't have `LD_BIND_NOW` env var set and try stepping further.

**Comment by cyrus-and** [comment]
I cannot reproduce it using a 64 bit box, not even with `-m32`. In the former case offsets are correct, in the latter are not computed because the function base offset cannot be resolved (for whatever reason).

It would be awesome if you could patch the dashboard and show me the output when this problem happens:

```diff
diff --git a/.gdbinit b/.gdbinit
index abd4490..613dcec 100644
--- a/.gdbinit
+++ b/.gdbinit
@@ -906,6 +906,7 @@ instructions constituting the current statement are marked, if available."""
                 if func_start:
                     max_offset = len(str(asm[-1]['addr'] - func_start))
                     offset = str(addr - func_start).ljust(max_offset)
+                    print(addr, func_start)
                     func_info = '{}+{} '.format(frame.name(), offset)
                 else:
                     func_info = '? '
```

**Comment by cyrus-and** [comment]
Anyway in both cases the instruction offsets are correct, so it must be the function base offset which is returned by GDB, but contains a wrong value.

**Comment by 10110111** [comment]
I guess by "the output" you mean `Output/messages` pane:
```
─── Output/messages ────────────────────
(4160694960L, 18446744073575279280L)
(4160694961L, 18446744073575279280L)
(4160694962L, 18446744073575279280L)
(4160694963L, 18446744073575279280L)
(4160694967L, 18446744073575279280L)
(4160694971L, 18446744073575279280L)
(4160694976L, 18446744073575279280L)
```

**Comment by cyrus-and** [comment]
Yeah, for some reason the high order 32 bit of `func_start` are `0xffffffff` while should be zero.

```
hex(18446744073575279280) 0xfffffffff7ff2ab0
hex(4160694960)                   0xf7ff2ab0
```

Possible culprit is `to_unsigned` but I cannot reproduce with 64bit GDB.

```python
def to_unsigned(value, size=8):
    # values from GDB can be used transparently but are not suitable for
    # being printed as unsigned integers, so a conversion is needed
    return int(value.cast(gdb.Value(0).type)) % (2 ** (size * 8))
```

**Comment by 10110111** [comment]
I think the problem is that Python's `int` is 32-bit on 32-bit system. If I change `Value(0)` to `Value(0L)` and `int` to `long` in the `to_unsigned` function, then it works as it should.

**Comment by cyrus-and** [comment]
Awesome, you're right! Just tried on a 32-bit system. Patch is on the way, thank you so much. :)

**Comment by cyrus-and** [comment]
It should work now, can you confirm?

**Comment by 10110111** [comment]
Yeah, works correctly now.
