### ISSUE TITLE
AttributeError: 'gdb.Frame' object has no attribute 'architecture'

### ISSUE THREAD

**Issue by viveksubbarao** [cyrus-and/gdb-dashboard#69]
I am getting the following error when I try to run dashboard

Cannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 354, in render
  File "<string>", line 847, in lines
AttributeError: 'gdb.Frame' object has no attribute 'architecture'

~ @viveksrao-bgp-ll-peering-all-0.sjc% gdb -v
GNU gdb (GDB) 8.0
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

I looked at Frame.py in data_directory and it does not seem to have the architecture method. Pls help.

**Comment by cyrus-and** [comment]
Try running GDB without any `.gdbinit` file, debug any executable, place a breakpoint, run, then run the following GDB command:

```
(gdb) python print(gdb.selected_frame().architecture().name())
i386:x86-64
```

If you gen an error then maybe your GDB has not been properly compiled with the python support?

>  I looked at Frame.py in data_directory and it does not seem to have the architecture method.

What is "data_directory"? AFAIK the implementation of `.architecture()` is in [`py-frame.c`][1].

[1]: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=gdb/python/py-frame.c;h=891f44e708fd7a4d9ba82325da7f7c8e38f27f07;hb=HEAD#l177

**Comment by viveksubbarao** [comment]
(gdb) python print(gdb.selected_frame().architecture().name())
i386
(gdb)

**Comment by cyrus-and** [comment]
And it works, which is quite strange because the backtrace of your first post complains about that, can you tell me more about your environment? Did you build GDB yourself, fetched from your distro's repos? If that's the case what distro?

**Comment by viveksubbarao** [comment]
Yes, I built gdb on my system.

My environment:
Linux kernel 3.18, fedora core 18, x86_64

gdb --config
This GDB was configured as follows:
   configure --host=i686-pc-linux-gnu --target=i686-pc-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --without-expat
             --with-gdb-datadir=/home/viveksrao/bin/gdb/share/gdb (relocatable)
             --with-jit-reader-dir=/home/viveksrao/bin/gdb/lib/gdb (relocatable)
             --without-libunwind-ia64
             --without-lzma
             --with-python=/usr
             --without-guile
             --with-separate-debug-dir=/home/viveksrao/bin/gdb/lib/debug (relocatable)
             --without-babeltrace

("Relocatable" means the directory can be moved with the GDB installation
tree, and GDB will still find it.)

**Comment by cyrus-and** [comment]
I've just tried with:

    ./configure --with-python=/usr/bin/python3.5 --prefix=/opt/gdb-8.0_python-3.5 --with-gdb-datadir=/tmp/xxx

with my Debian system and everything works fine, the `--with-gdb-datadir` seems to not impact the Python behavior (at least not for what concerns this issue), I think there's something wrong with your environment and I'm afraid I cannot help you further with this. Feel free to provide more details if you want.
