### ISSUE TITLE
Wrong offsets in disassembly when two symbols have the same name in different modules

### ISSUE THREAD

**Issue by 10110111** [cyrus-and/gdb-dashboard#70]
I can reproduce this on a 32-bit system, with some symbols like `_start` and `main` present in `/bin/true` using the following command:
```
gdb /bin/true -ex 'source ~/src/gdb-dashboard/.gdbinit' -ex 'b *0' -ex r -ex 'd 1' -ex 'dashboard -layout assembly' -ex 'dashboard -enabled on' -ex 'x/2i $pc' -ex 'p &_start'
```
I have the following output from it:
```
─── Assembly ─────────────────────────────
0xf7fdd800 _start+4026093216 mov    eax,esp
0xf7fdd802 _start+4026093218 call   0xf7fe2160 <_dl_start>
───────────────────────────────────────
=> 0xf7fdd800 <_start>: mov    eax,esp
   0xf7fdd802 <_start+2>:       call   0xf7fe2160 <_dl_start>
$1 = (<text variable, no debug info> *) 0x8048960 <_start>
```
As you can see, disassembly in dashboard has `_start+4026093216`, while disassembly from `x/2i` prints `_start` without large offsets. Then, `p &_start` confirms that there are at least two different symbols with this name, of which GDB picks not the one we want.

Looking in the Symbols dialog in EDB debugger, I find that one of the symbols is `true!_start`, and another is `ld-2.14.1.so!_start`.

**Comment by 10110111** [comment]
If your `/bin/true` is stripped, you can reproduce this with a simple program made like this:
```
gcc -x c -o test - <<< 'int main(){return 0;}'
```

**Comment by cyrus-and** [comment]
Yes, I see, I'm fetching the function offset with `gdb.parse_and_eval(frame.name()).address`, thus by using the name only, I don't know if there is a way/syntax to disambiguate. I'll look into this, thanks for reporting.

**Comment by cyrus-and** [comment]
A simpler way to reproduce this without the dashboard:

```console
$ gcc -x c -o test - <<<'int main(){}'
$ gdb -q --batch test -ex 'b *0' -ex r -ex disassemble -ex 'p &_start'
$ gdb -q --batch test -ex 'b _start' -ex r -ex disassemble -ex 'p &_start'
```

In the former case there's the the difference in address (`0xb7fdba20` vs `0x80482e0`):

```
$ gdb -q --batch test -ex 'b *0' -ex r -ex disassemble -ex 'p &_start'
Breakpoint 1 at 0x0
Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x0

Dump of assembler code for function _start:
=> 0xb7fdba20 <+0>:     mov    %esp,%eax
   0xb7fdba22 <+2>:     call   0xb7fdc5c0 <_dl_start>
End of assembler dump.
$1 = (<text variable, no debug info> *) 0x80482e0 <_start>
```

In short `b *0` (an hackish way to stop at the *first instruction*) makes the program stop in a place that is different from the `_start` symbol, yet it has the same name...

**Comment by 10110111** [comment]
A cleaner way to stop at the first instruction with modern GDB is to use the `starti` command.

**Comment by cyrus-and** [comment]
Yes, I cannot try right now but I guess the outcome will be the same.

**Comment by cyrus-and** [comment]
[Upstream issue][1].

[1]: https://sourceware.org/ml/gdb/2019-08/msg00035.html

**Comment by cyrus-and** [comment]
Well a3b8c3b7be814af7eef82698b9bc737cee345a6c is a possible solution, at least for now...
