### ISSUE TITLE
Show breakpoints

### ISSUE THREAD

**Issue by aoyama-val** [cyrus-and/gdb-dashboard#74]
Hi,
Thank you for amazing tool!

Wouldn't it be nice if breakpoints are shown in the Source module just like TUI?
Instead of displaying sideways, changing the style of line numbers might be enough (to save display space).
![gdb](https://user-images.githubusercontent.com/13144822/28749950-d14a7c3c-7513-11e7-8809-8d8e6744f975.png)

**Comment by cyrus-and** [comment]
Thanks to you for your interest! :)

Yes, it certainly would, but last time I checked, the Python API didn't provide all the needed features to properly implement this. And I don't really feel like parsing the output of `info breakpoints` (as it happens in #30).

**Comment by aoyama-val** [comment]
I understand, but that's too bad. I'm going to merge the PR and use it for myself... Thanks.

**Comment by tromey** [comment]
> the Python API didn't provide all the needed features

This is https://sourceware.org/bugzilla/show_bug.cgi?id=18385.

In my case what I did is get a breakpoint's linespec and then re-parse it using `gdb.decode_line`.  I think this can fail to work sometimes (hence the bug report) but I no longer remember under what conditions.
