### ISSUE TITLE
Assembly window resizes if there are not enough instructions to fill the context

### ISSUE THREAD

**Issue by javier-cabezas** [cyrus-and/gdb-dashboard#76]
IMO, windows that show a fixed amount of information should have a fixed size to avoid distractions due to window resizing (which may change the location of other modules).

This is the case of the assembly window, that keeps resizing if there are not enough instructions to fill the context before or after the current line.

I have a fix that adds leading/trailing blank lines as needed: https://github.com/javier-cabezas/gdb-dashboard/commit/719bcc0e487cb9326b3b6b5c8077d5439509c63b

**Comment by cyrus-and** [comment]
The context in the assembly module (as well as in the source module) is not meant to be the module height but the lines around the IP, think of it as `grep --context=<n>`.

Anyway, I see your point but this would be just a temporary fix, I'm planning to rewrite the layout algorithm so to allow modules to fully take advantage of the available space. I'll postpone this issue until then.

Thanks for your suggestion though, modules that don't move around definitely make sense.

**Comment by hao-lh** [comment]
I also have this issue as now I have stack window just below source, and due to window resize, I have to move my eye up and down.
Looking forward to this feature and many thanks!
