### ISSUE TITLE
It didn't work on /dev/pts

### ISSUE THREAD

**Issue by IceAmber** [cyrus-and/gdb-dashboard#77]
the name of TTY is
`iceamber@localhost:~ $ tty
/dev/pts/3
`
and then I run the command below, and nothing happened.
`>>> dashboard -output /dev/pts/3`

**Comment by cyrus-and** [comment]
Try to set a breakpoint and run the program.

**Comment by IceAmber** [comment]
sorry, I didn't run the program. and it worked after ran the program

**Comment by IceAmber** [comment]
another question, the expressions didn't work.
`─── Assembly ───────────────────────────────────────────────────────────────────────────────────────────
0x00000000004005a1 Print+59 mov    $0x4006b4,%edi
0x00000000004005a6 Print+64 mov    $0x0,%eax
0x00000000004005ab Print+69 callq  0x400450 <printf@plt>
0x00000000004005b0 Print+74 addl   $0x1,-0x4(%rbp)
0x00000000004005b4 Print+78 mov    -0x4(%rbp),%eax
0x00000000004005b7 Print+81 cmp    -0x14(%rbp),%eax
0x00000000004005ba Print+84 jl     0x400585 <Print+31>
─── Expressions ────────────────────────────────────────────────────────────────────────────────────────
─── History ────────────────────────────────────────────────────────────────────────────────────────────
$$1 = {[0] = 0x4006bc "hello", [1] = 0x4006c2 "just a test"}
$$0 = 0x4006c2 "just a test"
─── Memory ─────────────────────────────────────────────────────────────────────────────────────────────
─── Registers ──────────────────────────────────────────────────────────────────────────────────────────
   rax 0x000000000000000f    rbx 0x0000000000000000    rcx 0x000000007ffffff1    rdx 0x00007ffff7dd6760
   rsi 0x0000000000000001    rdi 0x0000000000000000    rbp 0x00007fffffffdbc0    rsp 0x00007fffffffdba0
    r8 0x0000000000000000     r9 0x000000000000000f    r10 0x000000000000000b    r11 0x0000000000000246
   r12 0x0000000000400480    r13 0x0000000000000000    r14 0x0000000000000000    r15 0x0000000000000000
   rip 0x00000000004005b0 eflags [ IF ]                 cs 0x00000033             ss 0x0000002b        
    ds 0x00000000             es 0x00000000             fs 0x00000000             gs 0x00000000        
─── Source ─────────────────────────────────────────────────────────────────────────────────────────────
 3 
 4 void Print(int count, char *data[])
 5 {
 6 	int i = 0;
 7 
 8 	for(i = 0; i < count; i ++)
 9 		printf("%d		%s\n", i, data[i]);
10 }
11 
12 void main()
13 {	
─── Stack ──────────────────────────────────────────────────────────────────────────────────────────────
[0] from 0x00000000004005b0 in Print+74 at test.c:8
arg count = 2
arg data = 0x7fffffffdbe0
[1] from 0x0000000000400605 in main+70 at test.c:22
(no arguments)
─── Threads ────────────────────────────────────────────────────────────────────────────────────────────
[1] id 1279 name test from 0x00000000004005b0 in Print+74 at test.c:8
────────────────────────────────────────────────────────────────────────────────────────────────────────
8		for(i = 0; i < count; i ++)
>>> 
`

**Comment by cyrus-and** [comment]
> another question, the expressions didn't work.

Care to elaborate? What do you expect?

**Comment by IceAmber** [comment]
just print the value of variable, as the picture shows at readme.

**Comment by cyrus-and** [comment]
You have to specify the expression, see `help dashboard expressions`:

    dashboard expressions watch foo + 42

**Comment by IceAmber** [comment]
well, I see. Thank you very mach
