### ISSUE TITLE
cannot add simple permanent settings

### ISSUE THREAD

**Issue by volviq** [cyrus-and/gdb-dashboard#78]
i wanted to add an additional simple configuration file: ~/.gdbinit.d/init
with the content:
```
set logging file ~/gdb/gdb.log
set logging redirect on
set logging on
```
if I do this, the gdb-dashboard disappears and does no more work.
Is there anything wrong with the structure of the file?

**Comment by cyrus-and** [comment]
Because you have to set `logging redirect` to `off`. The help system states:

```
>>> help set logging redirect
Set the logging output mode.
If redirect is off, output will go to both the screen and the log file.
If redirect is on, output will go only to the log file.
```
and you want the output to go to both the screen and the log file.

**Comment by volviq** [comment]
thanks. I thought I turned on individual parts of those settings lines, apparently I wasn't careful enough (also the .swp file of vim caused confusion, as it is also in the .gdbinit.d folder)
