### ISSUE TITLE
gdb-dashboard loses "Output/messages" on update

### ISSUE THREAD

**Issue by ajohnson23** [cyrus-and/gdb-dashboard#8]
I've noticed that the content of the Output/messages area gets reset any time dashboard is executed. Is this expected? Is there any way to preserve the content of the Output/messages area across dashboard updates?

**Comment by cyrus-and** [comment]
They are not lost, if you scroll up you can still find them. The dashboard is not a real curses-like interface; the screen is cleared every time to simulate a proper TUI. The main reason is that GDB dashboard purposefully is not a proper frontend, rather it is an aid/enhancement to GDB. So the target program output, the commands feedback and the dashboard itself are intermingled within the same terminal.

You can, however use [another terminal](https://sourceware.org/gdb/onlinedocs/gdb/Input_002fOutput.html) for the program I/O.

I understand that all this may appear confusing, I'm taking into consideration to implement an option to separate the dashboard output from the standard logging stream.

**Comment by ajohnson23** [comment]
I use tmux, and it would seem the problem is made a bit worse by that -- scrolling back is more confusing than scrolling back in a non-tmux terminal.

**Comment by cyrus-and** [comment]
> I use tmux, and it would seem the problem is made a bit worse by that -- scrolling back is more confusing than scrolling back in a non-tmux terminal.

Yeah I feel you, I'm a tmux user too! The idea is that the information shown in that area is (usually) only meaningful during the current step, no more. At this stage problem is not how to split dashboard, program I/O, etc. it is how to do that in a easy and reliable way.

**Comment by ajohnson23** [comment]
Ah yes -- I understand what you're saying, but the way I use gdb-dashboard, I have it updating any time I "up" or "down", so I end up "losing" relevant output in that case.

I suppose it might be possible to send gdbs output to a file and read that into my own module.... Does that sound sensible for me to implement?

**Comment by ajohnson23** [comment]
Actually a ptty might be required, at which point we're in *nix non-portable land.
Does gdb-dashboard work in windows?

**Comment by cyrus-and** [comment]
> Ah yes -- I understand what you're saying, but the way I use gdb-dashboard, I have it updating any time I "up" or "down", so I end up "losing" relevant output in that case.

If the relevant output is the program I/O then using another terminal may be a feasible solution.

Here's a quick way to do that:

1. open a terminal, type `tty; tail -f /dev/null` and note the output, e.g. `/dev/pts/5`;
2. open another terminal and start GDB with `gdb --tty /dev/pts/5`.

If you can live with the warning (`warning: GDB: Failed to set controlling terminal: Operation not permitted`) this is quite convenient. But it is not something I feel like to automatize yet.

> Does gdb-dashboard work in windows?

Never tried actually.

**Comment by ajohnson23** [comment]
Just for kicks, I tried using the tty setting in gdb to pump output to a pseudo tty, but it doesn't catch all output... some still gets sent to the controlling terminal. Maybe it's missing stderr and only handling stdout, but I'm not sure. If it worked I was going to hack support into gdb-dashboard in my own fork, but it seems unreliable unfortunately :/

This patch to gdb, which adds "set inferior-std(in/out/err)" may help, but it's pretty fresh and I'm not even sure what became of it.
https://sourceware.org/ml/gdb-patches/2015-05/msg00131.html

I'll keep this situation in the back of my mind, though. Let me know if anything occurs to you about it.

Overall though, thanks much for gdb-dashboard. It's an improvement over vanilla gdb without being too heavy or overly prescriptive.

**Comment by cyrus-and** [comment]
> some still gets sent to the controlling terminal

Uh, it always worked to me, never used it intensively though.

Anyway, I'm releasing a new feature that will allow to send the dashboard itself to another file or TTY. It's the other way around with respect to what you're trying to do but I think that the final effect will be the same, or even better as we don't have to fiddle with the GDB TTY. Stay tuned...

**Comment by ajohnson23** [comment]
That sounds like a nice way to go about it. Under that mode of operation, the other modules in the dashboard won't be interfered with/pushed around when you're running different commands in gdb which is great.

**Comment by cyrus-and** [comment]
FYI @ajohnson23 @dariomanesku @oblitum

Since you manifested some interest in this or similar issues, I think that you may find [this new feature](/cyrus-and/gdb-dashboard#dashboard--output-file) useful.

Thanks for your support!

**Comment by oblitum** [comment]
@cyrus-and great, thanks for instructions!

**Comment by ajohnson23** [comment]
I send the dashboard to a separate tmux pane now and gdb/program output stays completely undisturbed. Awesome.
