### ISSUE TITLE
Prompt has identical color as background under "solarized dark" color scheme

### ISSUE THREAD

**Issue by sunqingyao** [cyrus-and/gdb-dashboard#80]
At first I thought the prompt `>>>` isn't printed due to some internal error:

![screen shot 2017-08-29 at 23 12 20](https://user-images.githubusercontent.com/13443062/29828523-86be9306-8d0f-11e7-8361-898a79dec1b7.png)

But when I press <kbd>command </kbd> + <kbd> A </kbd>, I saw:

![screen shot 2017-08-29 at 23 13 24](https://user-images.githubusercontent.com/13443062/29828567-ad34e134-8d0f-11e7-936c-a15902b18584.png)

Since "solarized dark" is a popular color scheme, you may want to address this issue :)

**Comment by cyrus-and** [comment]
Thanks for reporting, but this is a Solarized problem as you can see the [background][1] color is the same as the [bright black][2] one.

You can customize the prompt color though, for example:

    dashboard -style prompt_not_running '\\[\\e[30m\\]>>>\\[\\e[0m\\]'

[1]: https://github.com/altercation/solarized/blob/e40cd4130e2a82f9b03ada1ca378b7701b1a9110/iterm2-colors-solarized/Solarized%20Dark.itermcolors#L149-L157
[2]: https://github.com/altercation/solarized/blob/e40cd4130e2a82f9b03ada1ca378b7701b1a9110/iterm2-colors-solarized/Solarized%20Dark.itermcolors#L131-L139
