### ISSUE TITLE
why don't work?

### ISSUE THREAD

**Issue by rfyiamcool** [cyrus-and/gdb-dashboard#83]
ruifengyun@localhost:~ $ tty /dev/pts/3
and then I run the command below, and nothing happened.
```
>>> dashboard -output /dev/pts/3
```

**Comment by giordi91** [comment]
did you actually start the debugging process? the dashboard only start after you run the debugged program

**Comment by cyrus-and** [comment]
@rfyiamcool: @giordi91 is right, see #77.
