### ISSUE TITLE
return "module disabled"

### ISSUE THREAD

**Issue by theking0** [cyrus-and/gdb-dashboard#84]
version: gdb  8.0 (compiled with "--with-system-gdbinit")
System: Linux Mint 18.2 Cinnamon x64-bit

No module is loaded on the dashboard.

 if try to run:

```
>>> dashboard memory
memory module disabled
>>> dashboard assembly 
assembly module disabled
```

this for all modules

am I making a mistake?

**Comment by cyrus-and** [comment]
A stated in the [README][1]:

> Every module adds its own subcommand dashboard <module> which is used to toggle the enable flag and to redisplay the dashboard.

For example:

```
>>> dashboard assembly 
assembly module disabled
>>> dashboard assembly 
assembly module enabled
```

All modules are enabled by default, you can also use the [`dashboard -layout`][2] command to decide qhat to enable.

[1]: https://github.com/cyrus-and/gdb-dashboard#modules-subcommands
[2]: https://github.com/cyrus-and/gdb-dashboard#dashboard--layout-directive
