### ISSUE TITLE
Storing session to text file?

### ISSUE THREAD

**Issue by giordi91** [cyrus-and/gdb-dashboard#85]
the main source of pain (at least for me) when dealing with gdb is having to set over and over the same breakpoint, expression etc, since I find myself going in and out often.
Would it be possible to store a JSON file or similar in the same executable folder storing simple stuff like all the breakpoints and expressions? Then when you run again, if such file is present it will load it or ask to load it restoring the values? or even just have a command to load it when we need it.

By the way, the dashboard is massively helpful thanks for that.

**Comment by cyrus-and** [comment]
Glad to hear that! :)

First of all this is about GDB itself and one of the design goal of the dashboard is to not introduce additional commands, especially commands that would affect the workflow of developers.

Said that, GDB already has something useful, see [Per-project configuration][1]. Yet of course this misses the part where the *state* is automatically saved. (BTW is not easy to figure out what a *state* is.) If you can live with the manual editing of such file then you're done. (FYI you can also manually `source` another GDB file.)

The dashboard won't provide any additional helpers in this sense, but you can write a custom Python/GDB file that perform the logic that you need and place it in `~/.gdbinit.d/` then maybe you can use a hook to dump the state (and the code needed to restore it) to a project-local `.gdbinit` file, for example:

```
define hook-quit
python dump_state()
end
```

Finally, and this might be obvious, you don't need to quit GDB after each program execution neither you do if you change the source and recompile, it is perfectly capable of figure this out:

```
`/your/program' has changed; re-reading symbols.
```

Hope it helps.

[1]: https://github.com/cyrus-and/gdb-dashboard#per-project-configuration
