### ISSUE TITLE
Changing stack limit breaks interrupts

### ISSUE THREAD

**Issue by lucianposton** [cyrus-and/gdb-dashboard#87]
![out](https://user-images.githubusercontent.com/646121/31184537-79d56436-a8de-11e7-9ef5-5c8498cd4174.gif)

When I `da stack -style 5` in the above gif, gdb-dashboard enters a state where ctrl+c fails to stop the program to debug. Each time it seems to continue the program after the message about receiving SIGINT.

Other settings seem okay e.g. setting the asm context.

gdb 7.12.1
gdb-dashboard 0b7e367e4085b567997

**Comment by lucianposton** [comment]
fyi, I wasn't able to repro this bug on another project that had source code.

**Comment by cyrus-and** [comment]
See #88 for now as it seems to be related.
