### ISSUE TITLE
gdb 8.0.1 -- gives error .gdbinit:1435: Error in sourced command file:

### ISSUE THREAD

**Issue by SandyWare** [cyrus-and/gdb-dashboard#90]
My gdb version gdb 8.0.1 , I need gdb 8.0.1 to work on C++17.
Python 2.7.6
Ubuntu 14.04.5 LTS
Codename:	trusty

When I launch gdb it gives me below error :
     -- gives error .gdbinit:1435: Error in sourced command file

Any idea how I can fix it ?

**Comment by cyrus-and** [comment]
Usually a backtrace is displayed along with that error, please provide the whole output.

**Comment by SandyWare** [comment]
My gdb 8.0.1 was get mess up.   Issues was with gdb 8.0.1, So I rollback to  gdb 7.7.1 its work good. Thanks for nice tool.
