### ISSUE TITLE
Upon seg fault, using "frame n" should update windows

### ISSUE THREAD

**Issue by MikeBrWade** [cyrus-and/gdb-dashboard#91]
The source/assembly/stack windows should update (the others might be more difficult) but those three would be extremely useful.

Fantastic tool btw!

**Comment by cyrus-and** [comment]
Thanks! You can set up an [hook][1] for that:

```
define hookpost-frame
dashboard
end
```

[1]: https://github.com/cyrus-and/gdb-dashboard#dashboard--enabled-onoff

**Comment by MikeBrWade** [comment]
Sounds very promising, is there a way to reload configuration of that .gdbinit file without restarting it? I have an active session with piped dashboard pieces to a dozen console windows it would be a pain to get that all set back up.

**Comment by cyrus-and** [comment]
You can just paste the relevant commands in the current session. Alternatively a simple `source ~/.gdbinit.d/whatever` should do, provided that the code there can be safely run twice or more.

**Comment by MikeBrWade** [comment]
Works great! Thanks for the help.

**Comment by cyrus-and** [comment]
You're welcome! :)
