### ISSUE TITLE
Source Window Keyboard &| Mouse interaction

### ISSUE THREAD

**Issue by MikeBrWade** [cyrus-and/gdb-dashboard#93]
Not sure if this is possible because I think they are output/display terminals only via the streaming IO interface to the tty.  But it would be nice if we could double click on a variable to add it to the watch, or maybe via the keyboard have it under the cursor and "w" adds to watch, "m" adds to memory, etc.

Copy pasting, or hand typing alot of watches and unwatches does slow down the flow a bit.

**Comment by cyrus-and** [comment]
Unfortunately this is not possible<sup>&#42;</sup>, the output is just some text (with ANSI codes) printed between subsequent prompts. GDB dashboard is not a proper frontend, it is just a tool that aims to make the interaction with vanilla GDB a bit less painful by providing a number of useful information automatically.

> Copy pasting, or hand typing alot of watches and unwatches does slow down the flow a bit.

You can obviously use completions which seem to work pretty well in GDB. Another option would be writing your own custom command using the [Python API][2] that fetches the mouse selection and do something with it. Follows a very simple, yet effective, example (for Linux, but can be easily adapted):

```gdb
python
def do_with_selection(format):
    import subprocess
    selection = subprocess.check_output(['xclip', '-o']).decode('utf8')
    gdb.execute(format.format(selection))
end

define mw
python do_with_selection('dashboard memory watch {}')
end

define ew
python do_with_selection('dashboard expression watch {}')
end
```

Place it in a file within `~/.gdbinit.d/`. Test it by selecting an expression and then issuing `mw` or `ew` (yes they are proper commands and not simply keystrokes). One cold argue whether this is more convenient than copy/paste or not...

---

&#42; Actually this *could* be possible with a fair amount of ANSI-fu but eventually one would end up with a frontend built *into* GDB itself while the proper way to go is the opposite: writing a frontend using whatever UI/language that interacts with GDB via a [proper protocol][1].

[1]: https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html
[2]: https://sourceware.org/gdb/onlinedocs/gdb/Python-API.html

**Comment by MikeBrWade** [comment]
Yep all valid points, figured it couldn't hurt to mention it.  I will try your suggestion using xclip and the command.
