### ISSUE TITLE
Watch & Unwatch Seem to not do what's expected

### ISSUE THREAD

**Issue by MikeBrWade** [cyrus-and/gdb-dashboard#95]
dashboard expression watch XXX <- Works
dashboard expression unwatch XXX <- Says "expression not watched" and doesn't unwatch it

dashboard expression clear does work but that blows away all my watches, is there some aspect this I am not seeing?

**Comment by cyrus-and** [comment]
You unwatch expression using the numeric id (the number between `[]`).

```
>>> help dashboard expressions unwatch
Stop watching an expression by id.
```

**Comment by MikeBrWade** [comment]
RTFM I guess, I did look but didn't notice it... Reading comprehension :-P
