### ISSUE TITLE
Debian - .gdbinit:1435: Error in sourced command file

### ISSUE THREAD

**Issue by jbfleury56** [cyrus-and/gdb-dashboard#96]
```
/home/username/.gdbinit:1435: Error in sourced command file:
Scripting in the "Python" language is not supported in this copy of GDB.
```
gdb-dashboard doesn't work with debian 9 stable. I did the wget command and here's what' displaying when i'm doing
```
gdb a.out
```
It worked perfectly fine on fedora 26 though

**Comment by Arkanosis** [comment]
Try switching from the `gdb` package to the `gdb-python2` package. The latter is linked against Python.

**Comment by jbfleury56** [comment]
> Try switching from the gdb package to the gdb-python2 package. The latter is linked against Python.

Thanks a lot it worked perfectly!
