### ISSUE TITLE
Change comment color in source window

### ISSUE THREAD

**Issue by MikeBrWade** [cyrus-and/gdb-dashboard#97]
Dark blue on black is really hard to read, I looked and it seems like its possible to modify it but I am not clear on the procedure, can you point me to the right place?

Thanks!

**Comment by cyrus-and** [comment]
While it's possible to customize the dashboard colors by specifying [ANSI sequences][1], you cannot explicitly alter the syntax highlighting but you can change the Pygments [style][2] and choose one which is more readable for your terminal.

[1]: https://github.com/cyrus-and/gdb-dashboard#ansi-escape-codes
[2]: https://github.com/cyrus-and/gdb-dashboard#syntax-highlighting

---

IMHO though there should not be "hard to read" colors in a terminal, I suggest to tune your palette, [here][3] is mine for example. Test it with:

```bash
for n in {0..7}; do
    for b in 0 1; do
        printf "\x1b[${b};3${n}mANSI \x1b[0m"
    done
    echo
done
```

![2017-11-07-203315_492x318_scrot](https://user-images.githubusercontent.com/1660263/32513612-ebaf54c2-c3fa-11e7-9cdb-47dc63d11b97.png)

[3]: https://github.com/cyrus-and/dotfiles/blob/2b5499b5701b2202f711e90391bc855fcc64b419/xorg/.Xresources#L43-L58

**Comment by MikeBrWade** [comment]
Yeah its this dark blue I can't read.
![image](https://user-images.githubusercontent.com/286241/32515991-b765ffac-c3b6-11e7-85b0-97fb0431fab1.png)

**Comment by cyrus-and** [comment]
Try tuning `*color4` and `*color12` in your `~/.Xresources` like this for example:

```
*color4: #0074ff
*color12: #0074ff
```

Or whatever shade of blue you like, I find the above quite readable.

**Comment by MikeBrWade** [comment]
Is there a way to change this:
![image](https://user-images.githubusercontent.com/286241/32516374-01140012-c3b8-11e7-9694-a3846666a402.png)

Aside from restarting my session?

like "dashboard style set syntax_highlighting emacs"
or something so I can try different ones?

**Comment by cyrus-and** [comment]
Just issue the style command with the argument:

    dashboard -style syntax_highlighting 'emacs'

**Comment by cyrus-and** [comment]
Documented here:

```
>>> help dashboard -style 
Access the stylable attributes.
Without arguments print all the stylable attributes. Subcommands are used to set
or print (when the value is omitted) individual attributes.
[...]
```

**Comment by MikeBrWade** [comment]
HA I was so close.. i was trying that, but I didn't have the single quotes around it and it didn't like it so I thought there was more to it than I knew.

**Comment by cyrus-and** [comment]
Yeah admittedly that part is a bit obscure and kind of violates the usual GDB behavior but the `dashboard -style` command is the bridge between GDB and Python, and I needed to represent several types (string integers, booleans, etc.) hence the quotes. At least one can figure it out by printing the old value (`'vim'` in your case).

**Comment by MikeBrWade** [comment]
Thanks, 'manni' is much easier to read, as always you rock.

**Comment by milesfrain** [comment]
For Ubuntu users, the `.Xresources` suggestion may not fix this comment color issue.

I found on my system that these settings are overridden by Gnome terminal palatte settings in `Edit > Profile Preferences > Colors`.

I'm also not sure if pygments even uses the ANSI colors when formatting source and assembly code. It seems that these ANSI colors are only used for the rest of the dashboard gui.

Anyway, I got things working by changing to a non-vim syntax highlighting style.

Tips for other folks with similar issues who find this page:

1. First run the commands from the syntax highlighting help section to get a list of available styles.
https://github.com/cyrus-and/gdb-dashboard#syntax-highlighting 
```
python from pygments.styles import get_all_styles as styles
python for s in styles(): print(s)
```
2. Then use the command posted earlier to try each syle within GDB to find which one looks best.
```dashboard -style syntax_highlighting 'monokai'```

3. Finally, modify `.gdbinit` to use your preferred style.

Is there a way to merge steps 1 and 2 using the GDB python interpreter to automatically cycle through and apply each syntax highlighting choice, perhaps separated by the user pressing return between each one? I'm not sure how to send arbitrary command to GDB from python. I'm guessing it will look something like this, although I'm not sure what to replace `execute_gdb_command` with:
```python for s in styles(): print(s); execute_gdb_command('dashboard -style syntax_highlighting \' + s + \''); input()```

**Comment by cyrus-and** [comment]
@milesfrain

> I'm also not sure if pygments even uses the ANSI colors when formatting source and assembly code. It seems that these ANSI colors are only used for the rest of the dashboard gui.

It does use ANSI codes, it just may use (according to the style? always?) [256-colors codes][1] you can customize them in the same way, it simply is more annoying...

[1]: https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit
