### ISSUE TITLE
Re-Order Expressions and Memory watches

### ISSUE THREAD

**Issue by MikeBrWade** [cyrus-and/gdb-dashboard#98]
Is there anyway to reorder them in the display without doing an "Clear" and resetting them all? Sometimes while deep in debugging you have dozens open.. but you want to leave some around and reorder them for the issue you are looking at.

**Comment by cyrus-and** [comment]
Reordering a list via a REPL interface would be very cumbersome, you necessarily have to specify at least the index of the item that you want to move and possibly the desired position or simply using a pick-one-and-move-to-first-position strategy.

I guess your best chance is to clear the list the use the built-in GDB history (possibly taking advantage of the incremental search feature `Ctrl-R` of readline) to re-watch expressions or memory locations.

If you deal with the same project very often you may even decide to use a [per-project configuration file](https://github.com/cyrus-and/gdb-dashboard#per-project-configuration) where you define GDB functions that helps you restoring your watchpoints.

Pushing this even further you may want to develop a custom module in which you introduce the concept of *issue*: a set of breakpoints, watchpoints etc. that you can save to external files and manage and restore from GDB. See the [example](https://github.com/cyrus-and/gdb-dashboard#example).
